In [1]:
# ============================================================
# Patch extraction pipeline - resume / memory safe version
# ------------------------------------------------------------
# 목적:
#   - 전처리 완료 결과에서 patch 추출
#   - 환자별 patch CSV로 바로 저장
#   - 이미 처리된 환자는 자동 skip
#   - 전체 patch를 메모리에 한 번에 쌓지 않음
#   - MemoryError 방지
# ============================================================

from pathlib import Path
import json
import gc
import time
from collections import Counter

import numpy as np
import pandas as pd
import SimpleITK as sitk
from tqdm import tqdm
from scipy.ndimage import distance_transform_edt


# ============================================================
# 1. CONFIG
# ============================================================

PATCH_CONFIG = {
    # 전체 전처리 결과 폴더
    "preprocess_root": r"E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest",

    # 패치 결과 저장 폴더 이름
    "out_dir_name": "patch_all_v2_tslungguard_nochest_resume",

    # patch 크기
    "patch_size": 32,

    # patch 이동 간격
    # 32 크기 patch를 16칸씩 이동하므로 반씩 겹침
    "patch_stride": 16,

    # slice 자체에 pure lung이 거의 없으면 제외
    "min_slice_pure_lung_ratio": 0.01,

    # 너무 작은 폐 mask slice 제외
    "min_pure_lung_pixels_per_slice": 100,

    # patch 안 pure lung 비율
    # 0.70이면 patch 안 70% 이상이 pure lung이어야 선택
    "min_patch_pure_lung_ratio": 0.70,

    # patch 안 장기 제외 영역이 2% 넘으면 제외
    "max_patch_organ_ratio": 0.02,

    # 중심부 / 말초부 기준
    # 폐 경계에서 가장 먼 거리 대비 평균 0.5 이상이면 central
    "central_distance_ratio_threshold": 0.50,

    # HU histogram bin
    "hist_bins": [
        -1000, -900, -800, -700, -600, -500, -400,
        -300, -200, -100, 0, 100, 200, 400
    ],

    # 이미 처리된 환자 CSV가 있으면 skip
    "skip_existing_patient_csv": True,

    # feature 계산 기준
    # False: 기존 방식 유지, patch 전체 HU로 feature 계산
    # True : patch 안 pure_lung 픽셀만 골라 feature 계산
    "feature_use_pure_lung_pixels_only": True,
}


PRE_ROOT = Path(PATCH_CONFIG["preprocess_root"])
PATCH_OUT = PRE_ROOT / PATCH_CONFIG["out_dir_name"]
PATCH_BY_PATIENT_DIR = PATCH_OUT / "patches_by_patient"
PATCH_DONE_DIR = PATCH_OUT / "done_markers"

PATCH_OUT.mkdir(parents=True, exist_ok=True)
PATCH_BY_PATIENT_DIR.mkdir(parents=True, exist_ok=True)
PATCH_DONE_DIR.mkdir(parents=True, exist_ok=True)

with open(PATCH_OUT / "patch_config.json", "w", encoding="utf-8") as f:
    json.dump(PATCH_CONFIG, f, indent=2, ensure_ascii=False)

print("========== PATCH CONFIG ==========")
print("PRE_ROOT:", PRE_ROOT)
print("PATCH_OUT:", PATCH_OUT)
print("PATCH_BY_PATIENT_DIR:", PATCH_BY_PATIENT_DIR)


# ============================================================
# 2. helper functions
# ============================================================

def format_seconds(seconds: float) -> str:
    seconds = int(seconds)

    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60

    if h > 0:
        return f"{h}시간 {m}분 {s}초"

    if m > 0:
        return f"{m}분 {s}초"

    return f"{s}초"


def read_nii_array(path: Path):
    img = sitk.ReadImage(str(path))
    arr = sitk.GetArrayFromImage(img)
    return img, arr


def safe_patient_csv_name(patient_id: str) -> str:
    return (
        str(patient_id)
        .replace("\\", "_")
        .replace("/", "_")
        .replace(":", "_")
        .replace("*", "_")
        .replace("?", "_")
        .replace('"', "_")
        .replace("<", "_")
        .replace(">", "_")
        .replace("|", "_")
    )


def calc_patch_features(patch_hu, hist_bins):
    """
    patch HU 값으로 간단 feature 계산.
    patch_hu는 2D patch이거나, pure_lung 픽셀만 골라낸 1D 배열일 수 있음.
    """

    x = patch_hu.reshape(-1)

    if x.size == 0:
        feat = {
            "hu_mean": np.nan,
            "hu_std": np.nan,
            "hu_min": np.nan,
            "hu_max": np.nan,
            "hu_p05": np.nan,
            "hu_p25": np.nan,
            "hu_p50": np.nan,
            "hu_p75": np.nan,
            "hu_p95": np.nan,
        }

        for i in range(len(hist_bins) - 1):
            feat[f"hist_bin_{i:02d}"] = np.nan

        return feat

    x = x.astype(np.float32, copy=False)

    hist, _ = np.histogram(x, bins=hist_bins)
    hist = hist.astype(np.float32)

    hist_sum = hist.sum()

    if hist_sum > 0:
        hist = hist / hist_sum

    feat = {
        "hu_mean": float(np.mean(x)),
        "hu_std": float(np.std(x)),
        "hu_min": float(np.min(x)),
        "hu_max": float(np.max(x)),
        "hu_p05": float(np.percentile(x, 5)),
        "hu_p25": float(np.percentile(x, 25)),
        "hu_p50": float(np.percentile(x, 50)),
        "hu_p75": float(np.percentile(x, 75)),
        "hu_p95": float(np.percentile(x, 95)),
    }

    for i, v in enumerate(hist):
        feat[f"hist_bin_{i:02d}"] = float(v)

    return feat


def get_z_level(z, valid_z_min, valid_z_max):
    """
    lung range 안에서 z 위치를 lower / middle / upper로 나눔.
    """

    if valid_z_max <= valid_z_min:
        return "middle", 0.5

    z_ratio = (z - valid_z_min) / float(valid_z_max - valid_z_min)
    z_ratio = float(np.clip(z_ratio, 0.0, 1.0))

    if z_ratio < 1.0 / 3.0:
        return "lower", z_ratio

    if z_ratio < 2.0 / 3.0:
        return "middle", z_ratio

    return "upper", z_ratio


def get_central_peripheral(dist_patch_values, threshold=0.5):
    """
    patch 안 pure_lung 픽셀들의 distance ratio 평균으로 central/peripheral 결정.
    """

    if len(dist_patch_values) == 0:
        return "peripheral", 0.0

    mean_ratio = float(np.mean(dist_patch_values))

    if mean_ratio >= threshold:
        return "central", mean_ratio

    return "peripheral", mean_ratio


def get_left_right_by_patch_center(x0, patch_size, width):
    """
    좌우 정보는 일단 metadata로만 저장.
    image_left / image_right는 영상 좌표 기준.
    """

    cx = x0 + patch_size / 2.0

    if cx < width / 2.0:
        return "image_left"

    return "image_right"


# ============================================================
# 3. one patient patch extraction
# ============================================================

def extract_patches_one_patient(patient_id, row0, config):
    patch_size = int(config["patch_size"])
    patch_stride = int(config["patch_stride"])
    patch_area = patch_size * patch_size

    ct_path = Path(row0["ct_1mm_lung_range_nii"])
    pure_path = Path(row0["pure_lung_lung_range_nii"])
    organ_path = Path(row0["organ_exclusion_lung_range_nii"])

    if not ct_path.exists():
        raise FileNotFoundError(f"CT lung range 없음: {ct_path}")

    if not pure_path.exists():
        raise FileNotFoundError(f"pure lung range 없음: {pure_path}")

    if not organ_path.exists():
        raise FileNotFoundError(f"organ exclusion range 없음: {organ_path}")

    _, ct_arr = read_nii_array(ct_path)
    _, pure_arr = read_nii_array(pure_path)
    _, organ_arr = read_nii_array(organ_path)

    # 중요:
    # ct_arr는 전체 float32 복사하지 않음.
    # feature 계산할 때 patch 단위로만 float32 변환함.
    pure_arr = pure_arr > 0
    organ_arr = organ_arr > 0

    if ct_arr.shape != pure_arr.shape:
        raise RuntimeError(f"{patient_id}: CT와 pure_lung shape 다름")

    if ct_arr.shape != organ_arr.shape:
        raise RuntimeError(f"{patient_id}: CT와 organ_exclusion shape 다름")

    zdim, h, w = ct_arr.shape

    pure_area_per_slice = pure_arr.sum(axis=(1, 2))
    pure_ratio_per_slice = pure_area_per_slice / float(h * w)

    valid_z_indices = np.where(
        (pure_ratio_per_slice >= float(config["min_slice_pure_lung_ratio"]))
        & (pure_area_per_slice >= int(config["min_pure_lung_pixels_per_slice"]))
    )[0]

    if len(valid_z_indices) == 0:
        summary = {
            "patient_id": patient_id,
            "status": "no_valid_z",
            "zdim": int(zdim),
            "height": int(h),
            "width": int(w),
            "valid_z_min": "",
            "valid_z_max": "",
            "valid_z_count": 0,
            "candidate_patch_count_before_filter": 0,
            "selected_patch_count": 0,
        }

        del ct_arr, pure_arr, organ_arr
        gc.collect()

        return [], summary

    valid_z_min = int(valid_z_indices.min())
    valid_z_max = int(valid_z_indices.max())

    patch_rows = []
    patient_candidate_count = 0
    patient_selected_count = 0

    for z in valid_z_indices:
        z = int(z)

        ct_slice = ct_arr[z]
        pure_slice = pure_arr[z]
        organ_slice = organ_arr[z]

        dist_map = distance_transform_edt(pure_slice)
        max_dist = float(dist_map.max())

        if max_dist <= 0:
            continue

        dist_ratio_map = dist_map / (max_dist + 1e-6)

        z_level, z_ratio = get_z_level(
            z=z,
            valid_z_min=valid_z_min,
            valid_z_max=valid_z_max,
        )

        for y0 in range(0, h - patch_size + 1, patch_stride):
            for x0 in range(0, w - patch_size + 1, patch_stride):
                patient_candidate_count += 1

                y1 = y0 + patch_size
                x1 = x0 + patch_size

                pure_patch = pure_slice[y0:y1, x0:x1]
                organ_patch = organ_slice[y0:y1, x0:x1]

                pure_pixels = int(pure_patch.sum())
                organ_pixels = int(organ_patch.sum())

                pure_ratio = pure_pixels / float(patch_area)
                organ_ratio = organ_pixels / float(patch_area)

                if pure_ratio < float(config["min_patch_pure_lung_ratio"]):
                    continue

                if organ_ratio > float(config["max_patch_organ_ratio"]):
                    continue

                ct_patch = ct_slice[y0:y1, x0:x1]

                dist_patch = dist_ratio_map[y0:y1, x0:x1]
                dist_values_inside_pure = dist_patch[pure_patch > 0]

                central_bin, central_ratio_mean = get_central_peripheral(
                    dist_patch_values=dist_values_inside_pure,
                    threshold=float(config["central_distance_ratio_threshold"]),
                )

                position_bin = f"{z_level}_{central_bin}"

                left_right_bin = get_left_right_by_patch_center(
                    x0=x0,
                    patch_size=patch_size,
                    width=w,
                )

                if bool(config["feature_use_pure_lung_pixels_only"]):
                    feature_pixels = ct_patch[pure_patch > 0]
                else:
                    feature_pixels = ct_patch

                features = calc_patch_features(
                    patch_hu=feature_pixels,
                    hist_bins=config["hist_bins"],
                )

                row = {
                    "patient_id": patient_id,

                    "local_z": int(z),
                    "y0": int(y0),
                    "x0": int(x0),
                    "y1": int(y1),
                    "x1": int(x1),

                    "patch_size": int(patch_size),
                    "patch_stride": int(patch_stride),

                    "pure_lung_pixels": int(pure_pixels),
                    "organ_pixels": int(organ_pixels),
                    "pure_lung_patch_ratio": float(pure_ratio),
                    "organ_patch_ratio": float(organ_ratio),
                    "slice_pure_lung_ratio": float(pure_ratio_per_slice[z]),

                    "z_level": z_level,
                    "z_ratio": float(z_ratio),
                    "central_peripheral": central_bin,
                    "central_distance_ratio_mean": float(central_ratio_mean),
                    "position_bin": position_bin,

                    "left_right_metadata": left_right_bin,

                    "ct_1mm_lung_range_nii": str(ct_path),
                    "pure_lung_lung_range_nii": str(pure_path),
                    "organ_exclusion_lung_range_nii": str(organ_path),
                }

                row.update(features)

                patch_rows.append(row)
                patient_selected_count += 1

    summary = {
        "patient_id": patient_id,
        "status": "success",
        "zdim": int(zdim),
        "height": int(h),
        "width": int(w),
        "valid_z_min": int(valid_z_min),
        "valid_z_max": int(valid_z_max),
        "valid_z_count": int(len(valid_z_indices)),
        "candidate_patch_count_before_filter": int(patient_candidate_count),
        "selected_patch_count": int(patient_selected_count),
    }

    del ct_arr, pure_arr, organ_arr
    gc.collect()

    return patch_rows, summary


# ============================================================
# 4. run patch extraction with resume
# ============================================================

metadata_path = PRE_ROOT / "metadata_slices.csv"

if not metadata_path.exists():
    raise FileNotFoundError(f"metadata_slices.csv 없음: {metadata_path}")

slice_df = pd.read_csv(metadata_path)

required_cols = [
    "patient_id",
    "ct_1mm_lung_range_nii",
    "pure_lung_lung_range_nii",
    "organ_exclusion_lung_range_nii",
]

for c in required_cols:
    if c not in slice_df.columns:
        raise RuntimeError(f"metadata_slices.csv에 필요한 컬럼 없음: {c}")

patient_ids = sorted(slice_df["patient_id"].unique())

print("========== PATCH EXTRACTION START ==========")
print("patient count:", len(patient_ids))
print("PATCH_OUT:", PATCH_OUT)

summary_rows = []
error_rows = []

global_start = time.perf_counter()
total_cases = len(patient_ids)

for case_idx, patient_id in enumerate(
    tqdm(
        patient_ids,
        desc="Patch extraction by patient",
        total=total_cases,
        ncols=100,
        ascii=True,
        leave=True,
        dynamic_ncols=False,
    ),
    start=1
):
    start = time.perf_counter()

    patient_safe = safe_patient_csv_name(patient_id)
    patient_csv = PATCH_BY_PATIENT_DIR / f"{patient_safe}.csv"
    patient_tmp_csv = PATCH_BY_PATIENT_DIR / f"{patient_safe}.tmp.csv"
    done_marker = PATCH_DONE_DIR / f"{patient_safe}.done"

    if (
        bool(PATCH_CONFIG["skip_existing_patient_csv"])
        and patient_csv.exists()
        and done_marker.exists()
    ):
        elapsed = time.perf_counter() - start

        summary_rows.append({
            "patient_id": patient_id,
            "status": "skipped_existing",
            "patient_csv": str(patient_csv),
            "elapsed_seconds": round(elapsed, 2),
            "elapsed_readable": format_seconds(elapsed),
        })

        continue

    try:
        pdf = slice_df[slice_df["patient_id"] == patient_id]

        if len(pdf) == 0:
            raise RuntimeError(f"{patient_id}: metadata_slices.csv에 환자 row 없음")

        row0 = pdf.iloc[0]

        patch_rows, summary = extract_patches_one_patient(
            patient_id=patient_id,
            row0=row0,
            config=PATCH_CONFIG,
        )

        patient_df = pd.DataFrame(patch_rows)

        # tmp 파일로 먼저 저장하고, 성공하면 최종 파일명으로 교체
        patient_df.to_csv(patient_tmp_csv, index=False, encoding="utf-8-sig")
        patient_tmp_csv.replace(patient_csv)

        done_marker.write_text("done", encoding="utf-8")

        elapsed = time.perf_counter() - start
        total_elapsed = time.perf_counter() - global_start
        avg_per_case = total_elapsed / case_idx
        remain = total_cases - case_idx
        eta = avg_per_case * remain

        summary.update({
            "patient_csv": str(patient_csv),
            "elapsed_seconds": round(elapsed, 2),
            "elapsed_readable": format_seconds(elapsed),
            "total_elapsed_seconds": round(total_elapsed, 2),
            "total_elapsed_readable": format_seconds(total_elapsed),
            "estimated_remaining_seconds": round(eta, 2),
            "estimated_remaining_readable": format_seconds(eta),
        })

        summary_rows.append(summary)

        pd.DataFrame(summary_rows).to_csv(
            PATCH_OUT / "patch_patient_summary.csv",
            index=False,
            encoding="utf-8-sig",
        )

        print(
            f"[PATCH] {patient_id} 완료 "
            f"({case_idx}/{total_cases}) | "
            f"patch={len(patient_df)} | "
            f"이번 환자: {format_seconds(elapsed)} | "
            f"전체 경과: {format_seconds(total_elapsed)} | "
            f"예상 남은 시간: {format_seconds(eta)}"
        )

        del patch_rows, patient_df
        gc.collect()

    except Exception as e:
        elapsed = time.perf_counter() - start

        error_rows.append({
            "patient_id": patient_id,
            "error": str(e),
            "elapsed_seconds": round(elapsed, 2),
            "elapsed_readable": format_seconds(elapsed),
        })

        pd.DataFrame(error_rows).to_csv(
            PATCH_OUT / "patch_errors.csv",
            index=False,
            encoding="utf-8-sig",
        )

        print("[ERROR]", patient_id, str(e))
        gc.collect()


summary_df = pd.DataFrame(summary_rows)
summary_df.to_csv(
    PATCH_OUT / "patch_patient_summary.csv",
    index=False,
    encoding="utf-8-sig",
)

if len(error_rows) > 0:
    pd.DataFrame(error_rows).to_csv(
        PATCH_OUT / "patch_errors.csv",
        index=False,
        encoding="utf-8-sig",
    )

print("\n========== PATCH EXTRACTION FINISHED ==========")
print("PATCH_OUT:", PATCH_OUT)
print("patient csv dir:", PATCH_BY_PATIENT_DIR)
print("summary:", PATCH_OUT / "patch_patient_summary.csv")
print("errors:", len(error_rows))


# ============================================================
# 5. position_bin count summary
# ------------------------------------------------------------
# 전체 patch를 한 번에 메모리에 올리지 않고,
# 환자별 CSV를 하나씩 읽어서 position count만 집계.
# ============================================================

position_counter = Counter()
patient_patch_counts = []

patient_csv_files = sorted(PATCH_BY_PATIENT_DIR.glob("*.csv"))

for csv_path in tqdm(
    patient_csv_files,
    desc="Summarize patch CSVs",
    total=len(patient_csv_files),
    ncols=100,
    ascii=True,
    leave=True,
    dynamic_ncols=False,
):
    df = pd.read_csv(csv_path, usecols=["patient_id", "position_bin"])

    if len(df) == 0:
        continue

    patient_id = df["patient_id"].iloc[0]
    counts = df["position_bin"].value_counts()

    for k, v in counts.items():
        position_counter[k] += int(v)

    patient_patch_counts.append({
        "patient_id": patient_id,
        "patch_count": int(len(df)),
    })

position_df = pd.DataFrame([
    {"position_bin": k, "patch_count": v}
    for k, v in sorted(position_counter.items())
])

patient_count_df = pd.DataFrame(patient_patch_counts)

position_df.to_csv(
    PATCH_OUT / "patch_position_counts.csv",
    index=False,
    encoding="utf-8-sig",
)

patient_count_df.to_csv(
    PATCH_OUT / "patch_count_by_patient.csv",
    index=False,
    encoding="utf-8-sig",
)

print("\n========== Position bin counts ==========")
display(position_df)

print("\n========== Patch count by patient summary ==========")

if len(patient_count_df) > 0:
    display(patient_count_df["patch_count"].describe())
else:
    print("patient_count_df 비어 있음")

print("\nSaved:")
print(PATCH_OUT / "patch_position_counts.csv")
print(PATCH_OUT / "patch_count_by_patient.csv")

========== PATCH CONFIG ==========
PRE_ROOT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest
PATCH_OUT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest\patch_all_v2_tslungguard_nochest_resume
PATCH_BY_PATIENT_DIR: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest\patch_all_v2_tslungguard_nochest_resume\patches_by_patient
========== PATCH EXTRACTION START ==========
patient count: 362
PATCH_OUT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest\patch_all_v2_tslungguard_nochest_resume

Patch extraction by patient:   0%|                                | 1/362 [00:19<1:56:39, 19.39s/it]

[PATCH] normal001 완료 (1/362) | patch=20948 | 이번 환자: 19초 | 전체 경과: 19초 | 예상 남은 시간: 1시간 56분 17초

Patch extraction by patient:   1%|1                               | 2/362 [00:39<1:58:10, 19.69s/it]

[PATCH] normal002 완료 (2/362) | patch=22012 | 이번 환자: 19초 | 전체 경과: 39초 | 예상 남은 시간: 1시간 57분 42초

Patch extraction by patient:   1%|2                               | 3/362 [01:04<2:12:45, 22.19s/it]

[PATCH] normal003 완료 (3/362) | patch=30825 | 이번 환자: 25초 | 전체 경과: 1분 4초 | 예상 남은 시간: 2시간 8분 21초

Patch extraction by patient:   1%|3                               | 4/362 [01:26<2:11:51, 22.10s/it]

[PATCH] normal004 완료 (4/362) | patch=27119 | 이번 환자: 21초 | 전체 경과: 1분 26초 | 예상 남은 시간: 2시간 8분 48초

Patch extraction by patient:   1%|4                               | 5/362 [01:51<2:18:16, 23.24s/it]

[PATCH] normal005 완료 (5/362) | patch=32653 | 이번 환자: 25초 | 전체 경과: 1분 51초 | 예상 남은 시간: 2시간 12분 48초

Patch extraction by patient:   2%|5                               | 6/362 [02:20<2:30:05, 25.30s/it]

[PATCH] normal006 완료 (6/362) | patch=39241 | 이번 환자: 29초 | 전체 경과: 2분 20초 | 예상 남은 시간: 2시간 19분 18초

Patch extraction by patient:   2%|6                               | 7/362 [02:41<2:20:29, 23.74s/it]

[PATCH] normal007 완료 (7/362) | patch=23343 | 이번 환자: 20초 | 전체 경과: 2분 41초 | 예상 남은 시간: 2시간 16분 27초

Patch extraction by patient:   2%|7                               | 8/362 [03:06<2:22:53, 24.22s/it]

[PATCH] normal008 완료 (8/362) | patch=33329 | 이번 환자: 25초 | 전체 경과: 3분 6초 | 예상 남은 시간: 2시간 17분 40초

Patch extraction by patient:   2%|7                               | 9/362 [03:28<2:18:44, 23.58s/it]

[PATCH] normal009 완료 (9/362) | patch=25858 | 이번 환자: 22초 | 전체 경과: 3분 28초 | 예상 남은 시간: 2시간 16분 32초

Patch extraction by patient:   3%|8                              | 10/362 [03:56<2:25:17, 24.77s/it]

[PATCH] normal010 완료 (10/362) | patch=34867 | 이번 환자: 27초 | 전체 경과: 3분 56초 | 예상 남은 시간: 2시간 18분 36초

Patch extraction by patient:   3%|9                              | 11/362 [04:24<2:30:57, 25.81s/it]

[PATCH] normal011 완료 (11/362) | patch=36485 | 이번 환자: 28초 | 전체 경과: 4분 24초 | 예상 남은 시간: 2시간 20분 37초

Patch extraction by patient:   3%|#                              | 12/362 [04:48<2:27:42, 25.32s/it]

[PATCH] normal012 완료 (12/362) | patch=30678 | 이번 환자: 24초 | 전체 경과: 4분 48초 | 예상 남은 시간: 2시간 20분 19초

Patch extraction by patient:   4%|#1                             | 13/362 [05:07<2:15:00, 23.21s/it]

[PATCH] normal013 완료 (13/362) | patch=21424 | 이번 환자: 18초 | 전체 경과: 5분 7초 | 예상 남은 시간: 2시간 17분 22초

Patch extraction by patient:   4%|#1                             | 14/362 [05:30<2:14:36, 23.21s/it]

[PATCH] normal014 완료 (14/362) | patch=28777 | 이번 환자: 23초 | 전체 경과: 5분 30초 | 예상 남은 시간: 2시간 16분 48초

Patch extraction by patient:   4%|#2                             | 15/362 [05:49<2:07:09, 21.99s/it]

[PATCH] normal015 완료 (15/362) | patch=20598 | 이번 환자: 19초 | 전체 경과: 5분 49초 | 예상 남은 시간: 2시간 14분 42초

Patch extraction by patient:   4%|#3                             | 16/362 [06:09<2:03:39, 21.44s/it]

[PATCH] normal016 완료 (16/362) | patch=24133 | 이번 환자: 20초 | 전체 경과: 6분 9초 | 예상 남은 시간: 2시간 13분 11초

Patch extraction by patient:   5%|#4                             | 17/362 [06:34<2:09:02, 22.44s/it]

[PATCH] normal017 완료 (17/362) | patch=29881 | 이번 환자: 24초 | 전체 경과: 6분 34초 | 예상 남은 시간: 2시간 13분 22초

Patch extraction by patient:   5%|#5                             | 18/362 [07:01<2:16:35, 23.83s/it]

[PATCH] normal018 완료 (18/362) | patch=33392 | 이번 환자: 26초 | 전체 경과: 7분 1초 | 예상 남은 시간: 2시간 14분 12초

Patch extraction by patient:   5%|#6                             | 19/362 [07:27<2:20:38, 24.60s/it]

[PATCH] normal019 완료 (19/362) | patch=34172 | 이번 환자: 26초 | 전체 경과: 7분 27초 | 예상 남은 시간: 2시간 14분 43초

Patch extraction by patient:   6%|#7                             | 20/362 [07:48<2:13:53, 23.49s/it]

[PATCH] normal020 완료 (20/362) | patch=24239 | 이번 환자: 20초 | 전체 경과: 7분 48초 | 예상 남은 시간: 2시간 13분 34초

Patch extraction by patient:   6%|#7                             | 21/362 [08:14<2:16:35, 24.03s/it]

[PATCH] normal021 완료 (21/362) | patch=31543 | 이번 환자: 25초 | 전체 경과: 8분 13초 | 예상 남은 시간: 2시간 13분 41초

Patch extraction by patient:   6%|#8                             | 22/362 [08:33<2:08:48, 22.73s/it]

[PATCH] normal022 완료 (22/362) | patch=22147 | 이번 환자: 19초 | 전체 경과: 8분 33초 | 예상 남은 시간: 2시간 12분 18초

Patch extraction by patient:   6%|#9                             | 23/362 [09:05<2:23:43, 25.44s/it]

[PATCH] normal023 완료 (23/362) | patch=41977 | 이번 환자: 31초 | 전체 경과: 9분 5초 | 예상 남은 시간: 2시간 13분 58초

Patch extraction by patient:   7%|##                             | 24/362 [09:35<2:31:06, 26.82s/it]

[PATCH] normal024 완료 (24/362) | patch=37894 | 이번 환자: 29초 | 전체 경과: 9분 35초 | 예상 남은 시간: 2시간 15분 4초

Patch extraction by patient:   7%|##1                            | 25/362 [10:01<2:28:59, 26.53s/it]

[PATCH] normal025 완료 (25/362) | patch=32476 | 이번 환자: 25초 | 전체 경과: 10분 1초 | 예상 남은 시간: 2시간 15분 5초

Patch extraction by patient:   7%|##2                            | 26/362 [10:28<2:29:18, 26.66s/it]

[PATCH] normal026 완료 (26/362) | patch=32734 | 이번 환자: 26초 | 전체 경과: 10분 28초 | 예상 남은 시간: 2시간 15분 19초

Patch extraction by patient:   7%|##3                            | 27/362 [10:50<2:21:35, 25.36s/it]

[PATCH] normal027 완료 (27/362) | patch=26663 | 이번 환자: 22초 | 전체 경과: 10분 50초 | 예상 남은 시간: 2시간 14분 32초

Patch extraction by patient:   8%|##3                            | 28/362 [11:09<2:09:53, 23.33s/it]

[PATCH] normal028 완료 (28/362) | patch=20975 | 이번 환자: 18초 | 전체 경과: 11분 9초 | 예상 남은 시간: 2시간 13분 2초

Patch extraction by patient:   8%|##4                            | 29/362 [11:31<2:07:29, 22.97s/it]

[PATCH] normal029 완료 (29/362) | patch=26160 | 이번 환자: 22초 | 전체 경과: 11분 31초 | 예상 남은 시간: 2시간 12분 18초

Patch extraction by patient:   8%|##5                            | 30/362 [11:56<2:09:49, 23.46s/it]

[PATCH] normal030 완료 (30/362) | patch=30925 | 이번 환자: 24초 | 전체 경과: 11분 55초 | 예상 남은 시간: 2시간 12분 3초

Patch extraction by patient:   9%|##6                            | 31/362 [12:20<2:11:36, 23.86s/it]

[PATCH] normal031 완료 (31/362) | patch=29995 | 이번 환자: 24초 | 전체 경과: 12분 20초 | 예상 남은 시간: 2시간 11분 49초

Patch extraction by patient:   9%|##7                            | 32/362 [12:39<2:02:40, 22.30s/it]

[PATCH] normal032 완료 (32/362) | patch=23004 | 이번 환자: 18초 | 전체 경과: 12분 39초 | 예상 남은 시간: 2시간 10분 31초

Patch extraction by patient:   9%|##8                            | 33/362 [13:08<2:13:59, 24.44s/it]

[PATCH] normal033 완료 (33/362) | patch=38358 | 이번 환자: 29초 | 전체 경과: 13분 8초 | 예상 남은 시간: 2시간 11분 4초

Patch extraction by patient:   9%|##9                            | 34/362 [13:29<2:08:04, 23.43s/it]

[PATCH] normal034 완료 (34/362) | patch=23824 | 이번 환자: 20초 | 전체 경과: 13분 29초 | 예상 남은 시간: 2시간 10분 13초

Patch extraction by patient:  10%|##9                            | 35/362 [13:57<2:14:15, 24.63s/it]

[PATCH] normal035 완료 (35/362) | patch=35652 | 이번 환자: 27초 | 전체 경과: 13분 57초 | 예상 남은 시간: 2시간 10분 23초

Patch extraction by patient:  10%|###                            | 36/362 [14:24<2:18:22, 25.47s/it]

[PATCH] normal036 완료 (36/362) | patch=34569 | 이번 환자: 27초 | 전체 경과: 14분 24초 | 예상 남은 시간: 2시간 10분 30초

Patch extraction by patient:  10%|###1                           | 37/362 [14:47<2:13:14, 24.60s/it]

[PATCH] normal037 완료 (37/362) | patch=27602 | 이번 환자: 22초 | 전체 경과: 14분 47초 | 예상 남은 시간: 2시간 9분 54초

Patch extraction by patient:  10%|###2                           | 38/362 [15:25<2:34:03, 28.53s/it]

[PATCH] normal038 완료 (38/362) | patch=52080 | 이번 환자: 37초 | 전체 경과: 15분 25초 | 예상 남은 시간: 2시간 11분 26초

Patch extraction by patient:  11%|###3                           | 39/362 [15:46<2:21:31, 26.29s/it]

[PATCH] normal039 완료 (39/362) | patch=24117 | 이번 환자: 20초 | 전체 경과: 15분 46초 | 예상 남은 시간: 2시간 10분 35초

Patch extraction by patient:  11%|###4                           | 40/362 [16:11<2:18:47, 25.86s/it]

[PATCH] normal040 완료 (40/362) | patch=32221 | 이번 환자: 24초 | 전체 경과: 16분 10초 | 예상 남은 시간: 2시간 10분 16초

Patch extraction by patient:  11%|###5                           | 41/362 [16:35<2:16:51, 25.58s/it]

[PATCH] normal041 완료 (41/362) | patch=30150 | 이번 환자: 24초 | 전체 경과: 16분 35초 | 예상 남은 시간: 2시간 9분 57초

Patch extraction by patient:  12%|###5                           | 42/362 [16:56<2:09:06, 24.21s/it]

[PATCH] normal042 완료 (42/362) | patch=24745 | 이번 환자: 20초 | 전체 경과: 16분 56초 | 예상 남은 시간: 2시간 9분 7초

Patch extraction by patient:  12%|###6                           | 43/362 [17:22<2:10:27, 24.54s/it]

[PATCH] normal043 완료 (43/362) | patch=31646 | 이번 환자: 25초 | 전체 경과: 17분 22초 | 예상 남은 시간: 2시간 8분 51초

Patch extraction by patient:  12%|###7                           | 44/362 [17:50<2:16:06, 25.68s/it]

[PATCH] normal044 완료 (44/362) | patch=38253 | 이번 환자: 28초 | 전체 경과: 17분 50초 | 예상 남은 시간: 2시간 8분 57초

Patch extraction by patient:  12%|###8                           | 45/362 [18:20<2:22:14, 26.92s/it]

[PATCH] normal045 완료 (45/362) | patch=39455 | 이번 환자: 29초 | 전체 경과: 18분 20초 | 예상 남은 시간: 2시간 9분 11초

Patch extraction by patient:  13%|###9                           | 46/362 [18:39<2:08:57, 24.49s/it]

[PATCH] normal046 완료 (46/362) | patch=19874 | 이번 환자: 18초 | 전체 경과: 18분 39초 | 예상 남은 시간: 2시간 8분 8초

Patch extraction by patient:  13%|####                           | 47/362 [19:00<2:03:36, 23.54s/it]

[PATCH] normal047 완료 (47/362) | patch=27299 | 이번 환자: 21초 | 전체 경과: 19분 0초 | 예상 남은 시간: 2시간 7분 23초

Patch extraction by patient:  13%|####1                          | 48/362 [19:28<2:10:05, 24.86s/it]

[PATCH] normal048 완료 (48/362) | patch=36835 | 이번 환자: 27초 | 전체 경과: 19분 28초 | 예상 남은 시간: 2시간 7분 23초

Patch extraction by patient:  14%|####1                          | 49/362 [19:58<2:17:58, 26.45s/it]

[PATCH] normal049 완료 (49/362) | patch=40415 | 이번 환자: 30초 | 전체 경과: 19분 58초 | 예상 남은 시간: 2시간 7분 36초

Patch extraction by patient:  14%|####2                          | 50/362 [20:31<2:27:43, 28.41s/it]

[PATCH] normal050 완료 (50/362) | patch=43285 | 이번 환자: 32초 | 전체 경과: 20분 31초 | 예상 남은 시간: 2시간 8분 4초

Patch extraction by patient:  14%|####3                          | 51/362 [20:58<2:24:51, 27.95s/it]

[PATCH] normal051 완료 (51/362) | patch=34465 | 이번 환자: 26초 | 전체 경과: 20분 58초 | 예상 남은 시간: 2시간 7분 54초

Patch extraction by patient:  14%|####4                          | 52/362 [21:21<2:16:43, 26.46s/it]

[PATCH] normal052 완료 (52/362) | patch=28079 | 이번 환자: 22초 | 전체 경과: 21분 21초 | 예상 남은 시간: 2시간 7분 19초

Patch extraction by patient:  15%|####5                          | 53/362 [21:44<2:10:16, 25.30s/it]

[PATCH] normal053 완료 (53/362) | patch=26605 | 이번 환자: 22초 | 전체 경과: 21분 44초 | 예상 남은 시간: 2시간 6분 42초

Patch extraction by patient:  15%|####6                          | 54/362 [22:12<2:14:02, 26.11s/it]

[PATCH] normal054 완료 (54/362) | patch=37483 | 이번 환자: 27초 | 전체 경과: 22분 12초 | 예상 남은 시간: 2시간 6분 37초

Patch extraction by patient:  15%|####7                          | 55/362 [22:38<2:14:38, 26.31s/it]

[PATCH] normal055 완료 (55/362) | patch=34903 | 이번 환자: 26초 | 전체 경과: 22분 38초 | 예상 남은 시간: 2시간 6분 24초

Patch extraction by patient:  15%|####7                          | 56/362 [23:04<2:13:38, 26.20s/it]

[PATCH] normal056 완료 (56/362) | patch=33034 | 이번 환자: 25초 | 전체 경과: 23분 4초 | 예상 남은 시간: 2시간 6분 6초

Patch extraction by patient:  16%|####8                          | 57/362 [23:27<2:08:19, 25.24s/it]

[PATCH] normal057 완료 (57/362) | patch=27838 | 이번 환자: 22초 | 전체 경과: 23분 27초 | 예상 남은 시간: 2시간 5분 32초

Patch extraction by patient:  16%|####9                          | 58/362 [23:48<2:00:23, 23.76s/it]

[PATCH] normal058 완료 (58/362) | patch=24600 | 이번 환자: 20초 | 전체 경과: 23분 48초 | 예상 남은 시간: 2시간 4분 45초

Patch extraction by patient:  16%|#####                          | 59/362 [24:21<2:14:31, 26.64s/it]

[PATCH] normal059 완료 (59/362) | patch=44421 | 이번 환자: 33초 | 전체 경과: 24분 21초 | 예상 남은 시간: 2시간 5분 5초

Patch extraction by patient:  17%|#####1                         | 60/362 [24:53<2:21:53, 28.19s/it]

[PATCH] normal060 완료 (60/362) | patch=42949 | 이번 환자: 31초 | 전체 경과: 24분 53초 | 예상 남은 시간: 2시간 5분 15초

Patch extraction by patient:  17%|#####2                         | 61/362 [25:15<2:11:40, 26.25s/it]

[PATCH] normal061 완료 (61/362) | patch=28589 | 이번 환자: 21초 | 전체 경과: 25분 14초 | 예상 남은 시간: 2시간 4분 35초

Patch extraction by patient:  17%|#####3                         | 62/362 [25:35<2:03:05, 24.62s/it]

[PATCH] normal062 완료 (62/362) | patch=26013 | 이번 환자: 20초 | 전체 경과: 25분 35초 | 예상 남은 시간: 2시간 3분 51초

Patch extraction by patient:  17%|#####3                         | 63/362 [25:56<1:56:08, 23.31s/it]

[PATCH] normal063 완료 (63/362) | patch=26090 | 이번 환자: 20초 | 전체 경과: 25분 56초 | 예상 남은 시간: 2시간 3분 4초

Patch extraction by patient:  18%|#####4                         | 64/362 [26:16<1:51:35, 22.47s/it]

[PATCH] normal064 완료 (64/362) | patch=23826 | 이번 환자: 20초 | 전체 경과: 26분 16초 | 예상 남은 시간: 2시간 2분 20초

Patch extraction by patient:  18%|#####5                         | 65/362 [26:45<2:00:55, 24.43s/it]

[PATCH] normal065 완료 (65/362) | patch=36114 | 이번 환자: 28초 | 전체 경과: 26분 45초 | 예상 남은 시간: 2시간 2분 16초

Patch extraction by patient:  18%|#####6                         | 66/362 [27:10<2:00:54, 24.51s/it]

[PATCH] normal066 완료 (66/362) | patch=28836 | 이번 환자: 24초 | 전체 경과: 27분 10초 | 예상 남은 시간: 2시간 1분 51초

Patch extraction by patient:  19%|#####7                         | 67/362 [27:34<1:59:37, 24.33s/it]

[PATCH] normal067 완료 (67/362) | patch=27944 | 이번 환자: 23초 | 전체 경과: 27분 34초 | 예상 남은 시간: 2시간 1분 23초

Patch extraction by patient:  19%|#####8                         | 68/362 [27:58<1:59:07, 24.31s/it]

[PATCH] normal068 완료 (68/362) | patch=30335 | 이번 환자: 24초 | 전체 경과: 27분 58초 | 예상 남은 시간: 2시간 0분 56초

Patch extraction by patient:  19%|#####9                         | 69/362 [28:30<2:10:27, 26.72s/it]

[PATCH] normal069 완료 (69/362) | patch=44501 | 이번 환자: 32초 | 전체 경과: 28분 30초 | 예상 남은 시간: 2시간 1분 4초

Patch extraction by patient:  19%|#####9                         | 70/362 [28:58<2:11:16, 26.97s/it]

[PATCH] normal070 완료 (70/362) | patch=34226 | 이번 환자: 27초 | 전체 경과: 28분 58초 | 예상 남은 시간: 2시간 0분 51초

Patch extraction by patient:  20%|######                         | 71/362 [29:24<2:10:16, 26.86s/it]

[PATCH] normal071 완료 (71/362) | patch=34989 | 이번 환자: 26초 | 전체 경과: 29분 24초 | 예상 남은 시간: 2시간 0분 33초

Patch extraction by patient:  20%|######1                        | 72/362 [29:47<2:03:24, 25.53s/it]

[PATCH] normal073 완료 (72/362) | patch=27611 | 이번 환자: 22초 | 전체 경과: 29분 47초 | 예상 남은 시간: 1시간 59분 59초

Patch extraction by patient:  20%|######2                        | 73/362 [30:10<1:58:45, 24.66s/it]

[PATCH] normal074 완료 (73/362) | patch=27632 | 이번 환자: 22초 | 전체 경과: 30분 9초 | 예상 남은 시간: 1시간 59분 25초

Patch extraction by patient:  20%|######3                        | 74/362 [30:37<2:01:42, 25.36s/it]

[PATCH] normal075 완료 (74/362) | patch=34442 | 이번 환자: 26초 | 전체 경과: 30분 36초 | 예상 남은 시간: 1시간 59분 9초

Patch extraction by patient:  21%|######4                        | 75/362 [31:04<2:04:05, 25.94s/it]

[PATCH] normal076 완료 (75/362) | patch=34170 | 이번 환자: 27초 | 전체 경과: 31분 4초 | 예상 남은 시간: 1시간 58분 53초

Patch extraction by patient:  21%|######5                        | 76/362 [31:31<2:04:51, 26.19s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.105756658031515062000744821260 완료 (76/362) | patch=33299 | 이번 환자: 26초 | 전체 경과: 31분 31초 | 예상 남은 시간: 1시간 58분 36초

Patch extraction by patient:  21%|######5                        | 77/362 [32:00<2:08:26, 27.04s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.122763913896761494371822656720 완료 (77/362) | patch=37363 | 이번 환자: 28초 | 전체 경과: 32분 0초 | 예상 남은 시간: 1시간 58분 26초

Patch extraction by patient:  22%|######6                        | 78/362 [32:33<2:16:26, 28.83s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.126121460017257137098781143514 완료 (78/362) | patch=45521 | 이번 환자: 32초 | 전체 경과: 32분 33초 | 예상 남은 시간: 1시간 58분 30초

Patch extraction by patient:  22%|######7                        | 79/362 [32:55<2:07:33, 27.04s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.139713436241461669335487719526 완료 (79/362) | patch=28537 | 이번 환자: 22초 | 전체 경과: 32분 55초 | 예상 남은 시간: 1시간 57분 58초

Patch extraction by patient:  22%|######8                        | 80/362 [33:20<2:03:11, 26.21s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.144438612068946916340281098509 완료 (80/362) | patch=31543 | 이번 환자: 24초 | 전체 경과: 33분 20초 | 예상 남은 시간: 1시간 57분 30초

Patch extraction by patient:  22%|######9                        | 81/362 [33:57<2:18:39, 29.61s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.146429221666426688999739595820 완료 (81/362) | patch=51215 | 이번 환자: 37초 | 전체 경과: 33분 57초 | 예상 남은 시간: 1시간 57분 49초

Patch extraction by patient:  23%|#######                        | 82/362 [34:26<2:17:14, 29.41s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.194465340552956447447896167830 완료 (82/362) | patch=38146 | 이번 환자: 28초 | 전체 경과: 34분 26초 | 예상 남은 시간: 1시간 57분 36초

Patch extraction by patient:  23%|#######1                       | 83/362 [34:58<2:19:55, 30.09s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.210837812047373739447725050963 완료 (83/362) | patch=43348 | 이번 환자: 31초 | 전체 경과: 34분 58초 | 예상 남은 시간: 1시간 57분 33초

Patch extraction by patient:  23%|#######1                       | 84/362 [35:19<2:06:49, 27.37s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.231645134739451754302647733304 완료 (84/362) | patch=25515 | 이번 환자: 20초 | 전체 경과: 35분 19초 | 예상 남은 시간: 1시간 56분 54초

Patch extraction by patient:  23%|#######2                       | 85/362 [35:46<2:05:39, 27.22s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.238522526736091851696274044574 완료 (85/362) | patch=33227 | 이번 환자: 26초 | 전체 경과: 35분 46초 | 예상 남은 시간: 1시간 56분 34초

Patch extraction by patient:  24%|#######3                       | 86/362 [36:05<1:54:07, 24.81s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.250438451287314206124484591986 완료 (86/362) | patch=22590 | 이번 환자: 19초 | 전체 경과: 36분 5초 | 예상 남은 시간: 1시간 55분 49초

Patch extraction by patient:  24%|#######4                       | 87/362 [36:32<1:56:40, 25.46s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.269689294231892620436462818860 완료 (87/362) | patch=34818 | 이번 환자: 26초 | 전체 경과: 36분 32초 | 예상 남은 시간: 1시간 55분 29초

Patch extraction by patient:  24%|#######5                       | 88/362 [36:50<1:46:21, 23.29s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.278660284797073139172446973682 완료 (88/362) | patch=20207 | 이번 환자: 18초 | 전체 경과: 36분 50초 | 예상 남은 시간: 1시간 54분 43초

Patch extraction by patient:  25%|#######6                       | 89/362 [37:20<1:54:17, 25.12s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.280972147860943609388015648430 완료 (89/362) | patch=39017 | 이번 환자: 29초 | 전체 경과: 37분 19초 | 예상 남은 시간: 1시간 54분 31초

Patch extraction by patient:  25%|#######7                       | 90/362 [37:41<1:48:33, 23.95s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.302134342469412607966016057827 완료 (90/362) | patch=26516 | 이번 환자: 21초 | 전체 경과: 37분 41초 | 예상 남은 시간: 1시간 53분 53초

Patch extraction by patient:  25%|#######7                       | 91/362 [38:10<1:55:43, 25.62s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.310626494937915759224334597176 완료 (91/362) | patch=38364 | 이번 환자: 29초 | 전체 경과: 38분 10초 | 예상 남은 시간: 1시간 53분 41초

Patch extraction by patient:  25%|#######8                       | 92/362 [38:30<1:47:27, 23.88s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.311981398931043315779172047718 완료 (92/362) | patch=20835 | 이번 환자: 19초 | 전체 경과: 38분 30초 | 예상 남은 시간: 1시간 53분 1초

Patch extraction by patient:  26%|#######9                       | 93/362 [39:11<2:10:13, 29.05s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.332453873575389860371315979768 완료 (93/362) | patch=58698 | 이번 환자: 40초 | 전체 경과: 39분 11초 | 예상 남은 시간: 1시간 53분 22초

Patch extraction by patient:  26%|########                       | 94/362 [39:29<1:54:14, 25.57s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.397062004302272014259317520874 완료 (94/362) | patch=17441 | 이번 환자: 17초 | 전체 경과: 39분 29초 | 예상 남은 시간: 1시간 52분 34초

Patch extraction by patient:  26%|########1                      | 95/362 [39:41<1:35:47, 21.52s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.564534197011295112247542153557 완료 (95/362) | patch=8730 | 이번 환자: 12초 | 전체 경과: 39분 41초 | 예상 남은 시간: 1시간 51분 32초

Patch extraction by patient:  27%|########2                      | 96/362 [40:01<1:33:42, 21.14s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.657775098760536289051744981056 완료 (96/362) | patch=23554 | 이번 환자: 20초 | 전체 경과: 40분 1초 | 예상 남은 시간: 1시간 50분 54초

Patch extraction by patient:  27%|########3                      | 97/362 [40:26<1:38:50, 22.38s/it]

[PATCH] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.975254950136384517744116790879 완료 (97/362) | patch=32514 | 이번 환자: 25초 | 전체 경과: 40분 26초 | 예상 남은 시간: 1시간 50분 29초

Patch extraction by patient:  27%|########3                      | 98/362 [41:06<2:01:44, 27.67s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.100684836163890911914061745866 완료 (98/362) | patch=58144 | 이번 환자: 39초 | 전체 경과: 41분 6초 | 예상 남은 시간: 1시간 50분 45초

Patch extraction by patient:  27%|########4                      | 99/362 [41:19<1:42:06, 23.30s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.111017101339429664883879536171 완료 (99/362) | patch=12237 | 이번 환자: 13초 | 전체 경과: 41분 19초 | 예상 남은 시간: 1시간 49분 47초

Patch extraction by patient:  28%|########2                     | 100/362 [41:37<1:33:50, 21.49s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.113697708991260454310623082679 완료 (100/362) | patch=19536 | 이번 환자: 17초 | 전체 경과: 41분 37초 | 예상 남은 시간: 1시간 49분 2초

Patch extraction by patient:  28%|########3                     | 101/362 [42:06<1:43:20, 23.76s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.139595277234735528205899724196 완료 (101/362) | patch=40347 | 이번 환자: 28초 | 전체 경과: 42분 6초 | 예상 남은 시간: 1시간 48분 48초

Patch extraction by patient:  28%|########4                     | 102/362 [42:21<1:32:01, 21.24s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.140527383975300992150799777603 완료 (102/362) | patch=16750 | 이번 환자: 15초 | 전체 경과: 42분 21초 | 예상 남은 시간: 1시간 47분 58초

Patch extraction by patient:  28%|########5                     | 103/362 [42:44<1:33:48, 21.73s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.144943344795414353192059796098 완료 (103/362) | patch=29652 | 이번 환자: 22초 | 전체 경과: 42분 44초 | 예상 남은 시간: 1시간 47분 28초

Patch extraction by patient:  29%|########6                     | 104/362 [43:13<1:42:14, 23.78s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.146603910507557786636779705509 완료 (104/362) | patch=37255 | 이번 환자: 28초 | 전체 경과: 43분 12초 | 예상 남은 시간: 1시간 47분 12초

Patch extraction by patient:  29%|########7                     | 105/362 [43:52<2:01:37, 28.39s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.152684536713461901635595118048 완료 (105/362) | patch=54976 | 이번 환자: 39초 | 전체 경과: 43분 52초 | 예상 남은 시간: 1시간 47분 22초

Patch extraction by patient:  29%|########7                     | 106/362 [44:10<1:48:44, 25.49s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.161002239822118346732951898613 완료 (106/362) | patch=19194 | 이번 환자: 18초 | 전체 경과: 44분 10초 | 예상 남은 시간: 1시간 46분 42초

Patch extraction by patient:  30%|########8                     | 107/362 [44:32<1:44:00, 24.47s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.161073793312426102774780216551 완료 (107/362) | patch=25978 | 이번 환자: 22초 | 전체 경과: 44분 32초 | 예상 남은 시간: 1시간 46분 10초

Patch extraction by patient:  30%|########9                     | 108/362 [45:05<1:54:07, 26.96s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.162207236104936931957809623059 완료 (108/362) | patch=44929 | 이번 환자: 32초 | 전체 경과: 45분 5초 | 예상 남은 시간: 1시간 46분 3초

Patch extraction by patient:  30%|#########                     | 109/362 [45:36<1:58:42, 28.15s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.171919524048654494439256263785 완료 (109/362) | patch=42244 | 이번 환자: 30초 | 전체 경과: 45분 36초 | 예상 남은 시간: 1시간 45분 51초

Patch extraction by patient:  30%|#########1                    | 110/362 [46:03<1:57:00, 27.86s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.184019785706727365023450012318 완료 (110/362) | patch=36381 | 이번 환자: 27초 | 전체 경과: 46분 3초 | 예상 남은 시간: 1시간 45분 31초

Patch extraction by patient:  31%|#########1                    | 111/362 [46:38<2:04:25, 29.74s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.186021279664749879526003668137 완료 (111/362) | patch=44675 | 이번 환자: 34초 | 전체 경과: 46분 37초 | 예상 남은 시간: 1시간 45분 26초

Patch extraction by patient:  31%|#########2                    | 112/362 [47:05<2:00:49, 29.00s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.193408384740507320589857096592 완료 (112/362) | patch=36620 | 이번 환자: 27초 | 전체 경과: 47분 5초 | 예상 남은 시간: 1시간 45분 6초

Patch extraction by patient:  31%|#########3                    | 113/362 [47:31<1:56:53, 28.17s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.197987940182806628828566429132 완료 (113/362) | patch=29595 | 이번 환자: 26초 | 전체 경과: 47분 31초 | 예상 남은 시간: 1시간 44분 43초

Patch extraction by patient:  31%|#########4                    | 114/362 [47:57<1:53:28, 27.45s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.200558451375970945040979397866 완료 (114/362) | patch=31636 | 이번 환자: 25초 | 전체 경과: 47분 57초 | 예상 남은 시간: 1시간 44분 19초

Patch extraction by patient:  32%|#########5                    | 115/362 [48:28<1:57:37, 28.57s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.216652640878960522552873394709 완료 (115/362) | patch=42122 | 이번 환자: 31초 | 전체 경과: 48분 28초 | 예상 남은 시간: 1시간 44분 6초

Patch extraction by patient:  32%|#########6                    | 116/362 [48:55<1:55:28, 28.16s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.222087811960706096424718056430 완료 (116/362) | patch=33302 | 이번 환자: 27초 | 전체 경과: 48분 55초 | 예상 남은 시간: 1시간 43분 45초

Patch extraction by patient:  32%|#########6                    | 117/362 [49:29<2:02:32, 30.01s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.231834776365874788440767645596 완료 (117/362) | patch=44522 | 이번 환자: 34초 | 전체 경과: 49분 29초 | 예상 남은 시간: 1시간 43분 39초

Patch extraction by patient:  33%|#########7                    | 118/362 [49:55<1:56:03, 28.54s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.259018373683540453277752706262 완료 (118/362) | patch=31635 | 이번 환자: 25초 | 전체 경과: 49분 55초 | 예상 남은 시간: 1시간 43분 13초

Patch extraction by patient:  33%|#########8                    | 119/362 [50:30<2:03:26, 30.48s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.286647622786041008124419915089 완료 (119/362) | patch=44845 | 이번 환자: 34초 | 전체 경과: 50분 30초 | 예상 남은 시간: 1시간 43분 7초

Patch extraction by patient:  33%|#########9                    | 120/362 [51:00<2:02:20, 30.33s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.300271604576987336866436407488 완료 (120/362) | patch=40075 | 이번 환자: 29초 | 전체 경과: 51분 0초 | 예상 남은 시간: 1시간 42분 51초

Patch extraction by patient:  33%|##########                    | 121/362 [51:26<1:56:31, 29.01s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.308183340111270052562662456038 완료 (121/362) | patch=31709 | 이번 환자: 25초 | 전체 경과: 51분 25초 | 예상 남은 시간: 1시간 42분 26초

Patch extraction by patient:  34%|##########1                   | 122/362 [51:53<1:54:00, 28.50s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.331211682377519763144559212009 완료 (122/362) | patch=35523 | 이번 환자: 27초 | 전체 경과: 51분 53초 | 예상 남은 시간: 1시간 42분 4초

Patch extraction by patient:  34%|##########1                   | 123/362 [52:14<1:44:33, 26.25s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.335866409407244673864352309754 완료 (123/362) | patch=24458 | 이번 환자: 20초 | 전체 경과: 52분 14초 | 예상 남은 시간: 1시간 41분 30초

Patch extraction by patient:  34%|##########2                   | 124/362 [52:37<1:40:46, 25.41s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.802595762867498341201607992711 완료 (124/362) | patch=28144 | 이번 환자: 23초 | 전체 경과: 52분 37초 | 예상 남은 시간: 1시간 41분 0초

Patch extraction by patient:  35%|##########3                   | 125/362 [53:03<1:40:15, 25.38s/it]

[PATCH] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.888291896309937415860209787179 완료 (125/362) | patch=32427 | 이번 환자: 25초 | 전체 경과: 53분 3초 | 예상 남은 시간: 1시간 40분 35초

Patch extraction by patient:  35%|##########4                   | 126/362 [53:25<1:36:33, 24.55s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.102133688497886810253331438797 완료 (126/362) | patch=29156 | 이번 환자: 22초 | 전체 경과: 53분 25초 | 예상 남은 시간: 1시간 40분 4초

Patch extraction by patient:  35%|##########5                   | 127/362 [53:46<1:31:28, 23.35s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.113586291551175790743673929831 완료 (127/362) | patch=26172 | 이번 환자: 20초 | 전체 경과: 53분 46초 | 예상 남은 시간: 1시간 39분 29초

Patch extraction by patient:  35%|##########6                   | 128/362 [54:23<1:47:23, 27.54s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.116492508532884962903000261147 완료 (128/362) | patch=53049 | 이번 환자: 37초 | 전체 경과: 54분 23초 | 예상 남은 시간: 1시간 39분 26초

Patch extraction by patient:  36%|##########6                   | 129/362 [54:41<1:35:48, 24.67s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.117383608379722740629083782428 완료 (129/362) | patch=19926 | 이번 환자: 17초 | 전체 경과: 54분 41초 | 예상 남은 시간: 1시간 38분 47초

Patch extraction by patient:  36%|##########7                   | 130/362 [55:13<1:43:40, 26.81s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.139444426690868429919252698606 완료 (130/362) | patch=44459 | 이번 환자: 31초 | 전체 경과: 55분 13초 | 예상 남은 시간: 1시간 38분 32초

Patch extraction by patient:  36%|##########8                   | 131/362 [55:39<1:42:05, 26.52s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.156322145453198768801776721493 완료 (131/362) | patch=34459 | 이번 환자: 25초 | 전체 경과: 55분 39초 | 예상 남은 시간: 1시간 38분 8초

Patch extraction by patient:  36%|##########9                   | 132/362 [56:06<1:42:48, 26.82s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.156579001330474859527530187095 완료 (132/362) | patch=36781 | 이번 환자: 27초 | 전체 경과: 56분 6초 | 예상 남은 시간: 1시간 37분 46초

Patch extraction by patient:  37%|###########                   | 133/362 [56:36<1:46:17, 27.85s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.159521777966998275980367008904 완료 (133/362) | patch=41675 | 이번 환자: 30초 | 전체 경과: 56분 36초 | 예상 남은 시간: 1시간 37분 28초

Patch extraction by patient:  37%|###########1                  | 134/362 [56:57<1:37:28, 25.65s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.172845185165807139298420209778 완료 (134/362) | patch=23156 | 이번 환자: 20초 | 전체 경과: 56분 57초 | 예상 남은 시간: 1시간 36분 54초

Patch extraction by patient:  37%|###########1                  | 135/362 [57:16<1:29:33, 23.67s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.176362912420491262783064585333 완료 (135/362) | patch=22046 | 이번 환자: 18초 | 전체 경과: 57분 16초 | 예상 남은 시간: 1시간 36분 18초

Patch extraction by patient:  38%|###########2                  | 136/362 [57:46<1:36:32, 25.63s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.191301539558980174217770205256 완료 (136/362) | patch=40194 | 이번 환자: 30초 | 전체 경과: 57분 46초 | 예상 남은 시간: 1시간 36분 0초

Patch extraction by patient:  38%|###########3                  | 137/362 [58:15<1:39:07, 26.43s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.213022585153512920098588556742 완료 (137/362) | patch=37799 | 이번 환자: 28초 | 전체 경과: 58분 14초 | 예상 남은 시간: 1시간 35분 39초

Patch extraction by patient:  38%|###########4                  | 138/362 [58:31<1:27:15, 23.37s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.216526102138308489357443843021 완료 (138/362) | patch=18653 | 이번 환자: 16초 | 전체 경과: 58분 31초 | 예상 남은 시간: 1시간 34분 59초

Patch extraction by patient:  38%|###########5                  | 139/362 [58:53<1:25:49, 23.09s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.220205300714852483483213840572 완료 (139/362) | patch=27045 | 이번 환자: 22초 | 전체 경과: 58분 53초 | 예상 남은 시간: 1시간 34분 29초

Patch extraction by patient:  39%|###########6                  | 140/362 [59:31<1:41:42, 27.49s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.221945191226273284587353530424 완료 (140/362) | patch=53582 | 이번 환자: 37초 | 전체 경과: 59분 31초 | 예상 남은 시간: 1시간 34분 23초

Patch extraction by patient:  39%|###########6                  | 141/362 [59:54<1:35:48, 26.01s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.223098610241551815995595311693 완료 (141/362) | patch=28111 | 이번 환자: 22초 | 전체 경과: 59분 53초 | 예상 남은 시간: 1시간 33분 53초

Patch extraction by patient:  39%|##########9                 | 142/362 [1:00:28<1:44:11, 28.41s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.230078008964732806419498631442 완료 (142/362) | patch=48442 | 이번 환자: 33초 | 전체 경과: 1시간 0분 27초 | 예상 남은 시간: 1시간 33분 40초

Patch extraction by patient:  40%|###########                 | 143/362 [1:00:54<1:41:45, 27.88s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.253283426904813468115158375647 완료 (143/362) | patch=34257 | 이번 환자: 26초 | 전체 경과: 1시간 0분 54초 | 예상 남은 시간: 1시간 33분 16초

Patch extraction by patient:  40%|###########1                | 144/362 [1:01:16<1:34:34, 26.03s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.265133389948279331857097127422 완료 (144/362) | patch=27843 | 이번 환자: 21초 | 전체 경과: 1시간 1분 16초 | 예상 남은 시간: 1시간 32분 45초

Patch extraction by patient:  40%|###########2                | 145/362 [1:01:36<1:28:03, 24.35s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.272259794130271010519952623746 완료 (145/362) | patch=22907 | 이번 환자: 20초 | 전체 경과: 1시간 1분 36초 | 예상 남은 시간: 1시간 32분 12초

Patch extraction by patient:  40%|###########2                | 146/362 [1:02:00<1:27:06, 24.20s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.281967919138248195763602360723 완료 (146/362) | patch=30210 | 이번 환자: 23초 | 전체 경과: 1시간 2분 0초 | 예상 남은 시간: 1시간 31분 44초

Patch extraction by patient:  41%|###########3                | 147/362 [1:02:26<1:28:26, 24.68s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.296863826932699509516219450076 완료 (147/362) | patch=32809 | 이번 환자: 25초 | 전체 경과: 1시간 2분 26초 | 예상 남은 시간: 1시간 31분 19초

Patch extraction by patient:  41%|###########4                | 148/362 [1:02:51<1:28:10, 24.72s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.306788423710427765311352901943 완료 (148/362) | patch=32604 | 이번 환자: 24초 | 전체 경과: 1시간 2분 51초 | 예상 남은 시간: 1시간 30분 52초

Patch extraction by patient:  41%|###########5                | 149/362 [1:03:27<1:40:01, 28.18s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.311236942972970815890902714604 완료 (149/362) | patch=51859 | 이번 환자: 36초 | 전체 경과: 1시간 3분 27초 | 예상 남은 시간: 1시간 30분 42초

Patch extraction by patient:  41%|###########6                | 150/362 [1:03:50<1:33:58, 26.60s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.325580698241281352835338693869 완료 (150/362) | patch=28349 | 이번 환자: 22초 | 전체 경과: 1시간 3분 50초 | 예상 남은 시간: 1시간 30분 13초

Patch extraction by patient:  42%|###########6                | 151/362 [1:04:03<1:19:31, 22.62s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.470912100568074901744259213968 완료 (151/362) | patch=12549 | 이번 환자: 13초 | 전체 경과: 1시간 4분 3초 | 예상 남은 시간: 1시간 29분 31초

Patch extraction by patient:  42%|###########7                | 152/362 [1:04:25<1:18:16, 22.36s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.504324996863016748259361352296 완료 (152/362) | patch=29706 | 이번 환자: 21초 | 전체 경과: 1시간 4분 25초 | 예상 남은 시간: 1시간 29분 0초

Patch extraction by patient:  42%|###########8                | 153/362 [1:04:48<1:18:45, 22.61s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.669518152156802508672627785405 완료 (153/362) | patch=28155 | 이번 환자: 23초 | 전체 경과: 1시간 4분 48초 | 예상 남은 시간: 1시간 28분 31초

Patch extraction by patient:  43%|###########9                | 154/362 [1:05:05<1:12:18, 20.86s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.707218743153927597786179232739 완료 (154/362) | patch=18863 | 이번 환자: 16초 | 전체 경과: 1시간 5분 5초 | 예상 남은 시간: 1시간 27분 54초

Patch extraction by patient:  43%|###########9                | 155/362 [1:05:23<1:09:02, 20.01s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.743969234977916254223533321294 완료 (155/362) | patch=21761 | 이번 환자: 17초 | 전체 경과: 1시간 5분 23초 | 예상 남은 시간: 1시간 27분 19초

Patch extraction by patient:  43%|############                | 156/362 [1:05:52<1:18:09, 22.76s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.776429308535398795601496131524 완료 (156/362) | patch=39692 | 이번 환자: 29초 | 전체 경과: 1시간 5분 52초 | 예상 남은 시간: 1시간 26분 59초

Patch extraction by patient:  43%|############1               | 157/362 [1:06:03<1:05:21, 19.13s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.803808126682275425758092691689 완료 (157/362) | patch=7594 | 이번 환자: 10초 | 전체 경과: 1시간 6분 3초 | 예상 남은 시간: 1시간 26분 15초

Patch extraction by patient:  44%|############2               | 158/362 [1:06:33<1:15:53, 22.32s/it]

[PATCH] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.885292267869246639232975687131 완료 (158/362) | patch=39459 | 이번 환자: 29초 | 전체 경과: 1시간 6분 33초 | 예상 남은 시간: 1시간 25분 55초

Patch extraction by patient:  44%|############2               | 159/362 [1:06:59<1:20:04, 23.67s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.100620385482151095585000946543 완료 (159/362) | patch=34643 | 이번 환자: 26초 | 전체 경과: 1시간 6분 59초 | 예상 남은 시간: 1시간 25분 32초

Patch extraction by patient:  44%|############3               | 160/362 [1:07:27<1:23:51, 24.91s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.125356649712550043958727288500 완료 (160/362) | patch=35438 | 이번 환자: 27초 | 전체 경과: 1시간 7분 27초 | 예상 남은 시간: 1시간 25분 10초

Patch extraction by patient:  44%|############4               | 161/362 [1:07:57<1:28:19, 26.36s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.145474881373882284343459153872 완료 (161/362) | patch=40924 | 이번 환자: 29초 | 전체 경과: 1시간 7분 57초 | 예상 남은 시간: 1시간 24분 50초

Patch extraction by patient:  45%|############5               | 162/362 [1:08:27<1:31:56, 27.58s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.160216916075817913953530562493 완료 (162/362) | patch=38817 | 이번 환자: 30초 | 전체 경과: 1시간 8분 27초 | 예상 남은 시간: 1시간 24분 31초

Patch extraction by patient:  45%|############6               | 163/362 [1:08:47<1:23:10, 25.08s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.177985905159808659201278495182 완료 (163/362) | patch=21857 | 이번 환자: 19초 | 전체 경과: 1시간 8분 47초 | 예상 남은 시간: 1시간 23분 58초

Patch extraction by patient:  45%|############6               | 164/362 [1:09:18<1:29:03, 26.99s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.191617711875409989053242965150 완료 (164/362) | patch=42690 | 이번 환자: 31초 | 전체 경과: 1시간 9분 18초 | 예상 남은 시간: 1시간 23분 40초

Patch extraction by patient:  46%|############7               | 165/362 [1:09:45<1:28:34, 26.98s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.199069398344356765037879821616 완료 (165/362) | patch=34960 | 이번 환자: 26초 | 전체 경과: 1시간 9분 45초 | 예상 남은 시간: 1시간 23분 17초

Patch extraction by patient:  46%|############8               | 166/362 [1:10:11<1:27:30, 26.79s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.202476538079060560282495099956 완료 (166/362) | patch=34731 | 이번 환자: 26초 | 전체 경과: 1시간 10분 11초 | 예상 남은 시간: 1시간 22분 53초

Patch extraction by patient:  46%|############9               | 167/362 [1:10:39<1:27:42, 26.99s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.203741923654363010377298352671 완료 (167/362) | patch=35411 | 이번 환자: 27초 | 전체 경과: 1시간 10분 39초 | 예상 남은 시간: 1시간 22분 30초

Patch extraction by patient:  46%|############9               | 168/362 [1:11:02<1:23:44, 25.90s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.205852555362702089950453265567 완료 (168/362) | patch=29948 | 이번 환자: 23초 | 전체 경과: 1시간 11분 2초 | 예상 남은 시간: 1시간 22분 2초

Patch extraction by patient:  47%|#############               | 169/362 [1:11:15<1:10:55, 22.05s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.210426531621179400035178209430 완료 (169/362) | patch=12114 | 이번 환자: 13초 | 전체 경과: 1시간 11분 15초 | 예상 남은 시간: 1시간 21분 22초

Patch extraction by patient:  47%|#############1              | 170/362 [1:11:55<1:27:08, 27.23s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.215086589927307766627151367533 완료 (170/362) | patch=53387 | 이번 환자: 39초 | 전체 경과: 1시간 11분 55초 | 예상 남은 시간: 1시간 21분 13초

Patch extraction by patient:  47%|#############2              | 171/362 [1:12:19<1:23:39, 26.28s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.229664630348267553620068691756 완료 (171/362) | patch=30834 | 이번 환자: 23초 | 전체 경과: 1시간 12분 19초 | 예상 남은 시간: 1시간 20분 46초

Patch extraction by patient:  48%|#############3              | 172/362 [1:12:31<1:10:18, 22.20s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.264090899378396711987322794314 완료 (172/362) | patch=12412 | 이번 환자: 12초 | 전체 경과: 1시간 12분 31초 | 예상 남은 시간: 1시간 20분 7초

Patch extraction by patient:  48%|#############3              | 173/362 [1:13:03<1:19:14, 25.16s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.268589491017129166376960414534 완료 (173/362) | patch=44144 | 이번 환자: 31초 | 전체 경과: 1시간 13분 3초 | 예상 남은 시간: 1시간 19분 49초

Patch extraction by patient:  48%|#############4              | 174/362 [1:13:18<1:08:51, 21.97s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.268838889380981659524993261082 완료 (174/362) | patch=14893 | 이번 환자: 14초 | 전체 경과: 1시간 13분 18초 | 예상 남은 시간: 1시간 19분 12초

Patch extraction by patient:  48%|#############5              | 175/362 [1:13:46<1:14:02, 23.76s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.314519596680450457855054746285 완료 (175/362) | patch=36077 | 이번 환자: 27초 | 전체 경과: 1시간 13분 46초 | 예상 남은 시간: 1시간 18분 49초

Patch extraction by patient:  49%|#############6              | 176/362 [1:14:12<1:15:31, 24.36s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.319009811633846643966578282371 완료 (176/362) | patch=31615 | 이번 환자: 25초 | 전체 경과: 1시간 14분 12초 | 예상 남은 시간: 1시간 18분 25초

Patch extraction by patient:  49%|#############6              | 177/362 [1:14:44<1:22:16, 26.68s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.334022941831199910030220864961 완료 (177/362) | patch=44028 | 이번 환자: 31초 | 전체 경과: 1시간 14분 44초 | 예상 남은 시간: 1시간 18분 6초

Patch extraction by patient:  49%|#############7              | 178/362 [1:14:59<1:11:30, 23.32s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.398955972049286139436103068984 완료 (178/362) | patch=17488 | 이번 환자: 15초 | 전체 경과: 1시간 14분 59초 | 예상 남은 시간: 1시간 17분 31초

Patch extraction by patient:  49%|#############8              | 179/362 [1:15:25<1:13:38, 24.15s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.619372068417051974713149104919 완료 (179/362) | patch=32920 | 이번 환자: 25초 | 전체 경과: 1시간 15분 25초 | 예상 남은 시간: 1시간 17분 6초

Patch extraction by patient:  50%|#############9              | 180/362 [1:15:55<1:18:26, 25.86s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.710845873679853791427022019413 완료 (180/362) | patch=39585 | 이번 환자: 29초 | 전체 경과: 1시간 15분 55초 | 예상 남은 시간: 1시간 16분 46초

Patch extraction by patient:  50%|##############              | 181/362 [1:16:19<1:16:31, 25.37s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.965620538050807352935663552285 완료 (181/362) | patch=30430 | 이번 환자: 24초 | 전체 경과: 1시간 16분 19초 | 예상 남은 시간: 1시간 16분 19초

Patch extraction by patient:  50%|##############              | 182/362 [1:16:45<1:16:09, 25.38s/it]

[PATCH] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.969607480572818589276327766720 완료 (182/362) | patch=33059 | 이번 환자: 25초 | 전체 경과: 1시간 16분 45초 | 예상 남은 시간: 1시간 15분 54초

Patch extraction by patient:  51%|##############1             | 183/362 [1:17:06<1:12:05, 24.17s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.100530488926682752765845212286 완료 (183/362) | patch=24815 | 이번 환자: 21초 | 전체 경과: 1시간 17분 6초 | 예상 남은 시간: 1시간 15분 25초

Patch extraction by patient:  51%|##############2             | 184/362 [1:17:24<1:05:43, 22.16s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.103115201714075993579787468219 완료 (184/362) | patch=15838 | 이번 환자: 17초 | 전체 경과: 1시간 17분 24초 | 예상 남은 시간: 1시간 14분 52초

Patch extraction by patient:  51%|###############3              | 185/362 [1:17:36<57:02, 19.34s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.104780906131535625872840889059 완료 (185/362) | patch=12412 | 이번 환자: 12초 | 전체 경과: 1시간 17분 36초 | 예상 남은 시간: 1시간 14분 15초

Patch extraction by patient:  51%|##############3             | 186/362 [1:18:12<1:10:49, 24.14s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.125067060506283419853742462394 완료 (186/362) | patch=49341 | 이번 환자: 35초 | 전체 경과: 1시간 18분 12초 | 예상 남은 시간: 1시간 13분 59초

Patch extraction by patient:  52%|##############4             | 187/362 [1:18:35<1:10:00, 24.01s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.145283812746259413053188838096 완료 (187/362) | patch=30691 | 이번 환자: 23초 | 전체 경과: 1시간 18분 35초 | 예상 남은 시간: 1시간 13분 33초

Patch extraction by patient:  52%|##############5             | 188/362 [1:19:07<1:16:07, 26.25s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.156821379677057223126714881626 완료 (188/362) | patch=43121 | 이번 환자: 31초 | 전체 경과: 1시간 19분 7초 | 예상 남은 시간: 1시간 13분 13초

Patch extraction by patient:  52%|##############6             | 189/362 [1:19:29<1:12:18, 25.08s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.163931625580639955914619627409 완료 (189/362) | patch=26164 | 이번 환자: 22초 | 전체 경과: 1시간 19분 29초 | 예상 남은 시간: 1시간 12분 45초

Patch extraction by patient:  52%|##############6             | 190/362 [1:19:53<1:10:25, 24.56s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.200837896655745926888305239398 완료 (190/362) | patch=27341 | 이번 환자: 23초 | 전체 경과: 1시간 19분 53초 | 예상 남은 시간: 1시간 12분 18초

Patch extraction by patient:  53%|##############7             | 191/362 [1:20:20<1:12:29, 25.43s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.203179378754043776171267611064 완료 (191/362) | patch=36767 | 이번 환자: 27초 | 전체 경과: 1시간 20분 20초 | 예상 남은 시간: 1시간 11분 55초

Patch extraction by patient:  53%|##############8             | 192/362 [1:20:36<1:03:50, 22.53s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.209269973797560820442292189762 완료 (192/362) | patch=16865 | 이번 환자: 15초 | 전체 경과: 1시간 20분 36초 | 예상 남은 시간: 1시간 11분 22초

Patch extraction by patient:  53%|##############9             | 193/362 [1:21:15<1:17:31, 27.52s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.211071908915618528829547301883 완료 (193/362) | patch=55697 | 이번 환자: 39초 | 전체 경과: 1시간 21분 15초 | 예상 남은 시간: 1시간 11분 9초

Patch extraction by patient:  54%|###############             | 194/362 [1:21:45<1:19:10, 28.28s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.232011770495640253949434620907 완료 (194/362) | patch=40034 | 이번 환자: 29초 | 전체 경과: 1시간 21분 45초 | 예상 남은 시간: 1시간 10분 47초

Patch extraction by patient:  54%|###############             | 195/362 [1:22:10<1:16:19, 27.42s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.232058316950007760548968840196 완료 (195/362) | patch=31047 | 이번 환자: 25초 | 전체 경과: 1시간 22분 10초 | 예상 남은 시간: 1시간 10분 22초

Patch extraction by patient:  54%|###############1            | 196/362 [1:22:40<1:17:50, 28.14s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.261678072503577216586082745513 완료 (196/362) | patch=40632 | 이번 환자: 29초 | 전체 경과: 1시간 22분 40초 | 예상 남은 시간: 1시간 10분 1초

Patch extraction by patient:  54%|###############2            | 197/362 [1:23:08<1:17:12, 28.08s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.303865116731361029078599241306 완료 (197/362) | patch=38043 | 이번 환자: 27초 | 전체 경과: 1시간 23분 8초 | 예상 남은 시간: 1시간 9분 38초

Patch extraction by patient:  55%|###############3            | 198/362 [1:23:33<1:14:28, 27.25s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.304676828064484590312919543151 완료 (198/362) | patch=32914 | 이번 환자: 25초 | 전체 경과: 1시간 23분 33초 | 예상 남은 시간: 1시간 9분 12초

Patch extraction by patient:  55%|###############3            | 199/362 [1:23:55<1:09:06, 25.44s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.316393351033132458296975008261 완료 (199/362) | patch=23719 | 이번 환자: 21초 | 전체 경과: 1시간 23분 55초 | 예상 남은 시간: 1시간 8분 44초

Patch extraction by patient:  55%|###############4            | 200/362 [1:24:15<1:04:35, 23.92s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.320967206808467952819309001585 완료 (200/362) | patch=25653 | 이번 환자: 20초 | 전체 경과: 1시간 24분 15초 | 예상 남은 시간: 1시간 8분 14초

Patch extraction by patient:  56%|###############5            | 201/362 [1:24:43<1:07:17, 25.08s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.329326052298830421573852261436 완료 (201/362) | patch=38529 | 이번 환자: 27초 | 전체 경과: 1시간 24분 43초 | 예상 남은 시간: 1시간 7분 51초

Patch extraction by patient:  56%|###############6            | 202/362 [1:25:03<1:03:03, 23.65s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.330425234131526435132846006585 완료 (202/362) | patch=22331 | 이번 환자: 20초 | 전체 경과: 1시간 25분 3초 | 예상 남은 시간: 1시간 7분 22초

Patch extraction by patient:  56%|###############7            | 203/362 [1:25:26<1:01:46, 23.31s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.333319057944372470283038483725 완료 (203/362) | patch=27649 | 이번 환자: 22초 | 전체 경과: 1시간 25분 26초 | 예상 남은 시간: 1시간 6분 55초

Patch extraction by patient:  56%|###############7            | 204/362 [1:25:52<1:03:58, 24.30s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.385151742584074711135621089321 완료 (204/362) | patch=35041 | 이번 환자: 26초 | 전체 경과: 1시간 25분 52초 | 예상 남은 시간: 1시간 6분 30초

Patch extraction by patient:  57%|###############8            | 205/362 [1:26:21<1:07:14, 25.70s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.390009458146468860187238398197 완료 (205/362) | patch=38736 | 이번 환자: 28초 | 전체 경과: 1시간 26분 21초 | 예상 남은 시간: 1시간 6분 8초

Patch extraction by patient:  57%|###############9            | 206/362 [1:27:07<1:22:30, 31.73s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.428038562098395445838061018440 완료 (206/362) | patch=66124 | 이번 환자: 45초 | 전체 경과: 1시간 27분 7초 | 예상 남은 시간: 1시간 5분 58초

Patch extraction by patient:  57%|################            | 207/362 [1:27:40<1:22:59, 32.13s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.449254134266555649028108149727 완료 (207/362) | patch=46764 | 이번 환자: 32초 | 전체 경과: 1시간 27분 40초 | 예상 남은 시간: 1시간 5분 39초

Patch extraction by patient:  57%|################            | 208/362 [1:28:04<1:15:50, 29.55s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.811825890493256320617655474043 완료 (208/362) | patch=28587 | 이번 환자: 23초 | 전체 경과: 1시간 28분 4초 | 예상 남은 시간: 1시간 5분 12초

Patch extraction by patient:  58%|################1           | 209/362 [1:28:28<1:11:05, 27.88s/it]

[PATCH] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.885168397833922082085837240429 완료 (209/362) | patch=29284 | 이번 환자: 23초 | 전체 경과: 1시간 28분 28초 | 예상 남은 시간: 1시간 4분 45초

Patch extraction by patient:  58%|################2           | 210/362 [1:28:46<1:03:15, 24.97s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.100332161840553388986847034053 완료 (210/362) | patch=21302 | 이번 환자: 18초 | 전체 경과: 1시간 28분 46초 | 예상 남은 시간: 1시간 4분 15초

Patch extraction by patient:  58%|#################4            | 211/362 [1:29:03<57:09, 22.71s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.101228986346984399347858840086 완료 (211/362) | patch=20160 | 이번 환자: 17초 | 전체 경과: 1시간 29분 3초 | 예상 남은 시간: 1시간 3분 44초

Patch extraction by patient:  59%|################3           | 212/362 [1:29:32<1:01:04, 24.43s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.106419850406056634877579573537 완료 (212/362) | patch=37128 | 이번 환자: 28초 | 전체 경과: 1시간 29분 32초 | 예상 남은 시간: 1시간 3분 21초

Patch extraction by patient:  59%|################4           | 213/362 [1:30:09<1:10:05, 28.22s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.111780708132595903430640048766 완료 (213/362) | patch=50353 | 이번 환자: 36초 | 전체 경과: 1시간 30분 9초 | 예상 남은 시간: 1시간 3분 3초

Patch extraction by patient:  59%|################5           | 214/362 [1:30:38<1:10:05, 28.41s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.120196332569034738680965284519 완료 (214/362) | patch=38685 | 이번 환자: 28초 | 전체 경과: 1시간 30분 38초 | 예상 남은 시간: 1시간 2분 40초

Patch extraction by patient:  59%|################6           | 215/362 [1:31:03<1:07:39, 27.61s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.133132722052053001903031735878 완료 (215/362) | patch=34569 | 이번 환자: 25초 | 전체 경과: 1시간 31분 3초 | 예상 남은 시간: 1시간 2분 15초

Patch extraction by patient:  60%|################7           | 216/362 [1:31:31<1:07:27, 27.72s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.134638281277099121660656324702 완료 (216/362) | patch=37754 | 이번 환자: 27초 | 전체 경과: 1시간 31분 31초 | 예상 남은 시간: 1시간 1분 52초

Patch extraction by patient:  60%|#################9            | 217/362 [1:31:46<57:38, 23.85s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.138894439026794145866157853158 완료 (217/362) | patch=15415 | 이번 환자: 14초 | 전체 경과: 1시간 31분 46초 | 예상 남은 시간: 1시간 1분 19초

Patch extraction by patient:  60%|##################            | 218/362 [1:32:11<58:10, 24.24s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.143410010885830403003179808334 완료 (218/362) | patch=31991 | 이번 환자: 25초 | 전체 경과: 1시간 32분 11초 | 예상 남은 시간: 1시간 0분 53초

Patch extraction by patient:  60%|##################1           | 219/362 [1:32:30<53:39, 22.51s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.143782059748737055784173697516 완료 (219/362) | patch=20661 | 이번 환자: 18초 | 전체 경과: 1시간 32분 30초 | 예상 남은 시간: 1시간 0분 24초

Patch extraction by patient:  61%|##################2           | 220/362 [1:32:58<57:11, 24.17s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.152706273988004688708784163325 완료 (220/362) | patch=35161 | 이번 환자: 27초 | 전체 경과: 1시간 32분 58초 | 예상 남은 시간: 1시간 0분 0초

Patch extraction by patient:  61%|#################           | 221/362 [1:33:37<1:07:43, 28.82s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.174935793360491516757154875981 완료 (221/362) | patch=55384 | 이번 환자: 39초 | 전체 경과: 1시간 33분 37초 | 예상 남은 시간: 59분 44초

Patch extraction by patient:  61%|#################1          | 222/362 [1:34:04<1:05:50, 28.21s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.183056151780567460322586876100 완료 (222/362) | patch=35352 | 이번 환자: 26초 | 전체 경과: 1시간 34분 4초 | 예상 남은 시간: 59분 19초

Patch extraction by patient:  62%|##################4           | 223/362 [1:34:25<59:50, 25.83s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.188484197846284733942365679565 완료 (223/362) | patch=23625 | 이번 환자: 20초 | 전체 경과: 1시간 34분 25초 | 예상 남은 시간: 58분 51초

Patch extraction by patient:  62%|##################5           | 224/362 [1:34:49<58:18, 25.35s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.190144948425835566841437565646 완료 (224/362) | patch=29789 | 이번 환자: 24초 | 전체 경과: 1시간 34분 49초 | 예상 남은 시간: 58분 24초

Patch extraction by patient:  62%|##################6           | 225/362 [1:35:12<56:07, 24.58s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.201890795870532056891161597218 완료 (225/362) | patch=28560 | 이번 환자: 22초 | 전체 경과: 1시간 35분 12초 | 예상 남은 시간: 57분 57초

Patch extraction by patient:  62%|##################7           | 226/362 [1:35:34<54:13, 23.92s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.205615524269596458818376243313 완료 (226/362) | patch=27835 | 이번 환자: 22초 | 전체 경과: 1시간 35분 34초 | 예상 남은 시간: 57분 30초

Patch extraction by patient:  63%|##################8           | 227/362 [1:36:01<56:10, 24.97s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.219281726101239572270900838145 완료 (227/362) | patch=37526 | 이번 환자: 27초 | 전체 경과: 1시간 36분 1초 | 예상 남은 시간: 57분 6초

Patch extraction by patient:  63%|##################8           | 228/362 [1:36:32<59:25, 26.61s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.229171189693734694696158152904 완료 (228/362) | patch=40879 | 이번 환자: 30초 | 전체 경과: 1시간 36분 32초 | 예상 남은 시간: 56분 44초

Patch extraction by patient:  63%|##################9           | 229/362 [1:36:45<50:14, 22.67s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.234400932423244218697302970157 완료 (229/362) | patch=11965 | 이번 환자: 13초 | 전체 경과: 1시간 36분 45초 | 예상 남은 시간: 56분 11초

Patch extraction by patient:  64%|###################           | 230/362 [1:37:00<44:27, 20.20s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.238042459915048190592571019348 완료 (230/362) | patch=12703 | 이번 환자: 14초 | 전체 경과: 1시간 37분 0초 | 예상 남은 시간: 55분 40초

Patch extraction by patient:  64%|###################1          | 231/362 [1:37:24<46:32, 21.32s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.245349763807614756148761326488 완료 (231/362) | patch=28033 | 이번 환자: 23초 | 전체 경과: 1시간 37분 24초 | 예상 남은 시간: 55분 14초

Patch extraction by patient:  64%|###################2          | 232/362 [1:37:52<50:56, 23.51s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.246589849815292078281051154201 완료 (232/362) | patch=36017 | 이번 환자: 28초 | 전체 경과: 1시간 37분 52초 | 예상 남은 시간: 54분 50초

Patch extraction by patient:  64%|###################3          | 233/362 [1:38:21<54:04, 25.15s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.285926554490515269336267972830 완료 (233/362) | patch=35084 | 이번 환자: 28초 | 전체 경과: 1시간 38분 21초 | 예상 남은 시간: 54분 27초

Patch extraction by patient:  65%|###################3          | 234/362 [1:38:50<55:40, 26.10s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.309955814083231537823157605135 완료 (234/362) | patch=35503 | 이번 환자: 28초 | 전체 경과: 1시간 38분 50초 | 예상 남은 시간: 54분 3초

Patch extraction by patient:  65%|###################4          | 235/362 [1:39:22<59:16, 28.00s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.328695385904874796172316226975 완료 (235/362) | patch=44357 | 이번 환자: 32초 | 전체 경과: 1시간 39분 22초 | 예상 남은 시간: 53분 42초

Patch extraction by patient:  65%|##################2         | 236/362 [1:39:57<1:02:53, 29.95s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.334184846571549530235084187602 완료 (236/362) | patch=42488 | 이번 환자: 34초 | 전체 경과: 1시간 39분 56초 | 예상 남은 시간: 53분 21초

Patch extraction by patient:  65%|###################6          | 237/362 [1:40:10<52:11, 25.05s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.397202838387416555106806022938 완료 (237/362) | patch=10307 | 이번 환자: 13초 | 전체 경과: 1시간 40분 10초 | 예상 남은 시간: 52분 50초

Patch extraction by patient:  66%|###################7          | 238/362 [1:40:38<53:27, 25.87s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.553241901808946577644850294647 완료 (238/362) | patch=33363 | 이번 환자: 27초 | 전체 경과: 1시간 40분 38초 | 예상 남은 시간: 52분 26초

Patch extraction by patient:  66%|###################8          | 239/362 [1:41:07<55:06, 26.88s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.596908385953413160131451426904 완료 (239/362) | patch=35699 | 이번 환자: 29초 | 전체 경과: 1시간 41분 7초 | 예상 남은 시간: 52분 2초

Patch extraction by patient:  66%|##################5         | 240/362 [1:41:43<1:00:15, 29.64s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.745109871503276594185453478952 완료 (240/362) | patch=47187 | 이번 환자: 35초 | 전체 경과: 1시간 41분 43초 | 예상 남은 시간: 51분 42초

Patch extraction by patient:  67%|###################9          | 241/362 [1:42:00<52:07, 25.84s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.842980983137518332429408284002 완료 (241/362) | patch=17183 | 이번 환자: 16초 | 전체 경과: 1시간 42분 0초 | 예상 남은 시간: 51분 13초

Patch extraction by patient:  67%|####################          | 242/362 [1:42:27<52:28, 26.24s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.910757789941076242457816491305 완료 (242/362) | patch=33758 | 이번 환자: 27초 | 전체 경과: 1시간 42분 27초 | 예상 남은 시간: 50분 48초

Patch extraction by patient:  67%|####################1         | 243/362 [1:42:51<50:37, 25.53s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.980362852713685276785310240144 완료 (243/362) | patch=27824 | 이번 환자: 23초 | 전체 경과: 1시간 42분 51초 | 예상 남은 시간: 50분 22초

Patch extraction by patient:  67%|####################2         | 244/362 [1:43:15<49:10, 25.01s/it]

[PATCH] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.986011151772797848993829243183 완료 (244/362) | patch=28800 | 이번 환자: 23초 | 전체 경과: 1시간 43분 15초 | 예상 남은 시간: 49분 56초

Patch extraction by patient:  68%|####################3         | 245/362 [1:43:35<45:59, 23.58s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.120842785645314664964010792308 완료 (245/362) | patch=21696 | 이번 환자: 20초 | 전체 경과: 1시간 43분 35초 | 예상 남은 시간: 49분 28초

Patch extraction by patient:  68%|####################3         | 246/362 [1:44:07<50:04, 25.90s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.136830368929967292376608088362 완료 (246/362) | patch=40984 | 이번 환자: 31초 | 전체 경과: 1시간 44분 7초 | 예상 남은 시간: 49분 5초

Patch extraction by patient:  68%|####################4         | 247/362 [1:44:32<49:24, 25.78s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.164790817284381538042494285101 완료 (247/362) | patch=32327 | 이번 환자: 25초 | 전체 경과: 1시간 44분 32초 | 예상 남은 시간: 48분 40초

Patch extraction by patient:  69%|####################5         | 248/362 [1:45:01<50:48, 26.74s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.171682845383273105440297561095 완료 (248/362) | patch=38932 | 이번 환자: 28초 | 전체 경과: 1시간 45분 1초 | 예상 남은 시간: 48분 16초

Patch extraction by patient:  69%|####################6         | 249/362 [1:45:25<48:34, 25.79s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.177888806135892723698313903329 완료 (249/362) | patch=29127 | 이번 환자: 23초 | 전체 경과: 1시간 45분 25초 | 예상 남은 시간: 47분 50초

Patch extraction by patient:  69%|####################7         | 250/362 [1:46:02<54:33, 29.22s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.182798854785392200340436516930 완료 (250/362) | patch=48824 | 이번 환자: 37초 | 전체 경과: 1시간 46분 2초 | 예상 남은 시간: 47분 30초

Patch extraction by patient:  69%|####################8         | 251/362 [1:46:35<56:07, 30.34s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.190937805243443708408459490152 완료 (251/362) | patch=44570 | 이번 환자: 32초 | 전체 경과: 1시간 46분 35초 | 예상 남은 시간: 47분 8초

Patch extraction by patient:  70%|####################8         | 252/362 [1:46:55<49:59, 27.27s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.226564372605239604660221582288 완료 (252/362) | patch=22017 | 이번 환자: 20초 | 전체 경과: 1시간 46분 55초 | 예상 남은 시간: 46분 40초

Patch extraction by patient:  70%|####################9         | 253/362 [1:47:17<46:32, 25.62s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.235217371152464582553341729176 완료 (253/362) | patch=26071 | 이번 환자: 21초 | 전체 경과: 1시간 47분 17초 | 예상 남은 시간: 46분 13초

Patch extraction by patient:  70%|#####################         | 254/362 [1:47:47<48:43, 27.07s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.240630002689062442926543993263 완료 (254/362) | patch=42054 | 이번 환자: 30초 | 전체 경과: 1시간 47분 47초 | 예상 남은 시간: 45분 50초

Patch extraction by patient:  70%|#####################1        | 255/362 [1:48:15<48:33, 27.23s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.254138388912084634057282064266 완료 (255/362) | patch=35869 | 이번 환자: 27초 | 전체 경과: 1시간 48분 15초 | 예상 남은 시간: 45분 25초

Patch extraction by patient:  71%|#####################2        | 256/362 [1:48:43<48:26, 27.42s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.255409701134762680010928250229 완료 (256/362) | patch=37864 | 이번 환자: 27초 | 전체 경과: 1시간 48분 43초 | 예상 남은 시간: 45분 0초

Patch extraction by patient:  71%|#####################2        | 257/362 [1:49:07<46:29, 26.56s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.266009527139315622265711325223 완료 (257/362) | patch=30958 | 이번 환자: 24초 | 전체 경과: 1시간 49분 7초 | 예상 남은 시간: 44분 35초

Patch extraction by patient:  71%|#####################3        | 258/362 [1:49:31<44:35, 25.72s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.275849601663847251574860892603 완료 (258/362) | patch=30628 | 이번 환자: 23초 | 전체 경과: 1시간 49분 31초 | 예상 남은 시간: 44분 8초

Patch extraction by patient:  72%|#####################4        | 259/362 [1:49:47<39:01, 22.73s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.290410217650314119074833254861 완료 (259/362) | patch=13640 | 이번 환자: 15초 | 전체 경과: 1시간 49분 47초 | 예상 남은 시간: 43분 39초

Patch extraction by patient:  72%|#####################5        | 260/362 [1:50:08<37:52, 22.28s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.297251044869095073091780740645 완료 (260/362) | patch=26734 | 이번 환자: 21초 | 전체 경과: 1시간 50분 8초 | 예상 남은 시간: 43분 12초

Patch extraction by patient:  72%|#####################6        | 261/362 [1:50:37<41:01, 24.38s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.306558074682524259000586270818 완료 (261/362) | patch=40397 | 이번 환자: 29초 | 전체 경과: 1시간 50분 37초 | 예상 남은 시간: 42분 48초

Patch extraction by patient:  72%|#####################7        | 262/362 [1:50:55<37:10, 22.31s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.307921770358136677021532761235 완료 (262/362) | patch=18992 | 이번 환자: 17초 | 전체 경과: 1시간 50분 55초 | 예상 남은 시간: 42분 20초

Patch extraction by patient:  73%|#####################7        | 263/362 [1:51:21<38:34, 23.38s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.308153138776443962077214577161 완료 (263/362) | patch=33862 | 이번 환자: 25초 | 전체 경과: 1시간 51분 21초 | 예상 남은 시간: 41분 54초

Patch extraction by patient:  73%|#####################8        | 264/362 [1:51:47<39:50, 24.39s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.313756547848086902190878548835 완료 (264/362) | patch=34846 | 이번 환자: 26초 | 전체 경과: 1시간 51분 47초 | 예상 남은 시간: 41분 29초

Patch extraction by patient:  73%|#####################9        | 265/362 [1:52:07<37:14, 23.04s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.341557859428950960906150406596 완료 (265/362) | patch=22623 | 이번 환자: 19초 | 전체 경과: 1시간 52분 7초 | 예상 남은 시간: 41분 2초

Patch extraction by patient:  73%|######################        | 266/362 [1:52:34<38:32, 24.09s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.414288023902112119945238126594 완료 (266/362) | patch=32720 | 이번 환자: 26초 | 전체 경과: 1시간 52분 34초 | 예상 남은 시간: 40분 37초

Patch extraction by patient:  74%|######################1       | 267/362 [1:52:55<36:49, 23.26s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.463588161905537526756964393219 완료 (267/362) | patch=26815 | 이번 환자: 21초 | 전체 경과: 1시간 52분 55초 | 예상 남은 시간: 40분 10초

Patch extraction by patient:  74%|######################2       | 268/362 [1:53:15<34:46, 22.19s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.465032801496479029639448332481 완료 (268/362) | patch=22574 | 이번 환자: 19초 | 전체 경과: 1시간 53분 15초 | 예상 남은 시간: 39분 43초

Patch extraction by patient:  74%|######################2       | 269/362 [1:53:34<33:04, 21.34s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.475325201787910087416720919680 완료 (269/362) | patch=22835 | 이번 환자: 19초 | 전체 경과: 1시간 53분 34초 | 예상 남은 시간: 39분 15초

Patch extraction by patient:  75%|######################3       | 270/362 [1:53:57<33:23, 21.78s/it]

[PATCH] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.561423049201987049884663740668 완료 (270/362) | patch=27597 | 이번 환자: 22초 | 전체 경과: 1시간 53분 57초 | 예상 남은 시간: 38분 49초

Patch extraction by patient:  75%|######################4       | 271/362 [1:54:17<32:04, 21.15s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.116097642684124305074876564522 완료 (271/362) | patch=24390 | 이번 환자: 19초 | 전체 경과: 1시간 54분 17초 | 예상 남은 시간: 38분 22초

Patch extraction by patient:  75%|######################5       | 272/362 [1:54:50<37:25, 24.95s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.116703382344406837243058680403 완료 (272/362) | patch=48006 | 이번 환자: 33초 | 전체 경과: 1시간 54분 50초 | 예상 남은 시간: 38분 0초

Patch extraction by patient:  75%|######################6       | 273/362 [1:55:23<40:23, 27.24s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.131150737314367975651717513386 완료 (273/362) | patch=44154 | 이번 환자: 32초 | 전체 경과: 1시간 55분 23초 | 예상 남은 시간: 37분 37초

Patch extraction by patient:  76%|######################7       | 274/362 [1:55:50<39:51, 27.18s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.139889514693390832525232698200 완료 (274/362) | patch=35545 | 이번 환자: 26초 | 전체 경과: 1시간 55분 50초 | 예상 남은 시간: 37분 12초

Patch extraction by patient:  76%|######################7       | 275/362 [1:56:20<40:45, 28.11s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.143813757344903170810482790787 완료 (275/362) | patch=42905 | 이번 환자: 30초 | 전체 경과: 1시간 56분 20초 | 예상 남은 시간: 36분 48초

Patch extraction by patient:  76%|######################8       | 276/362 [1:56:55<43:14, 30.17s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.151669338315069779994664893123 완료 (276/362) | patch=47497 | 이번 환자: 34초 | 전체 경과: 1시간 56분 55초 | 예상 남은 시간: 36분 26초

Patch extraction by patient:  77%|######################9       | 277/362 [1:57:16<38:53, 27.46s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.159665703190517688573100822213 완료 (277/362) | patch=25480 | 이번 환자: 21초 | 전체 경과: 1시간 57분 16초 | 예상 남은 시간: 35분 59초

Patch extraction by patient:  77%|#######################       | 278/362 [1:57:32<33:22, 23.84s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.163217526257871051722166468085 완료 (278/362) | patch=15678 | 이번 환자: 15초 | 전체 경과: 1시간 57분 32초 | 예상 남은 시간: 35분 30초

Patch extraction by patient:  77%|#######################1      | 279/362 [1:58:08<38:15, 27.65s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.167500254299688235071950909530 완료 (279/362) | patch=49844 | 이번 환자: 36초 | 전체 경과: 1시간 58분 8초 | 예상 남은 시간: 35분 8초

Patch extraction by patient:  77%|#######################2      | 280/362 [1:58:31<35:54, 26.28s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.170825539570536865106681134236 완료 (280/362) | patch=25834 | 이번 환자: 22초 | 전체 경과: 1시간 58분 31초 | 예상 남은 시간: 34분 42초

Patch extraction by patient:  78%|#######################2      | 281/362 [1:58:45<30:21, 22.49s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.187803155574314810830688534991 완료 (281/362) | patch=13324 | 이번 환자: 13초 | 전체 경과: 1시간 58분 45초 | 예상 남은 시간: 34분 13초

Patch extraction by patient:  78%|#######################3      | 282/362 [1:59:00<27:09, 20.37s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.223650122819238796121876338881 완료 (282/362) | patch=14950 | 이번 환자: 15초 | 전체 경과: 1시간 59분 0초 | 예상 남은 시간: 33분 45초

Patch extraction by patient:  78%|#######################4      | 283/362 [1:59:20<26:28, 20.11s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.245546033414728092794968890929 완료 (283/362) | patch=21294 | 이번 환자: 19초 | 전체 경과: 1시간 59분 20초 | 예상 남은 시간: 33분 18초

Patch extraction by patient:  78%|#######################5      | 284/362 [1:59:38<25:24, 19.55s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.248360766706804179966476685510 완료 (284/362) | patch=19149 | 이번 환자: 18초 | 전체 경과: 1시간 59분 38초 | 예상 남은 시간: 32분 51초

Patch extraction by patient:  79%|#######################6      | 285/362 [2:00:01<26:08, 20.37s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.248425363469507808613979846863 완료 (285/362) | patch=27502 | 이번 환자: 22초 | 전체 경과: 2시간 0분 1초 | 예상 남은 시간: 32분 25초

Patch extraction by patient:  79%|#######################7      | 286/362 [2:00:25<27:15, 21.52s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.252709517998555732486024866345 완료 (286/362) | patch=30229 | 이번 환자: 24초 | 전체 경과: 2시간 0분 25초 | 예상 남은 시간: 31분 59초

Patch extraction by patient:  79%|#######################7      | 287/362 [2:00:53<29:24, 23.53s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.256542095129414948017808425649 완료 (287/362) | patch=37079 | 이번 환자: 28초 | 전체 경과: 2시간 0분 53초 | 예상 남은 시간: 31분 35초

Patch extraction by patient:  80%|#######################8      | 288/362 [2:01:20<30:25, 24.68s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.266581250778073944645044950856 완료 (288/362) | patch=36201 | 이번 환자: 27초 | 전체 경과: 2시간 1분 20초 | 예상 남은 시간: 31분 10초

Patch extraction by patient:  80%|#######################9      | 289/362 [2:01:52<32:45, 26.92s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.270788655216695628640355888562 완료 (289/362) | patch=44561 | 이번 환자: 32초 | 전체 경과: 2시간 1분 52초 | 예상 남은 시간: 30분 47초

Patch extraction by patient:  80%|########################      | 290/362 [2:02:23<33:41, 28.08s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.276351267409869539593937734609 완료 (290/362) | patch=41887 | 이번 환자: 30초 | 전체 경과: 2시간 2분 23초 | 예상 남은 시간: 30분 23초

Patch extraction by patient:  80%|########################1     | 291/362 [2:02:53<33:48, 28.57s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.279953669991076107785464313394 완료 (291/362) | patch=39602 | 이번 환자: 29초 | 전체 경과: 2시간 2분 53초 | 예상 남은 시간: 29분 59초

Patch extraction by patient:  81%|########################1     | 292/362 [2:03:15<31:00, 26.58s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.303066851236267189733420290986 완료 (292/362) | patch=28543 | 이번 환자: 21초 | 전체 경과: 2시간 3분 15초 | 예상 남은 시간: 29분 32초

Patch extraction by patient:  81%|########################2     | 293/362 [2:03:35<28:18, 24.62s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.306112617218006614029386065035 완료 (293/362) | patch=24589 | 이번 환자: 19초 | 전체 경과: 2시간 3분 35초 | 예상 남은 시간: 29분 6초

Patch extraction by patient:  81%|########################3     | 294/362 [2:03:58<27:25, 24.20s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.307946352302138765071461362398 완료 (294/362) | patch=27660 | 이번 환자: 23초 | 전체 경과: 2시간 3분 58초 | 예상 남은 시간: 28분 40초

Patch extraction by patient:  81%|########################4     | 295/362 [2:04:19<25:44, 23.06s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.314836406260772370397541392345 완료 (295/362) | patch=24904 | 이번 환자: 20초 | 전체 경과: 2시간 4분 19초 | 예상 남은 시간: 28분 14초

Patch extraction by patient:  82%|########################5     | 296/362 [2:04:47<27:16, 24.80s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.315918264676377418120578391325 완료 (296/362) | patch=36856 | 이번 환자: 28초 | 전체 경과: 2시간 4분 47초 | 예상 남은 시간: 27분 49초

Patch extraction by patient:  82%|########################6     | 297/362 [2:05:16<28:11, 26.03s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.336198008634390022174744544656 완료 (297/362) | patch=38548 | 이번 환자: 28초 | 전체 경과: 2시간 5분 16초 | 예상 남은 시간: 27분 25초

Patch extraction by patient:  82%|########################6     | 298/362 [2:05:51<30:37, 28.71s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.339039410276356623209709113755 완료 (298/362) | patch=47978 | 이번 환자: 34초 | 전체 경과: 2시간 5분 51초 | 예상 남은 시간: 27분 1초

Patch extraction by patient:  83%|########################7     | 299/362 [2:06:17<29:11, 27.80s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.447468612991222399440694673357 완료 (299/362) | patch=32201 | 이번 환자: 25초 | 전체 경과: 2시간 6분 17초 | 예상 남은 시간: 26분 36초

Patch extraction by patient:  83%|########################8     | 300/362 [2:06:49<29:59, 29.03s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.664409965623578819357819577077 완료 (300/362) | patch=44669 | 이번 환자: 31초 | 전체 경과: 2시간 6분 49초 | 예상 남은 시간: 26분 12초

Patch extraction by patient:  83%|########################9     | 301/362 [2:07:00<23:58, 23.58s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.664989286137882319237192185951 완료 (301/362) | patch=10482 | 이번 환자: 10초 | 전체 경과: 2시간 7분 0초 | 예상 남은 시간: 25분 44초

Patch extraction by patient:  83%|#########################     | 302/362 [2:07:27<24:43, 24.72s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.686193079844756926365065559979 완료 (302/362) | patch=36667 | 이번 환자: 27초 | 전체 경과: 2시간 7분 27초 | 예상 남은 시간: 25분 19초

Patch extraction by patient:  84%|#########################1    | 303/362 [2:07:51<24:07, 24.53s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.749871569713868632259874663577 완료 (303/362) | patch=32774 | 이번 환자: 23초 | 전체 경과: 2시간 7분 51초 | 예상 남은 시간: 24분 53초

Patch extraction by patient:  84%|#########################1    | 304/362 [2:08:15<23:36, 24.42s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.897279226481700053115245043064 완료 (304/362) | patch=28666 | 이번 환자: 24초 | 전체 경과: 2시간 8분 15초 | 예상 남은 시간: 24분 28초

Patch extraction by patient:  84%|#########################2    | 305/362 [2:08:42<23:57, 25.22s/it]

[PATCH] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.957384617596077920906744920611 완료 (305/362) | patch=34384 | 이번 환자: 26초 | 전체 경과: 2시간 8분 42초 | 예상 남은 시간: 24분 3초

Patch extraction by patient:  85%|#########################3    | 306/362 [2:09:11<24:25, 26.17s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.108193664222196923321844991231 완료 (306/362) | patch=38770 | 이번 환자: 28초 | 전체 경과: 2시간 9분 11초 | 예상 남은 시간: 23분 38초

Patch extraction by patient:  85%|#########################4    | 307/362 [2:09:40<24:48, 27.06s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.153181766344026020914478182395 완료 (307/362) | patch=37265 | 이번 환자: 29초 | 전체 경과: 2시간 9분 40초 | 예상 남은 시간: 23분 13초

Patch extraction by patient:  85%|#########################5    | 308/362 [2:10:02<23:02, 25.61s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.161633200801003804714818844696 완료 (308/362) | patch=27642 | 이번 환자: 22초 | 전체 경과: 2시간 10분 2초 | 예상 남은 시간: 22분 48초

Patch extraction by patient:  85%|#########################6    | 309/362 [2:10:35<24:32, 27.79s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.161821150841552408667852639317 완료 (309/362) | patch=43679 | 이번 환자: 32초 | 전체 경과: 2시간 10분 35초 | 예상 남은 시간: 22분 23초

Patch extraction by patient:  86%|#########################6    | 310/362 [2:11:14<26:54, 31.04s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.175318131822744218104175746898 완료 (310/362) | patch=57353 | 이번 환자: 38초 | 전체 경과: 2시간 11분 14초 | 예상 남은 시간: 22분 0초

Patch extraction by patient:  86%|#########################7    | 311/362 [2:11:32<23:02, 27.10s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.203425588524695836343069893813 완료 (311/362) | patch=19341 | 이번 환자: 17초 | 전체 경과: 2시간 11분 32초 | 예상 남은 시간: 21분 34초

Patch extraction by patient:  86%|#########################8    | 312/362 [2:11:52<20:59, 25.19s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.236698827306171960683086245994 완료 (312/362) | patch=23586 | 이번 환자: 20초 | 전체 경과: 2시간 11분 52초 | 예상 남은 시간: 21분 8초

Patch extraction by patient:  86%|#########################9    | 313/362 [2:12:18<20:41, 25.35s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.246178337114401749164850220976 완료 (313/362) | patch=33764 | 이번 환자: 25초 | 전체 경과: 2시간 12분 18초 | 예상 남은 시간: 20분 42초

Patch extraction by patient:  87%|##########################    | 314/362 [2:12:49<21:32, 26.93s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.253317247142837717905329340520 완료 (314/362) | patch=41853 | 이번 환자: 30초 | 전체 경과: 2시간 12분 49초 | 예상 남은 시간: 20분 18초

Patch extraction by patient:  87%|##########################1   | 315/362 [2:13:13<20:23, 26.04s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.283878926524838648426928238498 완료 (315/362) | patch=30449 | 이번 환자: 23초 | 전체 경과: 2시간 13분 13초 | 예상 남은 시간: 19분 52초

Patch extraction by patient:  87%|##########################1   | 316/362 [2:13:35<19:12, 25.05s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.286627485198831346082954437212 완료 (316/362) | patch=29680 | 이번 환자: 22초 | 전체 경과: 2시간 13분 35초 | 예상 남은 시간: 19분 26초

Patch extraction by patient:  88%|##########################2   | 317/362 [2:14:01<18:51, 25.14s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.292049618819567427252971059233 완료 (317/362) | patch=32500 | 이번 환자: 25초 | 전체 경과: 2시간 14분 1초 | 예상 남은 시간: 19분 1초

Patch extraction by patient:  88%|##########################3   | 318/362 [2:14:28<18:55, 25.80s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.296066944953051278419805374238 완료 (318/362) | patch=36818 | 이번 환자: 27초 | 전체 경과: 2시간 14분 28초 | 예상 남은 시간: 18분 36초

Patch extraction by patient:  88%|##########################4   | 319/362 [2:14:47<17:05, 23.85s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.306520140119968755187868602181 완료 (319/362) | patch=26046 | 이번 환자: 19초 | 전체 경과: 2시간 14분 47초 | 예상 남은 시간: 18분 10초

Patch extraction by patient:  88%|##########################5   | 320/362 [2:15:16<17:39, 25.23s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.317613170669207528926259976488 완료 (320/362) | patch=36352 | 이번 환자: 28초 | 전체 경과: 2시간 15분 16초 | 예상 남은 시간: 17분 45초

Patch extraction by patient:  89%|##########################6   | 321/362 [2:15:39<16:54, 24.73s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.324649110927013926557500550446 완료 (321/362) | patch=28044 | 이번 환자: 23초 | 전체 경과: 2시간 15분 39초 | 예상 남은 시간: 17분 19초

Patch extraction by patient:  89%|##########################6   | 322/362 [2:16:05<16:43, 25.08s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.336102335330125765000317290445 완료 (322/362) | patch=33850 | 이번 환자: 25초 | 전체 경과: 2시간 16분 5초 | 예상 남은 시간: 16분 54초

Patch extraction by patient:  89%|##########################7   | 323/362 [2:16:36<17:19, 26.67s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.339484970190920330170416228517 완료 (323/362) | patch=41082 | 이번 환자: 30초 | 전체 경과: 2시간 16분 36초 | 예상 남은 시간: 16분 29초

Patch extraction by patient:  90%|##########################8   | 324/362 [2:17:05<17:23, 27.45s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.373433682859788429397781158572 완료 (324/362) | patch=38877 | 이번 환자: 29초 | 전체 경과: 2시간 17분 5초 | 예상 남은 시간: 16분 4초

Patch extraction by patient:  90%|##########################9   | 325/362 [2:17:34<17:15, 27.99s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.608029415915051219877530734559 완료 (325/362) | patch=36750 | 이번 환자: 29초 | 전체 경과: 2시간 17분 34초 | 예상 남은 시간: 15분 39초

Patch extraction by patient:  90%|###########################   | 326/362 [2:17:53<15:07, 25.19s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.622243923620914676263059698181 완료 (326/362) | patch=19340 | 이번 환자: 18초 | 전체 경과: 2시간 17분 53초 | 예상 남은 시간: 15분 13초

Patch extraction by patient:  90%|###########################   | 327/362 [2:18:27<16:13, 27.82s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.671278273674156798801285503514 완료 (327/362) | patch=46783 | 이번 환자: 33초 | 전체 경과: 2시간 18분 27초 | 예상 남은 시간: 14분 49초

Patch extraction by patient:  91%|###########################1  | 328/362 [2:18:45<14:03, 24.81s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.701514276942509393419164159551 완료 (328/362) | patch=21116 | 이번 환자: 17초 | 전체 경과: 2시간 18분 45초 | 예상 남은 시간: 14분 22초

Patch extraction by patient:  91%|###########################2  | 329/362 [2:19:12<13:59, 25.44s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.766881513533845439335142582269 완료 (329/362) | patch=34718 | 이번 환자: 26초 | 전체 경과: 2시간 19분 11초 | 예상 남은 시간: 13분 57초

Patch extraction by patient:  91%|###########################3  | 330/362 [2:19:34<13:09, 24.69s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.814122498113547115932318256859 완료 (330/362) | patch=28904 | 이번 환자: 22초 | 전체 경과: 2시간 19분 34초 | 예상 남은 시간: 13분 32초

Patch extraction by patient:  91%|###########################4  | 331/362 [2:20:07<13:57, 27.03s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.888615810685807330497715730842 완료 (331/362) | patch=44598 | 이번 환자: 32초 | 전체 경과: 2시간 20분 7초 | 예상 남은 시간: 13분 7초

Patch extraction by patient:  92%|###########################5  | 332/362 [2:20:35<13:36, 27.22s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.897161587681142256575045076919 완료 (332/362) | patch=35024 | 이번 환자: 27초 | 전체 경과: 2시간 20분 35초 | 예상 남은 시간: 12분 42초

Patch extraction by patient:  92%|###########################5  | 333/362 [2:20:55<12:10, 25.19s/it]

[PATCH] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.939216568327879462530496768794 완료 (333/362) | patch=23064 | 이번 환자: 20초 | 전체 경과: 2시간 20분 55초 | 예상 남은 시간: 12분 16초

Patch extraction by patient:  92%|###########################6  | 334/362 [2:21:31<13:13, 28.34s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.109882169963817627559804568094 완료 (334/362) | patch=53010 | 이번 환자: 35초 | 전체 경과: 2시간 21분 31초 | 예상 남은 시간: 11분 51초

Patch extraction by patient:  93%|###########################7  | 335/362 [2:21:50<11:34, 25.71s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.121805476976020513950614465787 완료 (335/362) | patch=22028 | 이번 환자: 19초 | 전체 경과: 2시간 21분 50초 | 예상 남은 시간: 11분 25초

Patch extraction by patient:  93%|###########################8  | 336/362 [2:22:10<10:24, 24.04s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.124656777236468248920498636247 완료 (336/362) | patch=22324 | 이번 환자: 20초 | 전체 경과: 2시간 22분 10초 | 예상 남은 시간: 11분 0초

Patch extraction by patient:  93%|###########################9  | 337/362 [2:22:42<10:55, 26.22s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.129650136453746261130135157590 완료 (337/362) | patch=44335 | 이번 환자: 31초 | 전체 경과: 2시간 22분 42초 | 예상 남은 시간: 10분 35초

Patch extraction by patient:  93%|############################  | 338/362 [2:23:14<11:13, 28.05s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.138674679709964033277400089532 완료 (338/362) | patch=45094 | 이번 환자: 32초 | 전체 경과: 2시간 23분 14초 | 예상 남은 시간: 10분 10초

Patch extraction by patient:  94%|############################  | 339/362 [2:23:37<10:11, 26.59s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.139577698050713461261415990027 완료 (339/362) | patch=29668 | 이번 환자: 23초 | 전체 경과: 2시간 23분 37초 | 예상 남은 시간: 9분 44초

Patch extraction by patient:  94%|############################1 | 340/362 [2:24:09<10:21, 28.27s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.145510611155363050427743946446 완료 (340/362) | patch=42613 | 이번 환자: 32초 | 전체 경과: 2시간 24분 9초 | 예상 남은 시간: 9분 19초

Patch extraction by patient:  94%|############################2 | 341/362 [2:24:36<09:42, 27.73s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.148935306123327835217659769212 완료 (341/362) | patch=34614 | 이번 환자: 26초 | 전체 경과: 2시간 24분 36초 | 예상 남은 시간: 8분 54초

Patch extraction by patient:  94%|############################3 | 342/362 [2:24:58<08:40, 26.03s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.179683407589764683292800449011 완료 (342/362) | patch=26787 | 이번 환자: 21초 | 전체 경과: 2시간 24분 58초 | 예상 남은 시간: 8분 28초

Patch extraction by patient:  95%|############################4 | 343/362 [2:25:24<08:12, 25.91s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.193721075067404532739943086458 완료 (343/362) | patch=33793 | 이번 환자: 25초 | 전체 경과: 2시간 25분 24초 | 예상 남은 시간: 8분 3초

Patch extraction by patient:  95%|############################5 | 344/362 [2:25:47<07:32, 25.15s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.229960820686439513664996214638 완료 (344/362) | patch=29686 | 이번 환자: 23초 | 전체 경과: 2시간 25분 47초 | 예상 남은 시간: 7분 37초

Patch extraction by patient:  95%|############################5 | 345/362 [2:26:14<07:19, 25.84s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.237915456403882324748189195892 완료 (345/362) | patch=37591 | 이번 환자: 27초 | 전체 경과: 2시간 26분 14초 | 예상 남은 시간: 7분 12초

Patch extraction by patient:  96%|############################6 | 346/362 [2:26:35<06:29, 24.32s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.254929810944557499537650429296 완료 (346/362) | patch=24504 | 이번 환자: 20초 | 전체 경과: 2시간 26분 35초 | 예상 남은 시간: 6분 46초

Patch extraction by patient:  96%|############################7 | 347/362 [2:27:16<07:20, 29.34s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.259453428008507791234730686014 완료 (347/362) | patch=58165 | 이번 환자: 40초 | 전체 경과: 2시간 27분 16초 | 예상 남은 시간: 6분 21초

Patch extraction by patient:  96%|############################8 | 348/362 [2:27:40<06:26, 27.58s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.265570697208310960298668720669 완료 (348/362) | patch=29815 | 이번 환자: 23초 | 전체 경과: 2시간 27분 40초 | 예상 남은 시간: 5분 56초

Patch extraction by patient:  96%|############################9 | 349/362 [2:27:54<05:07, 23.68s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.286061375572911414226912429210 완료 (349/362) | patch=13775 | 이번 환자: 14초 | 전체 경과: 2시간 27분 54초 | 예상 남은 시간: 5분 30초

Patch extraction by patient:  97%|############################# | 350/362 [2:28:15<04:31, 22.64s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.291156498203266896953765649282 완료 (350/362) | patch=24620 | 이번 환자: 20초 | 전체 경과: 2시간 28분 14초 | 예상 남은 시간: 5분 4초

Patch extraction by patient:  97%|############################# | 351/362 [2:28:42<04:24, 24.03s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.292576688635952269497781991202 완료 (351/362) | patch=35460 | 이번 환자: 27초 | 전체 경과: 2시간 28분 42초 | 예상 남은 시간: 4분 39초

Patch extraction by patient:  97%|#############################1| 352/362 [2:29:10<04:13, 25.39s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.300392272203629213913702120739 완료 (352/362) | patch=36577 | 이번 환자: 28초 | 전체 경과: 2시간 29분 10초 | 예상 남은 시간: 4분 14초

Patch extraction by patient:  98%|#############################2| 353/362 [2:29:39<03:57, 26.42s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.300693623747082239407271583452 완료 (353/362) | patch=35368 | 이번 환자: 28초 | 전체 경과: 2시간 29분 39초 | 예상 남은 시간: 3분 48초

Patch extraction by patient:  98%|#############################3| 354/362 [2:30:02<03:23, 25.48s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.306140003699110313373771452136 완료 (354/362) | patch=29732 | 이번 환자: 23초 | 전체 경과: 2시간 30분 2초 | 예상 남은 시간: 3분 23초

Patch extraction by patient:  98%|#############################4| 355/362 [2:30:28<02:58, 25.52s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.330043769832606379655473292782 완료 (355/362) | patch=32766 | 이번 환자: 25초 | 전체 경과: 2시간 30분 28초 | 예상 남은 시간: 2분 58초

Patch extraction by patient:  98%|#############################5| 356/362 [2:30:58<02:40, 26.70s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.330643702676971528301859647742 완료 (356/362) | patch=39787 | 이번 환자: 29초 | 전체 경과: 2시간 30분 57초 | 예상 남은 시간: 2분 32초

Patch extraction by patient:  99%|#############################5| 357/362 [2:31:32<02:25, 29.14s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.334166493392278943610545989413 완료 (357/362) | patch=45359 | 이번 환자: 34초 | 전체 경과: 2시간 31분 32초 | 예상 남은 시간: 2분 7초

Patch extraction by patient:  99%|#############################6| 358/362 [2:31:50<01:43, 25.78s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.340012777775661021262977442176 완료 (358/362) | patch=20997 | 이번 환자: 17초 | 전체 경과: 2시간 31분 50초 | 예상 남은 시간: 1분 41초

Patch extraction by patient:  99%|#############################7| 359/362 [2:32:10<01:11, 23.85s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.436403998650924660479049012235 완료 (359/362) | patch=19824 | 이번 환자: 19초 | 전체 경과: 2시간 32분 10초 | 예상 남은 시간: 1분 16초

Patch extraction by patient:  99%|#############################8| 360/362 [2:32:38<00:50, 25.12s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.472487466001405705666001578363 완료 (360/362) | patch=35369 | 이번 환자: 27초 | 전체 경과: 2시간 32분 38초 | 예상 남은 시간: 50초

Patch extraction by patient: 100%|#############################9| 361/362 [2:33:01<00:24, 24.49s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.855232435861303786204450738044 완료 (361/362) | patch=29693 | 이번 환자: 22초 | 전체 경과: 2시간 33분 1초 | 예상 남은 시간: 25초

Patch extraction by patient: 100%|##############################| 362/362 [2:33:16<00:00, 25.40s/it]

[PATCH] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.927394449308471452920270961822 완료 (362/362) | patch=16200 | 이번 환자: 14초 | 전체 경과: 2시간 33분 16초 | 예상 남은 시간: 0초

========== PATCH EXTRACTION FINISHED ==========
PATCH_OUT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest\patch_all_v2_tslungguard_nochest_resume
patient csv dir: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest\patch_all_v2_tslungguard_nochest_resume\patches_by_patient
summary: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest\patch_all_v2_tslungguard_nochest_resume\patch_patient_summary.csv
errors: 0

Summarize patch CSVs: 100%|#######################################| 362/362 [01:30<00:00,  4.02it/s]

========== Position bin counts ==========

        position_bin  patch_count
0      lower_central       838632
1   lower_peripheral      2188356
2     middle_central      1721819
3  middle_peripheral      3787892
4      upper_central       995664
5   upper_peripheral      2146744

========== Patch count by patient summary ==========

count      362.000000
mean     32262.726519
std       9847.895441
min       7594.000000
25%      25986.750000
50%      32488.000000
75%      38226.250000
max      66124.000000
Name: patch_count, dtype: float64

Saved:
E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest\patch_all_v2_tslungguard_nochest_resume\patch_position_counts.csv
E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest\patch_all_v2_tslungguard_nochest_resume\patch_count_by_patient.csv

In [1]:
from pathlib import Path
import pandas as pd

PATCH_OUT = Path(r"E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v1\patch_all_v2_resume")
PATCH_BY_PATIENT_DIR = PATCH_OUT / "patches_by_patient"
PATCH_DONE_DIR = PATCH_OUT / "done_markers"

csv_files = sorted([p for p in PATCH_BY_PATIENT_DIR.glob("*.csv") if not p.name.endswith(".tmp.csv")])
tmp_files = sorted(PATCH_BY_PATIENT_DIR.glob("*.tmp.csv"))
done_files = sorted(PATCH_DONE_DIR.glob("*.done"))

print("patient csv count:", len(csv_files))
print("tmp csv count:", len(tmp_files))
print("done marker count:", len(done_files))

summary_df = pd.read_csv(PATCH_OUT / "patch_patient_summary.csv")
count_df = pd.read_csv(PATCH_OUT / "patch_count_by_patient.csv")
position_df = pd.read_csv(PATCH_OUT / "patch_position_counts.csv")

print("summary rows:", len(summary_df))
print("patch_count_by_patient rows:", len(count_df))
print("position rows:", len(position_df))

print("\nsummary status counts:")
print(summary_df["status"].value_counts(dropna=False))

print("\nposition counts:")
display(position_df)

print("\npatch count summary:")
display(count_df["patch_count"].describe())

patient csv count: 362
tmp csv count: 0
done marker count: 362
summary rows: 362
patch_count_by_patient rows: 362
position rows: 6

summary status counts:
status
success    362
Name: count, dtype: int64

position counts:

        position_bin  patch_count
0      lower_central       829688
1   lower_peripheral      2214954
2     middle_central      1815279
3  middle_peripheral      4128678
4      upper_central       998059
5   upper_peripheral      2246813

patch count summary:

count      362.000000
mean     33794.118785
std       9955.532283
min      10362.000000
25%      27313.000000
50%      33391.500000
75%      39496.250000
max      73093.000000
Name: patch_count, dtype: float64