In [1]:
# ============================================================
# Build final training-ready dataset v2
# ------------------------------------------------------------
# 목적:
#   - 기존 전처리 결과와 patch CSV를 학습용 최종 폴더로 정리
#   - 환자별 full volume을 .npy로 저장
#   - CT는 int16 유지
#   - pure_lung / organ_exclusion mask 저장
#   - patch CSV에 학습용 .npy 경로 추가
#   - 빈 patch CSV / patch 없는 환자도 안전 처리
#   - train / val / test 환자 단위 split 생성
#   - 이미 만든 환자는 재실행 시 skip 가능
# ============================================================

from pathlib import Path
import json
import shutil
import hashlib
import random
import time
import gc

import numpy as np
import pandas as pd
import SimpleITK as sitk
from tqdm import tqdm
from pandas.errors import EmptyDataError


# ============================================================
# 1. CONFIG
# ============================================================

CONFIG = {
    # 전체 전처리 완료 폴더
    "preprocess_root": r"E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest",

    # patch 추출 결과 폴더 이름
    "patch_root_name": "patch_all_v2_tslungguard_nochest_resume",

    # 최종 학습용 폴더
    "training_ready_root": r"E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest",

    # CT 저장 dtype
    # 사용자가 여러 테스트를 위해 int16 유지 원함
    "ct_dtype": "int16",

    # mask 저장 dtype
    "mask_dtype": "uint8",

    # 기존 환자 결과가 있으면 skip
    "skip_existing": True,

    # 기존 결과 덮어쓰기
    "overwrite_existing": False,

    # patch CSV가 없는 환자 처리 방식
    # True  = patch CSV 없으면 에러 기록
    # False = volume만 만들고 patch_count=0으로 기록
    "require_patch_csv": False,

    # 최종 patch CSV에서 원본 NIfTI 경로 컬럼 제거 여부
    "drop_source_nii_columns_in_patch_csv": False,

    # 정상 데이터 label
    "default_label": "normal",

    # train / val / test split
    "make_train_val_test_split": True,
    "split_seed": 42,
    "train_ratio": 0.80,
    "val_ratio": 0.10,
    "test_ratio": 0.10,
}


PRE_ROOT = Path(CONFIG["preprocess_root"])
PATCH_ROOT = PRE_ROOT / CONFIG["patch_root_name"]
PATCH_BY_PATIENT_DIR = PATCH_ROOT / "patches_by_patient"

OUT_ROOT = Path(CONFIG["training_ready_root"])
VOLUME_ROOT = OUT_ROOT / "volumes_npy"
PATCH_INDEX_ROOT = OUT_ROOT / "patch_index_by_patient"
MANIFEST_DIR = OUT_ROOT / "manifests"
CONFIG_DIR = OUT_ROOT / "configs"
LOG_DIR = OUT_ROOT / "logs"

for d in [OUT_ROOT, VOLUME_ROOT, PATCH_INDEX_ROOT, MANIFEST_DIR, CONFIG_DIR, LOG_DIR]:
    d.mkdir(parents=True, exist_ok=True)

with open(CONFIG_DIR / "training_ready_config.json", "w", encoding="utf-8") as f:
    json.dump(CONFIG, f, indent=2, ensure_ascii=False)

print("========== CONFIG ==========")
print("PRE_ROOT:", PRE_ROOT)
print("PATCH_ROOT:", PATCH_ROOT)
print("PATCH_BY_PATIENT_DIR:", PATCH_BY_PATIENT_DIR)
print("OUT_ROOT:", OUT_ROOT)
print("VOLUME_ROOT:", VOLUME_ROOT)
print("PATCH_INDEX_ROOT:", PATCH_INDEX_ROOT)
print("ct_dtype:", CONFIG["ct_dtype"])


# ============================================================
# 2. helper functions
# ============================================================

def format_seconds(seconds: float) -> str:
    seconds = int(seconds)

    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60

    if h > 0:
        return f"{h}시간 {m}분 {s}초"

    if m > 0:
        return f"{m}분 {s}초"

    return f"{s}초"


def safe_id_from_patient_id(patient_id: str, max_prefix_len: int = 80) -> str:
    """
    긴 LUNA16 UID를 Windows 경로에서 안전하게 쓰기 위한 짧은 ID 생성.
    원래 patient_id는 manifest에 그대로 보존함.
    """

    patient_id = str(patient_id)

    cleaned = (
        patient_id
        .replace("\\", "_")
        .replace("/", "_")
        .replace(":", "_")
        .replace("*", "_")
        .replace("?", "_")
        .replace('"', "_")
        .replace("<", "_")
        .replace(">", "_")
        .replace("|", "_")
        .replace(" ", "_")
        .replace("(", "")
        .replace(")", "")
        .replace("[", "")
        .replace("]", "")
    )

    digest = hashlib.md5(patient_id.encode("utf-8")).hexdigest()[:10]

    if len(cleaned) > max_prefix_len:
        cleaned = cleaned[:max_prefix_len]

    return f"{cleaned}__{digest}"


def safe_patient_csv_name(patient_id: str) -> str:
    """
    patch_all_v2_resume 쪽 환자별 CSV 이름과 맞추기 위한 safe name.
    """

    return (
        str(patient_id)
        .replace("\\", "_")
        .replace("/", "_")
        .replace(":", "_")
        .replace("*", "_")
        .replace("?", "_")
        .replace('"', "_")
        .replace("<", "_")
        .replace(">", "_")
        .replace("|", "_")
    )


def read_sitk_array(path: Path):
    img = sitk.ReadImage(str(path))
    arr = sitk.GetArrayFromImage(img)
    return img, arr


def convert_ct_array_for_save(ct_arr: np.ndarray, dtype_name: str):
    """
    CT HU를 학습용 cache로 저장.
    현재 기본은 int16.
    sitkLinear 보간 때문에 float HU가 있을 수 있으므로 int16 저장 시 반올림됨.
    """

    dtype_name = str(dtype_name).lower()

    if dtype_name == "int16":
        if np.issubdtype(ct_arr.dtype, np.floating):
            out = np.rint(ct_arr)
            out = np.clip(out, np.iinfo(np.int16).min, np.iinfo(np.int16).max)
            return out.astype(np.int16)

        return ct_arr.astype(np.int16, copy=False)

    if dtype_name == "float32":
        return ct_arr.astype(np.float32, copy=False)

    raise ValueError(f"지원하지 않는 ct_dtype: {dtype_name}")


def convert_mask_array_for_save(mask_arr: np.ndarray, dtype_name: str):
    """
    mask는 0/1 형태로 저장.
    """

    dtype_name = str(dtype_name).lower()

    if dtype_name == "uint8":
        return (mask_arr > 0).astype(np.uint8)

    if dtype_name == "bool":
        return mask_arr > 0

    raise ValueError(f"지원하지 않는 mask_dtype: {dtype_name}")


def save_json(obj, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)


def read_json_if_exists(path: Path):
    if not path.exists():
        return {}

    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def copy_config_if_exists(src: Path, dst: Path):
    if src.exists():
        shutil.copy2(str(src), str(dst))
        return True

    return False


def read_csv_safe(path: Path):
    """
    빈 CSV도 에러 없이 읽기.
    """

    try:
        return pd.read_csv(path)
    except EmptyDataError:
        return pd.DataFrame()


def count_rows_csv_safe(path: Path):
    """
    patch CSV row 수 계산.
    빈 CSV면 0 반환.
    """

    if not path.exists():
        return 0

    try:
        df = pd.read_csv(path, usecols=["patient_id"])
        return int(len(df))
    except EmptyDataError:
        return 0
    except Exception:
        try:
            df = pd.read_csv(path)
            return int(len(df))
        except Exception:
            return 0


def make_empty_patch_df():
    """
    patch가 없는 환자도 빈 CSV에 최소 header를 남김.
    """

    return pd.DataFrame(columns=[
        "patient_id",
        "safe_id",
        "label",
        "local_z",
        "y0",
        "x0",
        "y1",
        "x1",
        "patch_size",
        "patch_stride",
        "position_bin",
        "z_level",
        "central_peripheral",
        "left_right_metadata",
        "pure_lung_patch_ratio",
        "organ_patch_ratio",
        "slice_pure_lung_ratio",
        "volume_dir",
        "ct_hu_npy",
        "pure_lung_npy",
        "organ_exclusion_npy",
        "volume_meta_json",
        "rel_volume_dir",
        "rel_ct_hu_npy",
        "rel_pure_lung_npy",
        "rel_organ_exclusion_npy",
        "rel_volume_meta_json",
    ])


def find_existing_patch_csv(patient_id: str, patch_summary_df=None):
    """
    patch_all_v2_resume 결과에서 환자별 patch csv 찾기.

    1순위:
        patch_patient_summary.csv의 patient_csv

    2순위:
        patches_by_patient 폴더에서 safe name 기반 직접 검색
    """

    patient_id = str(patient_id)

    if patch_summary_df is not None and len(patch_summary_df) > 0:
        if "patient_id" in patch_summary_df.columns and "patient_csv" in patch_summary_df.columns:
            rows = patch_summary_df[patch_summary_df["patient_id"].astype(str) == patient_id]

            if len(rows) > 0:
                for p in rows["patient_csv"].dropna().tolist():
                    p = Path(str(p))

                    if p.exists():
                        return p

    direct_name = safe_patient_csv_name(patient_id)
    direct_path = PATCH_BY_PATIENT_DIR / f"{direct_name}.csv"

    if direct_path.exists():
        return direct_path

    return None


# ============================================================
# 3. load metadata
# ============================================================

metadata_slices_path = PRE_ROOT / "metadata_slices.csv"
metadata_organs_path = PRE_ROOT / "metadata_organs.csv"
patch_summary_path = PATCH_ROOT / "patch_patient_summary.csv"
patch_config_path = PATCH_ROOT / "patch_config.json"
preprocess_config_path = PRE_ROOT / "final_preprocess_config.json"

if not metadata_slices_path.exists():
    raise FileNotFoundError(f"metadata_slices.csv 없음: {metadata_slices_path}")

if not PATCH_BY_PATIENT_DIR.exists():
    raise FileNotFoundError(f"patches_by_patient 폴더 없음: {PATCH_BY_PATIENT_DIR}")

slice_df = pd.read_csv(metadata_slices_path)

required_cols = [
    "patient_id",
    "ct_1mm_lung_range_nii",
    "pure_lung_lung_range_nii",
    "organ_exclusion_lung_range_nii",
]

for c in required_cols:
    if c not in slice_df.columns:
        raise RuntimeError(f"metadata_slices.csv에 필요한 컬럼 없음: {c}")

if patch_summary_path.exists():
    patch_summary_df = pd.read_csv(patch_summary_path)
else:
    patch_summary_df = pd.DataFrame()

patient_ids = sorted(slice_df["patient_id"].astype(str).unique())

print("========== INPUT CHECK ==========")
print("patient count:", len(patient_ids))
print("metadata_slices:", metadata_slices_path)
print("patch_summary exists:", patch_summary_path.exists())
print("patch csv dir:", PATCH_BY_PATIENT_DIR)

copy_config_if_exists(preprocess_config_path, CONFIG_DIR / "preprocess_config.json")
copy_config_if_exists(patch_config_path, CONFIG_DIR / "patch_config.json")


# ============================================================
# 4. build one patient training-ready files
# ============================================================

def build_one_patient(patient_id: str, row0, patch_summary_df):
    safe_id = safe_id_from_patient_id(patient_id)

    patient_volume_dir = VOLUME_ROOT / safe_id
    patient_patch_csv_out = PATCH_INDEX_ROOT / f"{safe_id}.csv"

    ct_npy = patient_volume_dir / "ct_hu.npy"
    pure_npy = patient_volume_dir / "pure_lung.npy"
    organ_npy = patient_volume_dir / "organ_exclusion.npy"
    meta_json = patient_volume_dir / "meta.json"
    done_marker = patient_volume_dir / ".done"

    if bool(CONFIG["overwrite_existing"]):
        if patient_volume_dir.exists():
            shutil.rmtree(patient_volume_dir)

        if patient_patch_csv_out.exists():
            patient_patch_csv_out.unlink()

    # --------------------------------------------------------
    # skip branch
    # 이미 만들어진 환자는 meta.json 읽어서 manifest 정보까지 채움
    # --------------------------------------------------------
    if (
        bool(CONFIG["skip_existing"])
        and done_marker.exists()
        and ct_npy.exists()
        and pure_npy.exists()
        and organ_npy.exists()
        and patient_patch_csv_out.exists()
    ):
        meta = read_json_if_exists(meta_json)
        patch_count = count_rows_csv_safe(patient_patch_csv_out)

        return {
            "patient_id": patient_id,
            "safe_id": safe_id,
            "status": "skipped_existing",
            "label": meta.get("label", CONFIG["default_label"]),

            "volume_dir": str(patient_volume_dir),
            "ct_hu_npy": str(ct_npy),
            "pure_lung_npy": str(pure_npy),
            "organ_exclusion_npy": str(organ_npy),
            "meta_json": str(meta_json),

            "source_ct_1mm_lung_range_nii": meta.get("source_ct_1mm_lung_range_nii", ""),
            "source_pure_lung_lung_range_nii": meta.get("source_pure_lung_lung_range_nii", ""),
            "source_organ_exclusion_lung_range_nii": meta.get("source_organ_exclusion_lung_range_nii", ""),

            "source_patch_csv": meta.get("source_patch_csv", ""),
            "patch_csv": str(patient_patch_csv_out),
            "patch_count": int(patch_count),

            "shape_zyx": str(tuple(meta.get("shape_zyx", []))),
            "spacing_xyz": str(tuple(meta.get("spacing_xyz", []))),
        }

    patient_volume_dir.mkdir(parents=True, exist_ok=True)

    ct_path = Path(row0["ct_1mm_lung_range_nii"])
    pure_path = Path(row0["pure_lung_lung_range_nii"])
    organ_path = Path(row0["organ_exclusion_lung_range_nii"])

    if not ct_path.exists():
        raise FileNotFoundError(f"CT lung range 없음: {ct_path}")

    if not pure_path.exists():
        raise FileNotFoundError(f"pure lung range 없음: {pure_path}")

    if not organ_path.exists():
        raise FileNotFoundError(f"organ exclusion lung range 없음: {organ_path}")

    source_patch_csv = find_existing_patch_csv(
        patient_id=patient_id,
        patch_summary_df=patch_summary_df,
    )

    if source_patch_csv is None and bool(CONFIG["require_patch_csv"]):
        raise FileNotFoundError(f"환자 patch CSV 없음: {patient_id}")

    # --------------------------------------------------------
    # read NIfTI
    # --------------------------------------------------------
    ct_img, ct_arr = read_sitk_array(ct_path)
    pure_img, pure_arr = read_sitk_array(pure_path)
    organ_img, organ_arr = read_sitk_array(organ_path)

    if ct_arr.shape != pure_arr.shape:
        raise RuntimeError(f"{patient_id}: CT와 pure_lung shape 다름")

    if ct_arr.shape != organ_arr.shape:
        raise RuntimeError(f"{patient_id}: CT와 organ_exclusion shape 다름")

    # --------------------------------------------------------
    # save arrays
    # --------------------------------------------------------
    ct_save = convert_ct_array_for_save(ct_arr, CONFIG["ct_dtype"])
    pure_save = convert_mask_array_for_save(pure_arr, CONFIG["mask_dtype"])
    organ_save = convert_mask_array_for_save(organ_arr, CONFIG["mask_dtype"])

    # del 전에 미리 저장해야 summary가 비지 않음
    shape_zyx = tuple(map(int, ct_save.shape))
    spacing_xyz = tuple(map(float, ct_img.GetSpacing()))
    origin_xyz = tuple(map(float, ct_img.GetOrigin()))
    direction = tuple(map(float, ct_img.GetDirection()))

    np.save(ct_npy, ct_save)
    np.save(pure_npy, pure_save)
    np.save(organ_npy, organ_save)

    # --------------------------------------------------------
    # patch CSV 정리
    # --------------------------------------------------------
    patch_count = 0

    if source_patch_csv is not None and Path(source_patch_csv).exists():
        patch_df = read_csv_safe(Path(source_patch_csv))

        if len(patch_df) == 0:
            patch_df = make_empty_patch_df()
            patch_count = 0
        else:
            patch_count = int(len(patch_df))

            patch_df["safe_id"] = safe_id
            patch_df["label"] = CONFIG["default_label"]

            patch_df["volume_dir"] = str(patient_volume_dir)
            patch_df["ct_hu_npy"] = str(ct_npy)
            patch_df["pure_lung_npy"] = str(pure_npy)
            patch_df["organ_exclusion_npy"] = str(organ_npy)
            patch_df["volume_meta_json"] = str(meta_json)

            patch_df["rel_volume_dir"] = str(patient_volume_dir.relative_to(OUT_ROOT))
            patch_df["rel_ct_hu_npy"] = str(ct_npy.relative_to(OUT_ROOT))
            patch_df["rel_pure_lung_npy"] = str(pure_npy.relative_to(OUT_ROOT))
            patch_df["rel_organ_exclusion_npy"] = str(organ_npy.relative_to(OUT_ROOT))
            patch_df["rel_volume_meta_json"] = str(meta_json.relative_to(OUT_ROOT))

            if bool(CONFIG["drop_source_nii_columns_in_patch_csv"]):
                drop_cols = [
                    "ct_1mm_lung_range_nii",
                    "pure_lung_lung_range_nii",
                    "organ_exclusion_lung_range_nii",
                ]

                patch_df = patch_df.drop(
                    columns=[c for c in drop_cols if c in patch_df.columns],
                    errors="ignore",
                )
    else:
        patch_df = make_empty_patch_df()
        patch_count = 0

    patch_df.to_csv(
        patient_patch_csv_out,
        index=False,
        encoding="utf-8-sig",
    )

    # --------------------------------------------------------
    # meta 저장
    # --------------------------------------------------------
    meta = {
        "patient_id": patient_id,
        "safe_id": safe_id,
        "label": CONFIG["default_label"],

        "shape_zyx": list(shape_zyx),
        "ct_dtype": str(ct_save.dtype),
        "mask_dtype": str(pure_save.dtype),

        "spacing_xyz": list(spacing_xyz),
        "origin_xyz": list(origin_xyz),
        "direction": list(direction),

        "source_ct_1mm_lung_range_nii": str(ct_path),
        "source_pure_lung_lung_range_nii": str(pure_path),
        "source_organ_exclusion_lung_range_nii": str(organ_path),
        "source_patch_csv": str(source_patch_csv) if source_patch_csv is not None else "",

        "ct_hu_npy": str(ct_npy),
        "pure_lung_npy": str(pure_npy),
        "organ_exclusion_npy": str(organ_npy),

        "patch_csv": str(patient_patch_csv_out),
        "patch_count": int(patch_count),

        "ct_dtype_save_policy": "int16 유지. sitkLinear 보간 소수점 HU는 반올림되어 저장됨.",
    }

    save_json(meta, meta_json)
    done_marker.write_text("done", encoding="utf-8")

    # 메모리 정리
    del ct_arr, pure_arr, organ_arr
    del ct_save, pure_save, organ_save
    del patch_df
    gc.collect()

    return {
        "patient_id": patient_id,
        "safe_id": safe_id,
        "status": "success",
        "label": CONFIG["default_label"],

        "volume_dir": str(patient_volume_dir),
        "ct_hu_npy": str(ct_npy),
        "pure_lung_npy": str(pure_npy),
        "organ_exclusion_npy": str(organ_npy),
        "meta_json": str(meta_json),

        "source_ct_1mm_lung_range_nii": str(ct_path),
        "source_pure_lung_lung_range_nii": str(pure_path),
        "source_organ_exclusion_lung_range_nii": str(organ_path),
        "source_patch_csv": str(source_patch_csv) if source_patch_csv is not None else "",

        "patch_csv": str(patient_patch_csv_out),
        "patch_count": int(patch_count),

        "shape_zyx": str(shape_zyx),
        "spacing_xyz": str(spacing_xyz),
    }


# ============================================================
# 5. run build
# ============================================================

summary_rows = []
error_rows = []

global_start = time.perf_counter()
total_cases = len(patient_ids)

print("\n========== BUILD TRAINING READY START ==========")

for case_idx, patient_id in enumerate(
    tqdm(
        patient_ids,
        desc="Build training-ready dataset",
        total=total_cases,
        ncols=100,
        ascii=True,
        leave=True,
        dynamic_ncols=False,
    ),
    start=1,
):
    start = time.perf_counter()

    try:
        pdf = slice_df[slice_df["patient_id"].astype(str) == str(patient_id)]

        if len(pdf) == 0:
            raise RuntimeError(f"metadata_slices.csv에 환자 row 없음: {patient_id}")

        row0 = pdf.iloc[0]

        row = build_one_patient(
            patient_id=str(patient_id),
            row0=row0,
            patch_summary_df=patch_summary_df,
        )

        elapsed = time.perf_counter() - start
        total_elapsed = time.perf_counter() - global_start
        avg = total_elapsed / case_idx
        remain = total_cases - case_idx
        eta = avg * remain

        row.update({
            "case_index": int(case_idx),
            "total_cases": int(total_cases),
            "elapsed_seconds": round(elapsed, 2),
            "elapsed_readable": format_seconds(elapsed),
            "total_elapsed_seconds": round(total_elapsed, 2),
            "total_elapsed_readable": format_seconds(total_elapsed),
            "estimated_remaining_seconds": round(eta, 2),
            "estimated_remaining_readable": format_seconds(eta),
        })

        summary_rows.append(row)

        pd.DataFrame(summary_rows).to_csv(
            LOG_DIR / "build_training_ready_summary.csv",
            index=False,
            encoding="utf-8-sig",
        )

        print(
            f"[READY] {patient_id} 완료 "
            f"({case_idx}/{total_cases}) | "
            f"status={row['status']} | "
            f"patch={row.get('patch_count', 0)} | "
            f"이번 환자: {format_seconds(elapsed)} | "
            f"예상 남은 시간: {format_seconds(eta)}"
        )

    except Exception as e:
        elapsed = time.perf_counter() - start

        err = {
            "patient_id": str(patient_id),
            "error": str(e),
            "elapsed_seconds": round(elapsed, 2),
            "elapsed_readable": format_seconds(elapsed),
        }

        error_rows.append(err)

        pd.DataFrame(error_rows).to_csv(
            LOG_DIR / "build_training_ready_errors.csv",
            index=False,
            encoding="utf-8-sig",
        )

        print("[ERROR]", patient_id, str(e))

    gc.collect()


summary_df = pd.DataFrame(summary_rows)
error_df = pd.DataFrame(error_rows)

summary_df.to_csv(
    LOG_DIR / "build_training_ready_summary.csv",
    index=False,
    encoding="utf-8-sig",
)

if len(error_df) > 0:
    error_df.to_csv(
        LOG_DIR / "build_training_ready_errors.csv",
        index=False,
        encoding="utf-8-sig",
    )

print("\n========== BUILD TRAINING READY FINISHED ==========")
print("OUT_ROOT:", OUT_ROOT)
print("success / skipped rows:", len(summary_df))
print("errors:", len(error_df))


# ============================================================
# 6. create patient manifest
# ============================================================

if len(summary_df) == 0:
    raise RuntimeError("성공한 환자가 없음. error csv 확인 필요.")

patient_manifest = summary_df.copy()

front_cols = [
    "patient_id",
    "safe_id",
    "status",
    "label",
    "patch_count",
    "shape_zyx",
    "spacing_xyz",
    "volume_dir",
    "ct_hu_npy",
    "pure_lung_npy",
    "organ_exclusion_npy",
    "meta_json",
    "patch_csv",
]

front_cols = [c for c in front_cols if c in patient_manifest.columns]
other_cols = [c for c in patient_manifest.columns if c not in front_cols]
patient_manifest = patient_manifest[front_cols + other_cols]

patient_manifest.to_csv(
    MANIFEST_DIR / "patient_manifest.csv",
    index=False,
    encoding="utf-8-sig",
)

# source patch summary 복사
if patch_summary_path.exists():
    shutil.copy2(
        str(patch_summary_path),
        str(MANIFEST_DIR / "source_patch_patient_summary.csv"),
    )

if (PATCH_ROOT / "patch_position_counts.csv").exists():
    shutil.copy2(
        str(PATCH_ROOT / "patch_position_counts.csv"),
        str(MANIFEST_DIR / "source_patch_position_counts.csv"),
    )

if (PATCH_ROOT / "patch_count_by_patient.csv").exists():
    shutil.copy2(
        str(PATCH_ROOT / "patch_count_by_patient.csv"),
        str(MANIFEST_DIR / "source_patch_count_by_patient.csv"),
    )


# ============================================================
# 7. summarize final patch CSVs
# ============================================================

patient_position_rows = []
patch_count_rows = []

for _, row in tqdm(
    patient_manifest.iterrows(),
    total=len(patient_manifest),
    desc="Summarize final patch indexes",
    ncols=100,
    ascii=True,
):
    patient_id = row["patient_id"]
    safe_id = row["safe_id"]
    patch_csv = Path(row["patch_csv"])

    if not patch_csv.exists():
        patch_count_rows.append({
            "patient_id": patient_id,
            "safe_id": safe_id,
            "patch_count": 0,
        })
        continue

    try:
        df = pd.read_csv(
            patch_csv,
            usecols=["patient_id", "position_bin"],
        )
    except EmptyDataError:
        df = pd.DataFrame(columns=["patient_id", "position_bin"])
    except ValueError:
        df = pd.DataFrame(columns=["patient_id", "position_bin"])

    patch_count_rows.append({
        "patient_id": patient_id,
        "safe_id": safe_id,
        "patch_count": int(len(df)),
    })

    if len(df) == 0:
        continue

    counts = df["position_bin"].value_counts()

    for position_bin, count in counts.items():
        patient_position_rows.append({
            "patient_id": patient_id,
            "safe_id": safe_id,
            "position_bin": position_bin,
            "patch_count": int(count),
        })

patient_position_df = pd.DataFrame(patient_position_rows)
patch_count_df = pd.DataFrame(patch_count_rows)

if len(patient_position_df) > 0:
    patch_position_counts = (
        patient_position_df
        .groupby("position_bin", as_index=False)["patch_count"]
        .sum()
        .sort_values("position_bin")
    )
else:
    patch_position_counts = pd.DataFrame(columns=["position_bin", "patch_count"])

patient_position_df.to_csv(
    MANIFEST_DIR / "patient_position_counts.csv",
    index=False,
    encoding="utf-8-sig",
)

patch_position_counts.to_csv(
    MANIFEST_DIR / "patch_position_counts.csv",
    index=False,
    encoding="utf-8-sig",
)

patch_count_df.to_csv(
    MANIFEST_DIR / "patch_count_by_patient.csv",
    index=False,
    encoding="utf-8-sig",
)


# ============================================================
# 8. train / val / test split
# ============================================================

if bool(CONFIG["make_train_val_test_split"]):
    split_base = patient_manifest.copy()

    split_base["patch_count"] = split_base["patch_count"].fillna(0).astype(int)

    # patch_count 0인 환자는 split 제외
    split_df = split_base[
        split_base["patch_count"] > 0
    ][[
        "patient_id",
        "safe_id",
        "patch_count",
        "patch_csv",
        "volume_dir",
        "ct_hu_npy",
        "pure_lung_npy",
        "organ_exclusion_npy",
    ]].copy()

    rng = random.Random(int(CONFIG["split_seed"]))
    ids = split_df["patient_id"].tolist()
    rng.shuffle(ids)

    n = len(ids)

    n_train = int(round(n * float(CONFIG["train_ratio"])))
    n_val = int(round(n * float(CONFIG["val_ratio"])))

    # 비율 반올림 때문에 전체를 넘지 않게 보정
    if n_train + n_val > n:
        n_val = max(0, n - n_train)

    train_ids = set(ids[:n_train])
    val_ids = set(ids[n_train:n_train + n_val])
    test_ids = set(ids[n_train + n_val:])

    def assign_split(pid):
        if pid in train_ids:
            return "train"

        if pid in val_ids:
            return "val"

        return "test"

    split_df["split"] = split_df["patient_id"].apply(assign_split)

    split_df.to_csv(
        MANIFEST_DIR / "train_val_test_split.csv",
        index=False,
        encoding="utf-8-sig",
    )

    split_df[split_df["split"] == "train"].to_csv(
        MANIFEST_DIR / "train_patients.csv",
        index=False,
        encoding="utf-8-sig",
    )

    split_df[split_df["split"] == "val"].to_csv(
        MANIFEST_DIR / "val_patients.csv",
        index=False,
        encoding="utf-8-sig",
    )

    split_df[split_df["split"] == "test"].to_csv(
        MANIFEST_DIR / "test_patients.csv",
        index=False,
        encoding="utf-8-sig",
    )

    print("\n========== SPLIT COUNT ==========")
    print(split_df["split"].value_counts())

    # --------------------------------------------------------
    # split별 position_bin 분포 확인
    # --------------------------------------------------------
    split_position_rows = []

    split_map = dict(zip(split_df["patient_id"], split_df["split"]))

    if len(patient_position_df) > 0:
        for _, r in patient_position_df.iterrows():
            pid = r["patient_id"]

            if pid not in split_map:
                continue

            split_position_rows.append({
                "split": split_map[pid],
                "patient_id": pid,
                "safe_id": r["safe_id"],
                "position_bin": r["position_bin"],
                "patch_count": int(r["patch_count"]),
            })

    split_position_df = pd.DataFrame(split_position_rows)

    if len(split_position_df) > 0:
        split_position_summary = (
            split_position_df
            .groupby(["split", "position_bin"], as_index=False)["patch_count"]
            .sum()
            .sort_values(["split", "position_bin"])
        )
    else:
        split_position_summary = pd.DataFrame(columns=["split", "position_bin", "patch_count"])

    split_position_df.to_csv(
        MANIFEST_DIR / "split_patient_position_counts.csv",
        index=False,
        encoding="utf-8-sig",
    )

    split_position_summary.to_csv(
        MANIFEST_DIR / "split_position_counts.csv",
        index=False,
        encoding="utf-8-sig",
    )

    print("\n========== SPLIT POSITION COUNTS ==========")
    display(split_position_summary)


# ============================================================
# 9. final check
# ============================================================

print("\n========== FINAL OUTPUT ==========")
print("OUT_ROOT:", OUT_ROOT)
print("volumes_npy:", VOLUME_ROOT)
print("patch_index_by_patient:", PATCH_INDEX_ROOT)
print("manifests:", MANIFEST_DIR)
print("configs:", CONFIG_DIR)
print("logs:", LOG_DIR)

print("\n========== FILES ==========")
print("patient_manifest:", MANIFEST_DIR / "patient_manifest.csv")
print("patch_position_counts:", MANIFEST_DIR / "patch_position_counts.csv")
print("patch_count_by_patient:", MANIFEST_DIR / "patch_count_by_patient.csv")
print("patient_position_counts:", MANIFEST_DIR / "patient_position_counts.csv")

if bool(CONFIG["make_train_val_test_split"]):
    print("train_val_test_split:", MANIFEST_DIR / "train_val_test_split.csv")
    print("split_position_counts:", MANIFEST_DIR / "split_position_counts.csv")

print("\n========== Position bin counts ==========")
display(patch_position_counts)

print("\n========== Patch count by patient summary ==========")
if len(patch_count_df) > 0:
    display(patch_count_df["patch_count"].describe())
else:
    print("patch_count_df 비어 있음")

print("\n========== Error count ==========")
print(len(error_df))

if len(error_df) > 0:
    print("error file:", LOG_DIR / "build_training_ready_errors.csv")

========== CONFIG ==========
PRE_ROOT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest
PATCH_ROOT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest\patch_all_v2_tslungguard_nochest_resume
PATCH_BY_PATIENT_DIR: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest\patch_all_v2_tslungguard_nochest_resume\patches_by_patient
OUT_ROOT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest
VOLUME_ROOT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\volumes_npy
PATCH_INDEX_ROOT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\patch_index_by_patient
ct_dtype: int16
========== INPUT CHECK ==========
patient count: 362
metadata_slices: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest\metadata_slices.csv
patch_summary exists: True
patch csv dir: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_final_all_nonfast_v2_tslungguard_nochest\patch_all_v2_tslungguard_nochest_resume\patches_by_patient

========== BUILD TRAINING READY START ==========

Build training-ready dataset:   0%|                                 | 1/362 [00:03<18:11,  3.02s/it]

[READY] normal001 완료 (1/362) | status=success | patch=20948 | 이번 환자: 2초 | 예상 남은 시간: 18분 0초

Build training-ready dataset:   1%|1                                | 2/362 [00:05<17:55,  2.99s/it]

[READY] normal002 완료 (2/362) | status=success | patch=22012 | 이번 환자: 2초 | 예상 남은 시간: 17분 47초

Build training-ready dataset:   1%|2                                | 3/362 [00:09<19:53,  3.32s/it]

[READY] normal003 완료 (3/362) | status=success | patch=30825 | 이번 환자: 3초 | 예상 남은 시간: 19분 18초

Build training-ready dataset:   1%|3                                | 4/362 [00:12<19:39,  3.30s/it]

[READY] normal004 완료 (4/362) | status=success | patch=27119 | 이번 환자: 3초 | 예상 남은 시간: 19분 17초

Build training-ready dataset:   1%|4                                | 5/362 [00:16<20:14,  3.40s/it]

[READY] normal005 완료 (5/362) | status=success | patch=32653 | 이번 환자: 3초 | 예상 남은 시간: 19분 40초

Build training-ready dataset:   2%|5                                | 6/362 [00:20<22:17,  3.76s/it]

[READY] normal006 완료 (6/362) | status=success | patch=39241 | 이번 환자: 4초 | 예상 남은 시간: 20분 43초

Build training-ready dataset:   2%|6                                | 7/362 [00:23<20:41,  3.50s/it]

[READY] normal007 완료 (7/362) | status=success | patch=23343 | 이번 환자: 2초 | 예상 남은 시간: 20분 13초

Build training-ready dataset:   2%|7                                | 8/362 [00:27<20:44,  3.52s/it]

[READY] normal008 완료 (8/362) | status=success | patch=33329 | 이번 환자: 3초 | 예상 남은 시간: 20분 16초

Build training-ready dataset:   2%|8                                | 9/362 [00:30<20:09,  3.43s/it]

[READY] normal009 완료 (9/362) | status=success | patch=25858 | 이번 환자: 3초 | 예상 남은 시간: 20분 4초

Build training-ready dataset:   3%|8                               | 10/362 [00:34<20:59,  3.58s/it]

[READY] normal010 완료 (10/362) | status=success | patch=34867 | 이번 환자: 3초 | 예상 남은 시간: 20분 19초

Build training-ready dataset:   3%|9                               | 11/362 [00:38<21:34,  3.69s/it]

[READY] normal011 완료 (11/362) | status=success | patch=36485 | 이번 환자: 3초 | 예상 남은 시간: 20분 30초

Build training-ready dataset:   3%|#                               | 12/362 [00:42<21:00,  3.60s/it]

[READY] normal012 완료 (12/362) | status=success | patch=30678 | 이번 환자: 3초 | 예상 남은 시간: 20분 24초

Build training-ready dataset:   4%|#1                              | 13/362 [00:44<19:34,  3.37s/it]

[READY] normal013 완료 (13/362) | status=success | patch=21424 | 이번 환자: 2초 | 예상 남은 시간: 20분 2초

Build training-ready dataset:   4%|#2                              | 14/362 [00:48<19:24,  3.35s/it]

[READY] normal014 완료 (14/362) | status=success | patch=28777 | 이번 환자: 3초 | 예상 남은 시간: 19분 55초

Build training-ready dataset:   4%|#3                              | 15/362 [00:51<19:02,  3.29s/it]

[READY] normal015 완료 (15/362) | status=success | patch=20598 | 이번 환자: 3초 | 예상 남은 시간: 19분 46초

Build training-ready dataset:   4%|#4                              | 16/362 [00:54<18:45,  3.25s/it]

[READY] normal016 완료 (16/362) | status=success | patch=24133 | 이번 환자: 3초 | 예상 남은 시간: 19분 36초

Build training-ready dataset:   5%|#5                              | 17/362 [00:57<19:00,  3.31s/it]

[READY] normal017 완료 (17/362) | status=success | patch=29881 | 이번 환자: 3초 | 예상 남은 시간: 19분 34초

Build training-ready dataset:   5%|#5                              | 18/362 [01:01<19:58,  3.48s/it]

[READY] normal018 완료 (18/362) | status=success | patch=33392 | 이번 환자: 3초 | 예상 남은 시간: 19분 40초

Build training-ready dataset:   5%|#6                              | 19/362 [01:05<20:07,  3.52s/it]

[READY] normal019 완료 (19/362) | status=success | patch=34172 | 이번 환자: 3초 | 예상 남은 시간: 19분 40초

Build training-ready dataset:   6%|#7                              | 20/362 [01:08<19:09,  3.36s/it]

[READY] normal020 완료 (20/362) | status=success | patch=24239 | 이번 환자: 2초 | 예상 남은 시간: 19분 28초

Build training-ready dataset:   6%|#8                              | 21/362 [01:11<19:22,  3.41s/it]

[READY] normal021 완료 (21/362) | status=success | patch=31543 | 이번 환자: 3초 | 예상 남은 시간: 19분 26초

Build training-ready dataset:   6%|#9                              | 22/362 [01:15<18:52,  3.33s/it]

[READY] normal022 완료 (22/362) | status=success | patch=22147 | 이번 환자: 3초 | 예상 남은 시간: 19분 19초

Build training-ready dataset:   6%|##                              | 23/362 [01:19<20:34,  3.64s/it]

[READY] normal023 완료 (23/362) | status=success | patch=41977 | 이번 환자: 4초 | 예상 남은 시간: 19분 30초

Build training-ready dataset:   7%|##1                             | 24/362 [01:23<21:07,  3.75s/it]

[READY] normal024 완료 (24/362) | status=success | patch=37894 | 이번 환자: 3초 | 예상 남은 시간: 19분 34초

Build training-ready dataset:   7%|##2                             | 25/362 [01:27<20:59,  3.74s/it]

[READY] normal025 완료 (25/362) | status=success | patch=32476 | 이번 환자: 3초 | 예상 남은 시간: 19분 34초

Build training-ready dataset:   7%|##2                             | 26/362 [01:30<21:00,  3.75s/it]

[READY] normal026 완료 (26/362) | status=success | patch=32734 | 이번 환자: 3초 | 예상 남은 시간: 19분 34초

Build training-ready dataset:   7%|##3                             | 27/362 [01:34<20:25,  3.66s/it]

[READY] normal027 완료 (27/362) | status=success | patch=26663 | 이번 환자: 3초 | 예상 남은 시간: 19분 30초

Build training-ready dataset:   8%|##4                             | 28/362 [01:37<19:05,  3.43s/it]

[READY] normal028 완료 (28/362) | status=success | patch=20975 | 이번 환자: 2초 | 예상 남은 시간: 19분 19초

Build training-ready dataset:   8%|##5                             | 29/362 [01:40<19:03,  3.43s/it]

[READY] normal029 완료 (29/362) | status=success | patch=26160 | 이번 환자: 3초 | 예상 남은 시간: 19분 15초

Build training-ready dataset:   8%|##6                             | 30/362 [01:44<19:18,  3.49s/it]

[READY] normal030 완료 (30/362) | status=success | patch=30925 | 이번 환자: 3초 | 예상 남은 시간: 19분 14초

Build training-ready dataset:   9%|##7                             | 31/362 [01:47<19:30,  3.54s/it]

[READY] normal031 완료 (31/362) | status=success | patch=29995 | 이번 환자: 3초 | 예상 남은 시간: 19분 12초

Build training-ready dataset:   9%|##8                             | 32/362 [01:50<18:13,  3.31s/it]

[READY] normal032 완료 (32/362) | status=success | patch=23004 | 이번 환자: 2초 | 예상 남은 시간: 19분 1초

Build training-ready dataset:   9%|##9                             | 33/362 [01:55<19:52,  3.63s/it]

[READY] normal033 완료 (33/362) | status=success | patch=38358 | 이번 환자: 4초 | 예상 남은 시간: 19분 7초

Build training-ready dataset:   9%|###                             | 34/362 [01:58<18:54,  3.46s/it]

[READY] normal034 완료 (34/362) | status=success | patch=23824 | 이번 환자: 3초 | 예상 남은 시간: 18분 59초

Build training-ready dataset:  10%|###                             | 35/362 [02:02<19:29,  3.58s/it]

[READY] normal035 완료 (35/362) | status=success | patch=35652 | 이번 환자: 3초 | 예상 남은 시간: 18분 59초

Build training-ready dataset:  10%|###1                            | 36/362 [02:05<20:01,  3.69s/it]

[READY] normal036 완료 (36/362) | status=success | patch=34569 | 이번 환자: 3초 | 예상 남은 시간: 19분 0초

Build training-ready dataset:  10%|###2                            | 37/362 [02:09<19:12,  3.55s/it]

[READY] normal037 완료 (37/362) | status=success | patch=27602 | 이번 환자: 3초 | 예상 남은 시간: 18분 54초

Build training-ready dataset:  10%|###3                            | 38/362 [02:14<21:26,  3.97s/it]

[READY] normal038 완료 (38/362) | status=success | patch=52080 | 이번 환자: 4초 | 예상 남은 시간: 19분 3초

Build training-ready dataset:  11%|###4                            | 39/362 [02:17<20:25,  3.79s/it]

[READY] normal039 완료 (39/362) | status=success | patch=24117 | 이번 환자: 3초 | 예상 남은 시간: 18분 58초

Build training-ready dataset:  11%|###5                            | 40/362 [02:20<19:46,  3.68s/it]

[READY] normal040 완료 (40/362) | status=success | patch=32221 | 이번 환자: 3초 | 예상 남은 시간: 18분 54초

Build training-ready dataset:  11%|###6                            | 41/362 [02:24<19:48,  3.70s/it]

[READY] normal041 완료 (41/362) | status=success | patch=30150 | 이번 환자: 3초 | 예상 남은 시간: 18분 52초

Build training-ready dataset:  12%|###7                            | 42/362 [02:27<18:52,  3.54s/it]

[READY] normal042 완료 (42/362) | status=success | patch=24745 | 이번 환자: 3초 | 예상 남은 시간: 18분 46초

Build training-ready dataset:  12%|###8                            | 43/362 [02:31<19:04,  3.59s/it]

[READY] normal043 완료 (43/362) | status=success | patch=31646 | 이번 환자: 3초 | 예상 남은 시간: 18분 43초

Build training-ready dataset:  12%|###8                            | 44/362 [02:35<19:36,  3.70s/it]

[READY] normal044 완료 (44/362) | status=success | patch=38253 | 이번 환자: 3초 | 예상 남은 시간: 18분 43초

Build training-ready dataset:  12%|###9                            | 45/362 [02:40<21:02,  3.98s/it]

[READY] normal045 완료 (45/362) | status=success | patch=39455 | 이번 환자: 4초 | 예상 남은 시간: 18분 48초

Build training-ready dataset:  13%|####                            | 46/362 [02:43<19:26,  3.69s/it]

[READY] normal046 완료 (46/362) | status=success | patch=19874 | 이번 환자: 2초 | 예상 남은 시간: 18분 40초

Build training-ready dataset:  13%|####1                           | 47/362 [02:46<18:40,  3.56s/it]

[READY] normal047 완료 (47/362) | status=success | patch=27299 | 이번 환자: 3초 | 예상 남은 시간: 18분 35초

Build training-ready dataset:  13%|####2                           | 48/362 [02:50<19:13,  3.67s/it]

[READY] normal048 완료 (48/362) | status=success | patch=36835 | 이번 환자: 3초 | 예상 남은 시간: 18분 34초

Build training-ready dataset:  14%|####3                           | 49/362 [02:54<19:55,  3.82s/it]

[READY] normal049 완료 (49/362) | status=success | patch=40415 | 이번 환자: 4초 | 예상 남은 시간: 18분 34초

Build training-ready dataset:  14%|####4                           | 50/362 [02:59<21:04,  4.05s/it]

[READY] normal050 완료 (50/362) | status=success | patch=43285 | 이번 환자: 4초 | 예상 남은 시간: 18분 37초

Build training-ready dataset:  14%|####5                           | 51/362 [03:02<20:37,  3.98s/it]

[READY] normal051 완료 (51/362) | status=success | patch=34465 | 이번 환자: 3초 | 예상 남은 시간: 18분 35초

Build training-ready dataset:  14%|####5                           | 52/362 [03:06<19:42,  3.81s/it]

[READY] normal052 완료 (52/362) | status=success | patch=28079 | 이번 환자: 3초 | 예상 남은 시간: 18분 30초

Build training-ready dataset:  15%|####6                           | 53/362 [03:09<18:51,  3.66s/it]

[READY] normal053 완료 (53/362) | status=success | patch=26605 | 이번 환자: 3초 | 예상 남은 시간: 18분 25초

Build training-ready dataset:  15%|####7                           | 54/362 [03:14<19:54,  3.88s/it]

[READY] normal054 완료 (54/362) | status=success | patch=37483 | 이번 환자: 4초 | 예상 남은 시간: 18분 26초

Build training-ready dataset:  15%|####8                           | 55/362 [03:17<19:28,  3.81s/it]

[READY] normal055 완료 (55/362) | status=success | patch=34903 | 이번 환자: 3초 | 예상 남은 시간: 18분 23초

Build training-ready dataset:  15%|####9                           | 56/362 [03:21<19:04,  3.74s/it]

[READY] normal056 완료 (56/362) | status=success | patch=33034 | 이번 환자: 3초 | 예상 남은 시간: 18분 19초

Build training-ready dataset:  16%|#####                           | 57/362 [03:24<18:25,  3.63s/it]

[READY] normal057 완료 (57/362) | status=success | patch=27838 | 이번 환자: 3초 | 예상 남은 시간: 18분 14초

Build training-ready dataset:  16%|#####1                          | 58/362 [03:27<17:30,  3.45s/it]

[READY] normal058 완료 (58/362) | status=success | patch=24600 | 이번 환자: 3초 | 예상 남은 시간: 18분 8초

Build training-ready dataset:  16%|#####2                          | 59/362 [03:32<19:29,  3.86s/it]

[READY] normal059 완료 (59/362) | status=success | patch=44421 | 이번 환자: 4초 | 예상 남은 시간: 18분 11초

Build training-ready dataset:  17%|#####3                          | 60/362 [03:36<20:03,  3.98s/it]

[READY] normal060 완료 (60/362) | status=success | patch=42949 | 이번 환자: 4초 | 예상 남은 시간: 18분 10초

Build training-ready dataset:  17%|#####3                          | 61/362 [03:39<18:37,  3.71s/it]

[READY] normal061 완료 (61/362) | status=success | patch=28589 | 이번 환자: 3초 | 예상 남은 시간: 18분 4초

Build training-ready dataset:  17%|#####4                          | 62/362 [03:42<17:29,  3.50s/it]

[READY] normal062 완료 (62/362) | status=success | patch=26013 | 이번 환자: 2초 | 예상 남은 시간: 17분 58초

Build training-ready dataset:  17%|#####5                          | 63/362 [03:45<16:22,  3.29s/it]

[READY] normal063 완료 (63/362) | status=success | patch=26090 | 이번 환자: 2초 | 예상 남은 시간: 17분 50초

Build training-ready dataset:  18%|#####6                          | 64/362 [03:48<16:05,  3.24s/it]

[READY] normal064 완료 (64/362) | status=success | patch=23826 | 이번 환자: 3초 | 예상 남은 시간: 17분 45초

Build training-ready dataset:  18%|#####7                          | 65/362 [03:52<17:08,  3.46s/it]

[READY] normal065 완료 (65/362) | status=success | patch=36114 | 이번 환자: 3초 | 예상 남은 시간: 17분 43초

Build training-ready dataset:  18%|#####8                          | 66/362 [03:56<17:19,  3.51s/it]

[READY] normal066 완료 (66/362) | status=success | patch=28836 | 이번 환자: 3초 | 예상 남은 시간: 17분 39초

Build training-ready dataset:  19%|#####9                          | 67/362 [03:59<17:14,  3.51s/it]

[READY] normal067 완료 (67/362) | status=success | patch=27944 | 이번 환자: 3초 | 예상 남은 시간: 17분 36초

Build training-ready dataset:  19%|######                          | 68/362 [04:03<17:34,  3.59s/it]

[READY] normal068 완료 (68/362) | status=success | patch=30335 | 이번 환자: 3초 | 예상 남은 시간: 17분 33초

Build training-ready dataset:  19%|######                          | 69/362 [04:08<19:03,  3.90s/it]

[READY] normal069 완료 (69/362) | status=success | patch=44501 | 이번 환자: 4초 | 예상 남은 시간: 17분 34초

Build training-ready dataset:  19%|######1                         | 70/362 [04:12<19:04,  3.92s/it]

[READY] normal070 완료 (70/362) | status=success | patch=34226 | 이번 환자: 3초 | 예상 남은 시간: 17분 32초

Build training-ready dataset:  20%|######2                         | 71/362 [04:16<19:06,  3.94s/it]

[READY] normal071 완료 (71/362) | status=success | patch=34989 | 이번 환자: 3초 | 예상 남은 시간: 17분 30초

Build training-ready dataset:  20%|######3                         | 72/362 [04:19<18:02,  3.73s/it]

[READY] normal073 완료 (72/362) | status=success | patch=27611 | 이번 환자: 3초 | 예상 남은 시간: 17분 25초

Build training-ready dataset:  20%|######4                         | 73/362 [04:22<17:13,  3.58s/it]

[READY] normal074 완료 (73/362) | status=success | patch=27632 | 이번 환자: 3초 | 예상 남은 시간: 17분 19초

Build training-ready dataset:  20%|######5                         | 74/362 [04:26<17:33,  3.66s/it]

[READY] normal075 완료 (74/362) | status=success | patch=34442 | 이번 환자: 3초 | 예상 남은 시간: 17분 17초

Build training-ready dataset:  21%|######6                         | 75/362 [04:30<17:48,  3.72s/it]

[READY] normal076 완료 (75/362) | status=success | patch=34170 | 이번 환자: 3초 | 예상 남은 시간: 17분 14초

Build training-ready dataset:  21%|######7                         | 76/362 [04:35<19:01,  3.99s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.105756658031515062000744821260 완료 (76/362) | status=success | patch=33299 | 이번 환자: 4초 | 예상 남은 시간: 17분 14초

Build training-ready dataset:  21%|######8                         | 77/362 [04:39<20:00,  4.21s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.122763913896761494371822656720 완료 (77/362) | status=success | patch=37363 | 이번 환자: 4초 | 예상 남은 시간: 17분 15초

Build training-ready dataset:  22%|######8                         | 78/362 [04:45<21:32,  4.55s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.126121460017257137098781143514 완료 (78/362) | status=success | patch=45521 | 이번 환자: 5초 | 예상 남은 시간: 17분 17초

Build training-ready dataset:  22%|######9                         | 79/362 [04:48<20:28,  4.34s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.139713436241461669335487719526 완료 (79/362) | status=success | patch=28537 | 이번 환자: 3초 | 예상 남은 시간: 17분 15초

Build training-ready dataset:  22%|#######                         | 80/362 [04:52<19:56,  4.24s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.144438612068946916340281098509 완료 (80/362) | status=success | patch=31543 | 이번 환자: 3초 | 예상 남은 시간: 17분 12초

Build training-ready dataset:  22%|#######1                        | 81/362 [04:59<22:55,  4.89s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.146429221666426688999739595820 완료 (81/362) | status=success | patch=51215 | 이번 환자: 6초 | 예상 남은 시간: 17분 18초

Build training-ready dataset:  23%|#######2                        | 82/362 [05:04<22:50,  4.89s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.194465340552956447447896167830 완료 (82/362) | status=success | patch=38146 | 이번 환자: 4초 | 예상 남은 시간: 17분 18초

Build training-ready dataset:  23%|#######3                        | 83/362 [05:09<23:13,  5.00s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.210837812047373739447725050963 완료 (83/362) | status=success | patch=43348 | 이번 환자: 5초 | 예상 남은 시간: 17분 20초

Build training-ready dataset:  23%|#######4                        | 84/362 [05:13<21:09,  4.57s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.231645134739451754302647733304 완료 (84/362) | status=success | patch=25515 | 이번 환자: 3초 | 예상 남은 시간: 17분 16초

Build training-ready dataset:  23%|#######5                        | 85/362 [05:17<21:02,  4.56s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.238522526736091851696274044574 완료 (85/362) | status=success | patch=33227 | 이번 환자: 4초 | 예상 남은 시간: 17분 14초

Build training-ready dataset:  24%|#######6                        | 86/362 [05:20<19:07,  4.16s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.250438451287314206124484591986 완료 (86/362) | status=success | patch=22590 | 이번 환자: 3초 | 예상 남은 시간: 17분 9초

Build training-ready dataset:  24%|#######6                        | 87/362 [05:25<19:29,  4.25s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.269689294231892620436462818860 완료 (87/362) | status=success | patch=34818 | 이번 환자: 4초 | 예상 남은 시간: 17분 8초

Build training-ready dataset:  24%|#######7                        | 88/362 [05:28<17:36,  3.85s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.278660284797073139172446973682 완료 (88/362) | status=success | patch=20207 | 이번 환자: 2초 | 예상 남은 시간: 17분 1초

Build training-ready dataset:  25%|#######8                        | 89/362 [05:32<18:45,  4.12s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.280972147860943609388015648430 완료 (89/362) | status=success | patch=39017 | 이번 환자: 4초 | 예상 남은 시간: 17분 1초

Build training-ready dataset:  25%|#######9                        | 90/362 [05:36<18:11,  4.01s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.302134342469412607966016057827 완료 (90/362) | status=success | patch=26516 | 이번 환자: 3초 | 예상 남은 시간: 16분 57초

Build training-ready dataset:  25%|########                        | 91/362 [05:41<19:03,  4.22s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.310626494937915759224334597176 완료 (91/362) | status=success | patch=38364 | 이번 환자: 4초 | 예상 남은 시간: 16분 56초

Build training-ready dataset:  25%|########1                       | 92/362 [05:44<17:37,  3.92s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.311981398931043315779172047718 완료 (92/362) | status=success | patch=20835 | 이번 환자: 3초 | 예상 남은 시간: 16분 51초

Build training-ready dataset:  26%|########2                       | 93/362 [05:51<21:04,  4.70s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.332453873575389860371315979768 완료 (93/362) | status=success | patch=58698 | 이번 환자: 6초 | 예상 남은 시간: 16분 55초

Build training-ready dataset:  26%|########3                       | 94/362 [05:54<18:44,  4.19s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.397062004302272014259317520874 완료 (94/362) | status=success | patch=17441 | 이번 환자: 2초 | 예상 남은 시간: 16분 49초

Build training-ready dataset:  26%|########3                       | 95/362 [05:56<16:05,  3.62s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.564534197011295112247542153557 완료 (95/362) | status=success | patch=8730 | 이번 환자: 2초 | 예상 남은 시간: 16분 41초

Build training-ready dataset:  27%|########4                       | 96/362 [05:59<15:40,  3.54s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.657775098760536289051744981056 완료 (96/362) | status=success | patch=23554 | 이번 환자: 3초 | 예상 남은 시간: 16분 36초

Build training-ready dataset:  27%|########5                       | 97/362 [06:03<16:26,  3.72s/it]

[READY] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.975254950136384517744116790879 완료 (97/362) | status=success | patch=32514 | 이번 환자: 4초 | 예상 남은 시간: 16분 34초

Build training-ready dataset:  27%|########6                       | 98/362 [06:10<20:03,  4.56s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.100684836163890911914061745866 완료 (98/362) | status=success | patch=58144 | 이번 환자: 6초 | 예상 남은 시간: 16분 37초

Build training-ready dataset:  27%|########7                       | 99/362 [06:12<16:44,  3.82s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.111017101339429664883879536171 완료 (99/362) | status=success | patch=12237 | 이번 환자: 2초 | 예상 남은 시간: 16분 29초

Build training-ready dataset:  28%|########5                      | 100/362 [06:15<15:45,  3.61s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.113697708991260454310623082679 완료 (100/362) | status=success | patch=19536 | 이번 환자: 3초 | 예상 남은 시간: 16분 24초

Build training-ready dataset:  28%|########6                      | 101/362 [06:20<17:42,  4.07s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.139595277234735528205899724196 완료 (101/362) | status=success | patch=40347 | 이번 환자: 5초 | 예상 남은 시간: 16분 24초

Build training-ready dataset:  28%|########7                      | 102/362 [06:23<15:48,  3.65s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.140527383975300992150799777603 완료 (102/362) | status=success | patch=16750 | 이번 환자: 2초 | 예상 남은 시간: 16분 17초

Build training-ready dataset:  28%|########8                      | 103/362 [06:27<16:14,  3.76s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.144943344795414353192059796098 완료 (103/362) | status=success | patch=29652 | 이번 환자: 3초 | 예상 남은 시간: 16분 14초

Build training-ready dataset:  29%|########9                      | 104/362 [06:32<17:25,  4.05s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.146603910507557786636779705509 완료 (104/362) | status=success | patch=37255 | 이번 환자: 4초 | 예상 남은 시간: 16분 13초

Build training-ready dataset:  29%|########9                      | 105/362 [06:38<20:16,  4.73s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.152684536713461901635595118048 완료 (105/362) | status=success | patch=54976 | 이번 환자: 6초 | 예상 남은 시간: 16분 15초

Build training-ready dataset:  29%|#########                      | 106/362 [06:41<17:59,  4.22s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.161002239822118346732951898613 완료 (106/362) | status=success | patch=19194 | 이번 환자: 2초 | 예상 남은 시간: 16분 9초

Build training-ready dataset:  30%|#########1                     | 107/362 [06:45<17:13,  4.05s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.161073793312426102774780216551 완료 (107/362) | status=success | patch=25978 | 이번 환자: 3초 | 예상 남은 시간: 16분 5초

Build training-ready dataset:  30%|#########2                     | 108/362 [06:50<18:37,  4.40s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.162207236104936931957809623059 완료 (108/362) | status=success | patch=44929 | 이번 환자: 5초 | 예상 남은 시간: 16분 5초

Build training-ready dataset:  30%|#########3                     | 109/362 [06:55<19:24,  4.60s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.171919524048654494439256263785 완료 (109/362) | status=success | patch=42244 | 이번 환자: 5초 | 예상 남은 시간: 16분 4초

Build training-ready dataset:  30%|#########4                     | 110/362 [06:59<18:58,  4.52s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.184019785706727365023450012318 완료 (110/362) | status=success | patch=36381 | 이번 환자: 4초 | 예상 남은 시간: 16분 1초

Build training-ready dataset:  31%|#########5                     | 111/362 [07:05<20:07,  4.81s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.186021279664749879526003668137 완료 (111/362) | status=success | patch=44675 | 이번 환자: 5초 | 예상 남은 시간: 16분 1초

Build training-ready dataset:  31%|#########5                     | 112/362 [07:09<19:43,  4.73s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.193408384740507320589857096592 완료 (112/362) | status=success | patch=36620 | 이번 환자: 4초 | 예상 남은 시간: 15분 59초

Build training-ready dataset:  31%|#########6                     | 113/362 [07:13<18:41,  4.50s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.197987940182806628828566429132 완료 (113/362) | status=success | patch=29595 | 이번 환자: 3초 | 예상 남은 시간: 15분 56초

Build training-ready dataset:  31%|#########7                     | 114/362 [07:17<18:05,  4.38s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.200558451375970945040979397866 완료 (114/362) | status=success | patch=31636 | 이번 환자: 4초 | 예상 남은 시간: 15분 52초

Build training-ready dataset:  32%|#########8                     | 115/362 [07:22<18:22,  4.46s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.216652640878960522552873394709 완료 (115/362) | status=success | patch=42122 | 이번 환자: 4초 | 예상 남은 시간: 15분 50초

Build training-ready dataset:  32%|#########9                     | 116/362 [07:26<17:53,  4.36s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.222087811960706096424718056430 완료 (116/362) | status=success | patch=33302 | 이번 환자: 4초 | 예상 남은 시간: 15분 47초

Build training-ready dataset:  32%|##########                     | 117/362 [07:32<19:29,  4.77s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.231834776365874788440767645596 완료 (117/362) | status=success | patch=44522 | 이번 환자: 5초 | 예상 남은 시간: 15분 47초

Build training-ready dataset:  33%|##########1                    | 118/362 [07:36<18:39,  4.59s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.259018373683540453277752706262 완료 (118/362) | status=success | patch=31635 | 이번 환자: 4초 | 예상 남은 시간: 15분 44초

Build training-ready dataset:  33%|##########1                    | 119/362 [07:42<19:57,  4.93s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.286647622786041008124419915089 완료 (119/362) | status=success | patch=44845 | 이번 환자: 5초 | 예상 남은 시간: 15분 44초

Build training-ready dataset:  33%|##########2                    | 120/362 [07:47<19:45,  4.90s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.300271604576987336866436407488 완료 (120/362) | status=success | patch=40075 | 이번 환자: 4초 | 예상 남은 시간: 15분 42초

Build training-ready dataset:  33%|##########3                    | 121/362 [07:51<18:38,  4.64s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.308183340111270052562662456038 완료 (121/362) | status=success | patch=31709 | 이번 환자: 4초 | 예상 남은 시간: 15분 38초

Build training-ready dataset:  34%|##########4                    | 122/362 [07:55<18:29,  4.62s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.331211682377519763144559212009 완료 (122/362) | status=success | patch=35523 | 이번 환자: 4초 | 예상 남은 시간: 15분 35초

Build training-ready dataset:  34%|##########5                    | 123/362 [07:59<17:07,  4.30s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.335866409407244673864352309754 완료 (123/362) | status=success | patch=24458 | 이번 환자: 3초 | 예상 남은 시간: 15분 31초

Build training-ready dataset:  34%|##########6                    | 124/362 [08:03<17:16,  4.35s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.802595762867498341201607992711 완료 (124/362) | status=success | patch=28144 | 이번 환자: 4초 | 예상 남은 시간: 15분 28초

Build training-ready dataset:  35%|##########7                    | 125/362 [08:08<17:06,  4.33s/it]

[READY] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.888291896309937415860209787179 완료 (125/362) | status=success | patch=32427 | 이번 환자: 4초 | 예상 남은 시간: 15분 25초

Build training-ready dataset:  35%|##########7                    | 126/362 [08:12<16:47,  4.27s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.102133688497886810253331438797 완료 (126/362) | status=success | patch=29156 | 이번 환자: 4초 | 예상 남은 시간: 15분 21초

Build training-ready dataset:  35%|##########8                    | 127/362 [08:15<15:46,  4.03s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.113586291551175790743673929831 완료 (127/362) | status=success | patch=26172 | 이번 환자: 3초 | 예상 남은 시간: 15분 17초

Build training-ready dataset:  35%|##########9                    | 128/362 [08:22<18:29,  4.74s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.116492508532884962903000261147 완료 (128/362) | status=success | patch=53049 | 이번 환자: 6초 | 예상 남은 시간: 15분 17초

Build training-ready dataset:  36%|###########                    | 129/362 [08:25<16:27,  4.24s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.117383608379722740629083782428 완료 (129/362) | status=success | patch=19926 | 이번 환자: 3초 | 예상 남은 시간: 15분 12초

Build training-ready dataset:  36%|###########1                   | 130/362 [08:30<17:49,  4.61s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.139444426690868429919252698606 완료 (130/362) | status=success | patch=44459 | 이번 환자: 5초 | 예상 남은 시간: 15분 11초

Build training-ready dataset:  36%|###########2                   | 131/362 [08:35<17:26,  4.53s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.156322145453198768801776721493 완료 (131/362) | status=success | patch=34459 | 이번 환자: 4초 | 예상 남은 시간: 15분 8초

Build training-ready dataset:  36%|###########3                   | 132/362 [08:39<17:33,  4.58s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.156579001330474859527530187095 완료 (132/362) | status=success | patch=36781 | 이번 환자: 4초 | 예상 남은 시간: 15분 5초

Build training-ready dataset:  37%|###########3                   | 133/362 [08:44<18:10,  4.76s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.159521777966998275980367008904 완료 (133/362) | status=success | patch=41675 | 이번 환자: 5초 | 예상 남은 시간: 15분 3초

Build training-ready dataset:  37%|###########4                   | 134/362 [08:48<16:56,  4.46s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.172845185165807139298420209778 완료 (134/362) | status=success | patch=23156 | 이번 환자: 3초 | 예상 남은 시간: 14분 59초

Build training-ready dataset:  37%|###########5                   | 135/362 [08:52<15:43,  4.16s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.176362912420491262783064585333 완료 (135/362) | status=success | patch=22046 | 이번 환자: 3초 | 예상 남은 시간: 14분 54초

Build training-ready dataset:  38%|###########6                   | 136/362 [08:57<16:35,  4.40s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.191301539558980174217770205256 완료 (136/362) | status=success | patch=40194 | 이번 환자: 4초 | 예상 남은 시간: 14분 52초

Build training-ready dataset:  38%|###########7                   | 137/362 [09:01<16:49,  4.49s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.213022585153512920098588556742 완료 (137/362) | status=success | patch=37799 | 이번 환자: 4초 | 예상 남은 시간: 14분 49초

Build training-ready dataset:  38%|###########8                   | 138/362 [09:04<14:52,  3.98s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.216526102138308489357443843021 완료 (138/362) | status=success | patch=18653 | 이번 환자: 2초 | 예상 남은 시간: 14분 43초

Build training-ready dataset:  38%|###########9                   | 139/362 [09:08<14:41,  3.95s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.220205300714852483483213840572 완료 (139/362) | status=success | patch=27045 | 이번 환자: 3초 | 예상 남은 시간: 14분 39초

Build training-ready dataset:  39%|###########9                   | 140/362 [09:14<17:21,  4.69s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.221945191226273284587353530424 완료 (140/362) | status=success | patch=53582 | 이번 환자: 6초 | 예상 남은 시간: 14분 39초

Build training-ready dataset:  39%|############                   | 141/362 [09:18<16:28,  4.47s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.223098610241551815995595311693 완료 (141/362) | status=success | patch=28111 | 이번 환자: 3초 | 예상 남은 시간: 14분 35초

Build training-ready dataset:  39%|############1                  | 142/362 [09:24<17:25,  4.75s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.230078008964732806419498631442 완료 (142/362) | status=success | patch=48442 | 이번 환자: 5초 | 예상 남은 시간: 14분 34초

Build training-ready dataset:  40%|############2                  | 143/362 [09:28<16:52,  4.63s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.253283426904813468115158375647 완료 (143/362) | status=success | patch=34257 | 이번 환자: 4초 | 예상 남은 시간: 14분 30초

Build training-ready dataset:  40%|############3                  | 144/362 [09:32<15:45,  4.34s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.265133389948279331857097127422 완료 (144/362) | status=success | patch=27843 | 이번 환자: 3초 | 예상 남은 시간: 14분 26초

Build training-ready dataset:  40%|############4                  | 145/362 [09:35<14:37,  4.05s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.272259794130271010519952623746 완료 (145/362) | status=success | patch=22907 | 이번 환자: 3초 | 예상 남은 시간: 14분 21초

Build training-ready dataset:  40%|############5                  | 146/362 [09:40<15:09,  4.21s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.281967919138248195763602360723 완료 (146/362) | status=success | patch=30210 | 이번 환자: 4초 | 예상 남은 시간: 14분 18초

Build training-ready dataset:  41%|############5                  | 147/362 [09:44<15:38,  4.36s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.296863826932699509516219450076 완료 (147/362) | status=success | patch=32809 | 이번 환자: 4초 | 예상 남은 시간: 14분 15초

Build training-ready dataset:  41%|############6                  | 148/362 [09:49<15:35,  4.37s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.306788423710427765311352901943 완료 (148/362) | status=success | patch=32604 | 이번 환자: 4초 | 예상 남은 시간: 14분 12초

Build training-ready dataset:  41%|############7                  | 149/362 [09:55<17:33,  4.95s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.311236942972970815890902714604 완료 (149/362) | status=success | patch=51859 | 이번 환자: 6초 | 예상 남은 시간: 14분 11초

Build training-ready dataset:  41%|############8                  | 150/362 [09:59<16:13,  4.59s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.325580698241281352835338693869 완료 (150/362) | status=success | patch=28349 | 이번 환자: 3초 | 예상 남은 시간: 14분 7초

Build training-ready dataset:  42%|############9                  | 151/362 [10:01<14:01,  3.99s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.470912100568074901744259213968 완료 (151/362) | status=success | patch=12549 | 이번 환자: 2초 | 예상 남은 시간: 14분 1초

Build training-ready dataset:  42%|#############                  | 152/362 [10:05<13:52,  3.96s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.504324996863016748259361352296 완료 (152/362) | status=success | patch=29706 | 이번 환자: 3초 | 예상 남은 시간: 13분 56초

Build training-ready dataset:  42%|#############1                 | 153/362 [10:10<14:03,  4.03s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.669518152156802508672627785405 완료 (153/362) | status=success | patch=28155 | 이번 환자: 4초 | 예상 남은 시간: 13분 53초

Build training-ready dataset:  43%|#############1                 | 154/362 [10:12<12:52,  3.71s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.707218743153927597786179232739 완료 (154/362) | status=success | patch=18863 | 이번 환자: 2초 | 예상 남은 시간: 13분 47초

Build training-ready dataset:  43%|#############2                 | 155/362 [10:15<12:00,  3.48s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.743969234977916254223533321294 완료 (155/362) | status=success | patch=21761 | 이번 환자: 2초 | 예상 남은 시간: 13분 42초

Build training-ready dataset:  43%|#############3                 | 156/362 [10:20<13:28,  3.93s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.776429308535398795601496131524 완료 (156/362) | status=success | patch=39692 | 이번 환자: 4초 | 예상 남은 시간: 13분 39초

Build training-ready dataset:  43%|#############4                 | 157/362 [10:22<11:14,  3.29s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.803808126682275425758092691689 완료 (157/362) | status=success | patch=7594 | 이번 환자: 1초 | 예상 남은 시간: 13분 33초

Build training-ready dataset:  44%|#############5                 | 158/362 [10:28<13:17,  3.91s/it]

[READY] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.885292267869246639232975687131 완료 (158/362) | status=success | patch=39459 | 이번 환자: 5초 | 예상 남은 시간: 13분 30초

Build training-ready dataset:  44%|#############6                 | 159/362 [10:32<13:50,  4.09s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.100620385482151095585000946543 완료 (159/362) | status=success | patch=34643 | 이번 환자: 4초 | 예상 남은 시간: 13분 27초

Build training-ready dataset:  44%|#############7                 | 160/362 [10:37<14:17,  4.25s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.125356649712550043958727288500 완료 (160/362) | status=success | patch=35438 | 이번 환자: 4초 | 예상 남은 시간: 13분 24초

Build training-ready dataset:  44%|#############7                 | 161/362 [10:42<14:57,  4.46s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.145474881373882284343459153872 완료 (161/362) | status=success | patch=40924 | 이번 환자: 4초 | 예상 남은 시간: 13분 21초

Build training-ready dataset:  45%|#############8                 | 162/362 [10:47<15:35,  4.68s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.160216916075817913953530562493 완료 (162/362) | status=success | patch=38817 | 이번 환자: 5초 | 예상 남은 시간: 13분 19초

Build training-ready dataset:  45%|#############9                 | 163/362 [10:50<13:56,  4.20s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.177985905159808659201278495182 완료 (163/362) | status=success | patch=21857 | 이번 환자: 3초 | 예상 남은 시간: 13분 14초

Build training-ready dataset:  45%|##############                 | 164/362 [10:55<14:54,  4.52s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.191617711875409989053242965150 완료 (164/362) | status=success | patch=42690 | 이번 환자: 5초 | 예상 남은 시간: 13분 11초

Build training-ready dataset:  46%|##############1                | 165/362 [11:00<15:15,  4.65s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.199069398344356765037879821616 완료 (165/362) | status=success | patch=34960 | 이번 환자: 4초 | 예상 남은 시간: 13분 8초

Build training-ready dataset:  46%|##############2                | 166/362 [11:05<15:03,  4.61s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.202476538079060560282495099956 완료 (166/362) | status=success | patch=34731 | 이번 환자: 4초 | 예상 남은 시간: 13분 5초

Build training-ready dataset:  46%|##############3                | 167/362 [11:09<14:45,  4.54s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.203741923654363010377298352671 완료 (167/362) | status=success | patch=35411 | 이번 환자: 4초 | 예상 남은 시간: 13분 1초

Build training-ready dataset:  46%|##############3                | 168/362 [11:13<14:02,  4.34s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.205852555362702089950453265567 완료 (168/362) | status=success | patch=29948 | 이번 환자: 3초 | 예상 남은 시간: 12분 57초

Build training-ready dataset:  47%|##############4                | 169/362 [11:15<11:54,  3.70s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.210426531621179400035178209430 완료 (169/362) | status=success | patch=12114 | 이번 환자: 2초 | 예상 남은 시간: 12분 51초

Build training-ready dataset:  47%|##############5                | 170/362 [11:22<14:32,  4.54s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.215086589927307766627151367533 완료 (170/362) | status=success | patch=53387 | 이번 환자: 6초 | 예상 남은 시간: 12분 50초

Build training-ready dataset:  47%|##############6                | 171/362 [11:26<13:53,  4.37s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.229664630348267553620068691756 완료 (171/362) | status=success | patch=30834 | 이번 환자: 3초 | 예상 남은 시간: 12분 46초

Build training-ready dataset:  48%|##############7                | 172/362 [11:28<11:49,  3.73s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.264090899378396711987322794314 완료 (172/362) | status=success | patch=12412 | 이번 환자: 2초 | 예상 남은 시간: 12분 40초

Build training-ready dataset:  48%|##############8                | 173/362 [11:33<13:19,  4.23s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.268589491017129166376960414534 완료 (173/362) | status=success | patch=44144 | 이번 환자: 5초 | 예상 남은 시간: 12분 37초

Build training-ready dataset:  48%|##############9                | 174/362 [11:36<11:34,  3.69s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.268838889380981659524993261082 완료 (174/362) | status=success | patch=14893 | 이번 환자: 2초 | 예상 남은 시간: 12분 32초

Build training-ready dataset:  48%|##############9                | 175/362 [11:40<12:23,  3.98s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.314519596680450457855054746285 완료 (175/362) | status=success | patch=36077 | 이번 환자: 4초 | 예상 남은 시간: 12분 28초

Build training-ready dataset:  49%|###############                | 176/362 [11:45<12:34,  4.06s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.319009811633846643966578282371 완료 (176/362) | status=success | patch=31615 | 이번 환자: 4초 | 예상 남은 시간: 12분 25초

Build training-ready dataset:  49%|###############1               | 177/362 [11:50<13:38,  4.43s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.334022941831199910030220864961 완료 (177/362) | status=success | patch=44028 | 이번 환자: 5초 | 예상 남은 시간: 12분 22초

Build training-ready dataset:  49%|###############2               | 178/362 [11:52<11:47,  3.85s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.398955972049286139436103068984 완료 (178/362) | status=success | patch=17488 | 이번 환자: 2초 | 예상 남은 시간: 12분 16초

Build training-ready dataset:  49%|###############3               | 179/362 [11:57<12:14,  4.01s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.619372068417051974713149104919 완료 (179/362) | status=success | patch=32920 | 이번 환자: 4초 | 예상 남은 시간: 12분 13초

Build training-ready dataset:  50%|###############4               | 180/362 [12:02<13:05,  4.31s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.710845873679853791427022019413 완료 (180/362) | status=success | patch=39585 | 이번 환자: 4초 | 예상 남은 시간: 12분 10초

Build training-ready dataset:  50%|###############5               | 181/362 [12:06<12:42,  4.21s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.965620538050807352935663552285 완료 (181/362) | status=success | patch=30430 | 이번 환자: 3초 | 예상 남은 시간: 12분 6초

Build training-ready dataset:  50%|###############5               | 182/362 [12:10<12:43,  4.24s/it]

[READY] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.969607480572818589276327766720 완료 (182/362) | status=success | patch=33059 | 이번 환자: 4초 | 예상 남은 시간: 12분 2초

Build training-ready dataset:  51%|###############6               | 183/362 [12:13<11:54,  3.99s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.100530488926682752765845212286 완료 (183/362) | status=success | patch=24815 | 이번 환자: 3초 | 예상 남은 시간: 11분 57초

Build training-ready dataset:  51%|###############7               | 184/362 [12:16<10:40,  3.60s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.103115201714075993579787468219 완료 (184/362) | status=success | patch=15838 | 이번 환자: 2초 | 예상 남은 시간: 11분 52초

Build training-ready dataset:  51%|###############8               | 185/362 [12:18<09:22,  3.18s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.104780906131535625872840889059 완료 (185/362) | status=success | patch=12412 | 이번 환자: 2초 | 예상 남은 시간: 11분 46초

Build training-ready dataset:  51%|###############9               | 186/362 [12:24<11:37,  3.96s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.125067060506283419853742462394 완료 (186/362) | status=success | patch=49341 | 이번 환자: 5초 | 예상 남은 시간: 11분 44초

Build training-ready dataset:  52%|################               | 187/362 [12:29<11:58,  4.11s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.145283812746259413053188838096 완료 (187/362) | status=success | patch=30691 | 이번 환자: 4초 | 예상 남은 시간: 11분 40초

Build training-ready dataset:  52%|################               | 188/362 [12:34<12:54,  4.45s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.156821379677057223126714881626 완료 (188/362) | status=success | patch=43121 | 이번 환자: 5초 | 예상 남은 시간: 11분 38초

Build training-ready dataset:  52%|################1              | 189/362 [12:37<12:02,  4.17s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.163931625580639955914619627409 완료 (189/362) | status=success | patch=26164 | 이번 환자: 3초 | 예상 남은 시간: 11분 33초

Build training-ready dataset:  52%|################2              | 190/362 [12:41<11:39,  4.07s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.200837896655745926888305239398 완료 (190/362) | status=success | patch=27341 | 이번 환자: 3초 | 예상 남은 시간: 11분 29초

Build training-ready dataset:  53%|################3              | 191/362 [12:46<11:58,  4.20s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.203179378754043776171267611064 완료 (191/362) | status=success | patch=36767 | 이번 환자: 4초 | 예상 남은 시간: 11분 25초

Build training-ready dataset:  53%|################4              | 192/362 [12:48<10:31,  3.71s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.209269973797560820442292189762 완료 (192/362) | status=success | patch=16865 | 이번 환자: 2초 | 예상 남은 시간: 11분 20초

Build training-ready dataset:  53%|################5              | 193/362 [12:55<13:15,  4.71s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.211071908915618528829547301883 완료 (193/362) | status=success | patch=55697 | 이번 환자: 6초 | 예상 남은 시간: 11분 19초

Build training-ready dataset:  54%|################6              | 194/362 [13:00<13:29,  4.82s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.232011770495640253949434620907 완료 (194/362) | status=success | patch=40034 | 이번 환자: 5초 | 예상 남은 시간: 11분 16초

Build training-ready dataset:  54%|################6              | 195/362 [13:05<13:26,  4.83s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.232058316950007760548968840196 완료 (195/362) | status=success | patch=31047 | 이번 환자: 4초 | 예상 남은 시간: 11분 12초

Build training-ready dataset:  54%|################7              | 196/362 [13:10<13:32,  4.90s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.261678072503577216586082745513 완료 (196/362) | status=success | patch=40632 | 이번 환자: 5초 | 예상 남은 시간: 11분 9초

Build training-ready dataset:  54%|################8              | 197/362 [13:15<13:19,  4.85s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.303865116731361029078599241306 완료 (197/362) | status=success | patch=38043 | 이번 환자: 4초 | 예상 남은 시간: 11분 6초

Build training-ready dataset:  55%|################9              | 198/362 [13:19<12:47,  4.68s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.304676828064484590312919543151 완료 (198/362) | status=success | patch=32914 | 이번 환자: 4초 | 예상 남은 시간: 11분 2초

Build training-ready dataset:  55%|#################              | 199/362 [13:23<12:03,  4.44s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.316393351033132458296975008261 완료 (199/362) | status=success | patch=23719 | 이번 환자: 3초 | 예상 남은 시간: 10분 58초

Build training-ready dataset:  55%|#################1             | 200/362 [13:27<11:18,  4.19s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.320967206808467952819309001585 완료 (200/362) | status=success | patch=25653 | 이번 환자: 3초 | 예상 남은 시간: 10분 53초

Build training-ready dataset:  56%|#################2             | 201/362 [13:32<11:59,  4.47s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.329326052298830421573852261436 완료 (201/362) | status=success | patch=38529 | 이번 환자: 5초 | 예상 남은 시간: 10분 50초

Build training-ready dataset:  56%|#################2             | 202/362 [13:35<11:03,  4.15s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.330425234131526435132846006585 완료 (202/362) | status=success | patch=22331 | 이번 환자: 3초 | 예상 남은 시간: 10분 46초

Build training-ready dataset:  56%|#################3             | 203/362 [13:39<10:48,  4.08s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.333319057944372470283038483725 완료 (203/362) | status=success | patch=27649 | 이번 환자: 3초 | 예상 남은 시간: 10분 41초

Build training-ready dataset:  56%|#################4             | 204/362 [13:44<11:06,  4.22s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.385151742584074711135621089321 완료 (204/362) | status=success | patch=35041 | 이번 환자: 4초 | 예상 남은 시간: 10분 38초

Build training-ready dataset:  57%|#################5             | 205/362 [13:49<11:34,  4.43s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.390009458146468860187238398197 완료 (205/362) | status=success | patch=38736 | 이번 환자: 4초 | 예상 남은 시간: 10분 34초

Build training-ready dataset:  57%|#################6             | 206/362 [13:56<14:01,  5.39s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.428038562098395445838061018440 완료 (206/362) | status=success | patch=66124 | 이번 환자: 7초 | 예상 남은 시간: 10분 33초

Build training-ready dataset:  57%|#################7             | 207/362 [14:02<14:02,  5.43s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.449254134266555649028108149727 완료 (207/362) | status=success | patch=46764 | 이번 환자: 5초 | 예상 남은 시간: 10분 30초

Build training-ready dataset:  57%|#################8             | 208/362 [14:06<12:49,  5.00s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.811825890493256320617655474043 완료 (208/362) | status=success | patch=28587 | 이번 환자: 3초 | 예상 남은 시간: 10분 26초

Build training-ready dataset:  58%|#################8             | 209/362 [14:10<11:59,  4.70s/it]

[READY] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.885168397833922082085837240429 완료 (209/362) | status=success | patch=29284 | 이번 환자: 3초 | 예상 남은 시간: 10분 22초

Build training-ready dataset:  58%|#################9             | 210/362 [14:13<10:38,  4.20s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.100332161840553388986847034053 완료 (210/362) | status=success | patch=21302 | 이번 환자: 2초 | 예상 남은 시간: 10분 17초

Build training-ready dataset:  58%|##################             | 211/362 [14:16<09:41,  3.85s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.101228986346984399347858840086 완료 (211/362) | status=success | patch=20160 | 이번 환자: 2초 | 예상 남은 시간: 10분 12초

Build training-ready dataset:  59%|##################1            | 212/362 [14:21<10:34,  4.23s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.106419850406056634877579573537 완료 (212/362) | status=success | patch=37128 | 이번 환자: 5초 | 예상 남은 시간: 10분 9초

Build training-ready dataset:  59%|##################2            | 213/362 [14:27<12:05,  4.87s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.111780708132595903430640048766 완료 (213/362) | status=success | patch=50353 | 이번 환자: 6초 | 예상 남은 시간: 10분 7초

Build training-ready dataset:  59%|##################3            | 214/362 [14:33<12:17,  4.98s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.120196332569034738680965284519 완료 (214/362) | status=success | patch=38685 | 이번 환자: 5초 | 예상 남은 시간: 10분 3초

Build training-ready dataset:  59%|##################4            | 215/362 [14:37<11:41,  4.77s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.133132722052053001903031735878 완료 (215/362) | status=success | patch=34569 | 이번 환자: 4초 | 예상 남은 시간: 9분 59초

Build training-ready dataset:  60%|##################4            | 216/362 [14:42<11:32,  4.74s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.134638281277099121660656324702 완료 (216/362) | status=success | patch=37754 | 이번 환자: 4초 | 예상 남은 시간: 9분 56초

Build training-ready dataset:  60%|##################5            | 217/362 [14:44<09:53,  4.09s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.138894439026794145866157853158 완료 (217/362) | status=success | patch=15415 | 이번 환자: 2초 | 예상 남은 시간: 9분 51초

Build training-ready dataset:  60%|##################6            | 218/362 [14:48<09:48,  4.08s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.143410010885830403003179808334 완료 (218/362) | status=success | patch=31991 | 이번 환자: 4초 | 예상 남은 시간: 9분 47초

Build training-ready dataset:  60%|##################7            | 219/362 [14:52<09:14,  3.88s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.143782059748737055784173697516 완료 (219/362) | status=success | patch=20661 | 이번 환자: 3초 | 예상 남은 시간: 9분 42초

Build training-ready dataset:  61%|##################8            | 220/362 [14:56<09:46,  4.13s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.152706273988004688708784163325 완료 (220/362) | status=success | patch=35161 | 이번 환자: 4초 | 예상 남은 시간: 9분 38초

Build training-ready dataset:  61%|##################9            | 221/362 [15:03<11:28,  4.88s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.174935793360491516757154875981 완료 (221/362) | status=success | patch=55384 | 이번 환자: 6초 | 예상 남은 시간: 9분 36초

Build training-ready dataset:  61%|###################            | 222/362 [15:07<10:55,  4.68s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.183056151780567460322586876100 완료 (222/362) | status=success | patch=35352 | 이번 환자: 4초 | 예상 남은 시간: 9분 32초

Build training-ready dataset:  62%|###################            | 223/362 [15:11<09:56,  4.29s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.188484197846284733942365679565 완료 (223/362) | status=success | patch=23625 | 이번 환자: 3초 | 예상 남은 시간: 9분 27초

Build training-ready dataset:  62%|###################1           | 224/362 [15:15<09:40,  4.20s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.190144948425835566841437565646 완료 (224/362) | status=success | patch=29789 | 이번 환자: 3초 | 예상 남은 시간: 9분 23초

Build training-ready dataset:  62%|###################2           | 225/362 [15:18<09:19,  4.08s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.201890795870532056891161597218 완료 (225/362) | status=success | patch=28560 | 이번 환자: 3초 | 예상 남은 시간: 9분 19초

Build training-ready dataset:  62%|###################3           | 226/362 [15:22<08:54,  3.93s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.205615524269596458818376243313 완료 (226/362) | status=success | patch=27835 | 이번 환자: 3초 | 예상 남은 시간: 9분 15초

Build training-ready dataset:  63%|###################4           | 227/362 [15:26<09:08,  4.06s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.219281726101239572270900838145 완료 (227/362) | status=success | patch=37526 | 이번 환자: 4초 | 예상 남은 시간: 9분 11초

Build training-ready dataset:  63%|###################5           | 228/362 [15:32<09:59,  4.48s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.229171189693734694696158152904 완료 (228/362) | status=success | patch=40879 | 이번 환자: 5초 | 예상 남은 시간: 9분 7초

Build training-ready dataset:  63%|###################6           | 229/362 [15:34<08:27,  3.82s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.234400932423244218697302970157 완료 (229/362) | status=success | patch=11965 | 이번 환자: 2초 | 예상 남은 시간: 9분 2초

Build training-ready dataset:  64%|###################6           | 230/362 [15:37<07:42,  3.50s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.238042459915048190592571019348 완료 (230/362) | status=success | patch=12703 | 이번 환자: 2초 | 예상 남은 시간: 8분 57초

Build training-ready dataset:  64%|###################7           | 231/362 [15:41<08:00,  3.67s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.245349763807614756148761326488 완료 (231/362) | status=success | patch=28033 | 이번 환자: 4초 | 예상 남은 시간: 8분 53초

Build training-ready dataset:  64%|###################8           | 232/362 [15:45<08:28,  3.91s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.246589849815292078281051154201 완료 (232/362) | status=success | patch=36017 | 이번 환자: 4초 | 예상 남은 시간: 8분 49초

Build training-ready dataset:  64%|###################9           | 233/362 [15:50<08:46,  4.08s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.285926554490515269336267972830 완료 (233/362) | status=success | patch=35084 | 이번 환자: 4초 | 예상 남은 시간: 8분 46초

Build training-ready dataset:  65%|####################           | 234/362 [15:54<09:00,  4.22s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.309955814083231537823157605135 완료 (234/362) | status=success | patch=35503 | 이번 환자: 4초 | 예상 남은 시간: 8분 42초

Build training-ready dataset:  65%|####################1          | 235/362 [15:59<09:27,  4.47s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.328695385904874796172316226975 완료 (235/362) | status=success | patch=44357 | 이번 환자: 4초 | 예상 남은 시간: 8분 38초

Build training-ready dataset:  65%|####################2          | 236/362 [16:05<10:08,  4.83s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.334184846571549530235084187602 완료 (236/362) | status=success | patch=42488 | 이번 환자: 5초 | 예상 남은 시간: 8분 35초

Build training-ready dataset:  65%|####################2          | 237/362 [16:07<08:24,  4.03s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.397202838387416555106806022938 완료 (237/362) | status=success | patch=10307 | 이번 환자: 2초 | 예상 남은 시간: 8분 30초

Build training-ready dataset:  66%|####################3          | 238/362 [16:12<08:31,  4.13s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.553241901808946577644850294647 완료 (238/362) | status=success | patch=33363 | 이번 환자: 4초 | 예상 남은 시간: 8분 26초

Build training-ready dataset:  66%|####################4          | 239/362 [16:16<08:43,  4.26s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.596908385953413160131451426904 완료 (239/362) | status=success | patch=35699 | 이번 환자: 4초 | 예상 남은 시간: 8분 22초

Build training-ready dataset:  66%|####################5          | 240/362 [16:21<09:16,  4.56s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.745109871503276594185453478952 완료 (240/362) | status=success | patch=47187 | 이번 환자: 5초 | 예상 남은 시간: 8분 19초

Build training-ready dataset:  67%|####################6          | 241/362 [16:25<08:24,  4.17s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.842980983137518332429408284002 완료 (241/362) | status=success | patch=17183 | 이번 환자: 3초 | 예상 남은 시간: 8분 14초

Build training-ready dataset:  67%|####################7          | 242/362 [16:29<08:23,  4.19s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.910757789941076242457816491305 완료 (242/362) | status=success | patch=33758 | 이번 환자: 4초 | 예상 남은 시간: 8분 10초

Build training-ready dataset:  67%|####################8          | 243/362 [16:33<08:07,  4.10s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.980362852713685276785310240144 완료 (243/362) | status=success | patch=27824 | 이번 환자: 3초 | 예상 남은 시간: 8분 6초

Build training-ready dataset:  67%|####################8          | 244/362 [16:37<08:00,  4.07s/it]

[READY] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.986011151772797848993829243183 완료 (244/362) | status=success | patch=28800 | 이번 환자: 3초 | 예상 남은 시간: 8분 2초

Build training-ready dataset:  68%|####################9          | 245/362 [16:40<07:29,  3.85s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.120842785645314664964010792308 완료 (245/362) | status=success | patch=21696 | 이번 환자: 3초 | 예상 남은 시간: 7분 57초

Build training-ready dataset:  68%|#####################          | 246/362 [16:45<08:06,  4.19s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.136830368929967292376608088362 완료 (246/362) | status=success | patch=40984 | 이번 환자: 4초 | 예상 남은 시간: 7분 54초

Build training-ready dataset:  68%|#####################1         | 247/362 [16:49<08:06,  4.23s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.164790817284381538042494285101 완료 (247/362) | status=success | patch=32327 | 이번 환자: 4초 | 예상 남은 시간: 7분 50초

Build training-ready dataset:  69%|#####################2         | 248/362 [16:54<08:19,  4.38s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.171682845383273105440297561095 완료 (248/362) | status=success | patch=38932 | 이번 환자: 4초 | 예상 남은 시간: 7분 46초

Build training-ready dataset:  69%|#####################3         | 249/362 [16:58<08:00,  4.25s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.177888806135892723698313903329 완료 (249/362) | status=success | patch=29127 | 이번 환자: 3초 | 예상 남은 시간: 7분 42초

Build training-ready dataset:  69%|#####################4         | 250/362 [17:04<09:01,  4.84s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.182798854785392200340436516930 완료 (250/362) | status=success | patch=48824 | 이번 환자: 6초 | 예상 남은 시간: 7분 39초

Build training-ready dataset:  69%|#####################4         | 251/362 [17:10<09:09,  4.95s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.190937805243443708408459490152 완료 (251/362) | status=success | patch=44570 | 이번 환자: 5초 | 예상 남은 시간: 7분 35초

Build training-ready dataset:  70%|#####################5         | 252/362 [17:13<08:13,  4.49s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.226564372605239604660221582288 완료 (252/362) | status=success | patch=22017 | 이번 환자: 3초 | 예상 남은 시간: 7분 31초

Build training-ready dataset:  70%|#####################6         | 253/362 [17:17<07:39,  4.21s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.235217371152464582553341729176 완료 (253/362) | status=success | patch=26071 | 이번 환자: 3초 | 예상 남은 시간: 7분 26초

Build training-ready dataset:  70%|#####################7         | 254/362 [17:22<08:00,  4.45s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.240630002689062442926543993263 완료 (254/362) | status=success | patch=42054 | 이번 환자: 4초 | 예상 남은 시간: 7분 23초

Build training-ready dataset:  70%|#####################8         | 255/362 [17:26<08:01,  4.50s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.254138388912084634057282064266 완료 (255/362) | status=success | patch=35869 | 이번 환자: 4초 | 예상 남은 시간: 7분 19초

Build training-ready dataset:  71%|#####################9         | 256/362 [17:31<07:57,  4.50s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.255409701134762680010928250229 완료 (256/362) | status=success | patch=37864 | 이번 환자: 4초 | 예상 남은 시간: 7분 15초

Build training-ready dataset:  71%|######################         | 257/362 [17:35<07:43,  4.42s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.266009527139315622265711325223 완료 (257/362) | status=success | patch=30958 | 이번 환자: 4초 | 예상 남은 시간: 7분 11초

Build training-ready dataset:  71%|######################         | 258/362 [17:39<07:20,  4.23s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.275849601663847251574860892603 완료 (258/362) | status=success | patch=30628 | 이번 환자: 3초 | 예상 남은 시간: 7분 6초

Build training-ready dataset:  72%|######################1        | 259/362 [17:41<06:20,  3.69s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.290410217650314119074833254861 완료 (259/362) | status=success | patch=13640 | 이번 환자: 2초 | 예상 남은 시간: 7분 2초

Build training-ready dataset:  72%|######################2        | 260/362 [17:45<06:10,  3.64s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.297251044869095073091780740645 완료 (260/362) | status=success | patch=26734 | 이번 환자: 3초 | 예상 남은 시간: 6분 57초

Build training-ready dataset:  72%|######################3        | 261/362 [17:50<06:48,  4.04s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.306558074682524259000586270818 완료 (261/362) | status=success | patch=40397 | 이번 환자: 4초 | 예상 남은 시간: 6분 54초

Build training-ready dataset:  72%|######################4        | 262/362 [17:53<06:10,  3.70s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.307921770358136677021532761235 완료 (262/362) | status=success | patch=18992 | 이번 환자: 2초 | 예상 남은 시간: 6분 49초

Build training-ready dataset:  73%|######################5        | 263/362 [17:57<06:23,  3.87s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.308153138776443962077214577161 완료 (263/362) | status=success | patch=33862 | 이번 환자: 4초 | 예상 남은 시간: 6분 45초

Build training-ready dataset:  73%|######################6        | 264/362 [18:01<06:38,  4.07s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.313756547848086902190878548835 완료 (264/362) | status=success | patch=34846 | 이번 환자: 4초 | 예상 남은 시간: 6분 41초

Build training-ready dataset:  73%|######################6        | 265/362 [18:05<06:16,  3.88s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.341557859428950960906150406596 완료 (265/362) | status=success | patch=22623 | 이번 환자: 3초 | 예상 남은 시간: 6분 37초

Build training-ready dataset:  73%|######################7        | 266/362 [18:09<06:33,  4.10s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.414288023902112119945238126594 완료 (266/362) | status=success | patch=32720 | 이번 환자: 4초 | 예상 남은 시간: 6분 33초

Build training-ready dataset:  74%|######################8        | 267/362 [18:13<06:15,  3.95s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.463588161905537526756964393219 완료 (267/362) | status=success | patch=26815 | 이번 환자: 3초 | 예상 남은 시간: 6분 29초

Build training-ready dataset:  74%|######################9        | 268/362 [18:16<05:58,  3.81s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.465032801496479029639448332481 완료 (268/362) | status=success | patch=22574 | 이번 환자: 3초 | 예상 남은 시간: 6분 24초

Build training-ready dataset:  74%|#######################        | 269/362 [18:20<05:42,  3.68s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.475325201787910087416720919680 완료 (269/362) | status=success | patch=22835 | 이번 환자: 3초 | 예상 남은 시간: 6분 20초

Build training-ready dataset:  75%|#######################1       | 270/362 [18:24<05:43,  3.74s/it]

[READY] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.561423049201987049884663740668 완료 (270/362) | status=success | patch=27597 | 이번 환자: 3초 | 예상 남은 시간: 6분 16초

Build training-ready dataset:  75%|#######################2       | 271/362 [18:27<05:25,  3.58s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.116097642684124305074876564522 완료 (271/362) | status=success | patch=24390 | 이번 환자: 3초 | 예상 남은 시간: 6분 11초

Build training-ready dataset:  75%|#######################2       | 272/362 [18:32<06:14,  4.16s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.116703382344406837243058680403 완료 (272/362) | status=success | patch=48006 | 이번 환자: 5초 | 예상 남은 시간: 6분 8초

Build training-ready dataset:  75%|#######################3       | 273/362 [18:38<06:36,  4.45s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.131150737314367975651717513386 완료 (273/362) | status=success | patch=44154 | 이번 환자: 5초 | 예상 남은 시간: 6분 4초

Build training-ready dataset:  76%|#######################4       | 274/362 [18:42<06:33,  4.47s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.139889514693390832525232698200 완료 (274/362) | status=success | patch=35545 | 이번 환자: 4초 | 예상 남은 시간: 6분 0초

Build training-ready dataset:  76%|#######################5       | 275/362 [18:47<06:45,  4.66s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.143813757344903170810482790787 완료 (275/362) | status=success | patch=42905 | 이번 환자: 5초 | 예상 남은 시간: 5분 56초

Build training-ready dataset:  76%|#######################6       | 276/362 [18:53<07:04,  4.93s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.151669338315069779994664893123 완료 (276/362) | status=success | patch=47497 | 이번 환자: 5초 | 예상 남은 시간: 5분 53초

Build training-ready dataset:  77%|#######################7       | 277/362 [18:56<06:22,  4.50s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.159665703190517688573100822213 완료 (277/362) | status=success | patch=25480 | 이번 환자: 3초 | 예상 남은 시간: 5분 48초

Build training-ready dataset:  77%|#######################8       | 278/362 [18:59<05:30,  3.94s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.163217526257871051722166468085 완료 (278/362) | status=success | patch=15678 | 이번 환자: 2초 | 예상 남은 시간: 5분 44초

Build training-ready dataset:  77%|#######################8       | 279/362 [19:05<06:24,  4.63s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.167500254299688235071950909530 완료 (279/362) | status=success | patch=49844 | 이번 환자: 6초 | 예상 남은 시간: 5분 40초

Build training-ready dataset:  77%|#######################9       | 280/362 [19:09<06:03,  4.44s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.170825539570536865106681134236 완료 (280/362) | status=success | patch=25834 | 이번 환자: 3초 | 예상 남은 시간: 5분 36초

Build training-ready dataset:  78%|########################       | 281/362 [19:11<05:06,  3.79s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.187803155574314810830688534991 완료 (281/362) | status=success | patch=13324 | 이번 환자: 2초 | 예상 남은 시간: 5분 32초

Build training-ready dataset:  78%|########################1      | 282/362 [19:14<04:38,  3.48s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.223650122819238796121876338881 완료 (282/362) | status=success | patch=14950 | 이번 환자: 2초 | 예상 남은 시간: 5분 27초

Build training-ready dataset:  78%|########################2      | 283/362 [19:17<04:31,  3.43s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.245546033414728092794968890929 완료 (283/362) | status=success | patch=21294 | 이번 환자: 3초 | 예상 남은 시간: 5분 23초

Build training-ready dataset:  78%|########################3      | 284/362 [19:21<04:21,  3.35s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.248360766706804179966476685510 완료 (284/362) | status=success | patch=19149 | 이번 환자: 3초 | 예상 남은 시간: 5분 18초

Build training-ready dataset:  79%|########################4      | 285/362 [19:24<04:26,  3.45s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.248425363469507808613979846863 완료 (285/362) | status=success | patch=27502 | 이번 환자: 3초 | 예상 남은 시간: 5분 14초

Build training-ready dataset:  79%|########################4      | 286/362 [19:28<04:32,  3.58s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.252709517998555732486024866345 완료 (286/362) | status=success | patch=30229 | 이번 환자: 3초 | 예상 남은 시간: 5분 10초

Build training-ready dataset:  79%|########################5      | 287/362 [19:33<04:53,  3.91s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.256542095129414948017808425649 완료 (287/362) | status=success | patch=37079 | 이번 환자: 4초 | 예상 남은 시간: 5분 6초

Build training-ready dataset:  80%|########################6      | 288/362 [19:37<05:01,  4.08s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.266581250778073944645044950856 완료 (288/362) | status=success | patch=36201 | 이번 환자: 4초 | 예상 남은 시간: 5분 2초

Build training-ready dataset:  80%|########################7      | 289/362 [19:43<05:23,  4.43s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.270788655216695628640355888562 완료 (289/362) | status=success | patch=44561 | 이번 환자: 5초 | 예상 남은 시간: 4분 58초

Build training-ready dataset:  80%|########################8      | 290/362 [19:48<05:39,  4.71s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.276351267409869539593937734609 완료 (290/362) | status=success | patch=41887 | 이번 환자: 5초 | 예상 남은 시간: 4분 55초

Build training-ready dataset:  80%|########################9      | 291/362 [19:53<05:39,  4.79s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.279953669991076107785464313394 완료 (291/362) | status=success | patch=39602 | 이번 환자: 4초 | 예상 남은 시간: 4분 51초

Build training-ready dataset:  81%|#########################      | 292/362 [19:57<05:19,  4.56s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.303066851236267189733420290986 완료 (292/362) | status=success | patch=28543 | 이번 환자: 3초 | 예상 남은 시간: 4분 47초

Build training-ready dataset:  81%|#########################      | 293/362 [20:00<04:49,  4.20s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.306112617218006614029386065035 완료 (293/362) | status=success | patch=24589 | 이번 환자: 3초 | 예상 남은 시간: 4분 42초

Build training-ready dataset:  81%|#########################1     | 294/362 [20:04<04:42,  4.15s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.307946352302138765071461362398 완료 (294/362) | status=success | patch=27660 | 이번 환자: 3초 | 예상 남은 시간: 4분 38초

Build training-ready dataset:  81%|#########################2     | 295/362 [20:08<04:26,  3.98s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.314836406260772370397541392345 완료 (295/362) | status=success | patch=24904 | 이번 환자: 3초 | 예상 남은 시간: 4분 34초

Build training-ready dataset:  82%|#########################3     | 296/362 [20:13<04:39,  4.24s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.315918264676377418120578391325 완료 (296/362) | status=success | patch=36856 | 이번 환자: 4초 | 예상 남은 시간: 4분 30초

Build training-ready dataset:  82%|#########################4     | 297/362 [20:18<04:47,  4.42s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.336198008634390022174744544656 완료 (297/362) | status=success | patch=38548 | 이번 환자: 4초 | 예상 남은 시간: 4분 26초

Build training-ready dataset:  82%|#########################5     | 298/362 [20:24<05:11,  4.87s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.339039410276356623209709113755 완료 (298/362) | status=success | patch=47978 | 이번 환자: 5초 | 예상 남은 시간: 4분 22초

Build training-ready dataset:  83%|#########################6     | 299/362 [20:28<04:52,  4.64s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.447468612991222399440694673357 완료 (299/362) | status=success | patch=32201 | 이번 환자: 4초 | 예상 남은 시간: 4분 18초

Build training-ready dataset:  83%|#########################6     | 300/362 [20:33<04:55,  4.77s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.664409965623578819357819577077 완료 (300/362) | status=success | patch=44669 | 이번 환자: 5초 | 예상 남은 시간: 4분 14초

Build training-ready dataset:  83%|#########################7     | 301/362 [20:35<03:57,  3.89s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.664989286137882319237192185951 완료 (301/362) | status=success | patch=10482 | 이번 환자: 1초 | 예상 남은 시간: 4분 10초

Build training-ready dataset:  83%|#########################8     | 302/362 [20:39<04:04,  4.08s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.686193079844756926365065559979 완료 (302/362) | status=success | patch=36667 | 이번 환자: 4초 | 예상 남은 시간: 4분 6초

Build training-ready dataset:  84%|#########################9     | 303/362 [20:43<03:57,  4.03s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.749871569713868632259874663577 완료 (303/362) | status=success | patch=32774 | 이번 환자: 3초 | 예상 남은 시간: 4분 2초

Build training-ready dataset:  84%|##########################     | 304/362 [20:48<04:05,  4.23s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.897279226481700053115245043064 완료 (304/362) | status=success | patch=28666 | 이번 환자: 4초 | 예상 남은 시간: 3분 58초

Build training-ready dataset:  84%|##########################1    | 305/362 [20:52<04:04,  4.29s/it]

[READY] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.957384617596077920906744920611 완료 (305/362) | status=success | patch=34384 | 이번 환자: 4초 | 예상 남은 시간: 3분 54초

Build training-ready dataset:  85%|##########################2    | 306/362 [20:57<04:07,  4.42s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.108193664222196923321844991231 완료 (306/362) | status=success | patch=38770 | 이번 환자: 4초 | 예상 남은 시간: 3분 50초

Build training-ready dataset:  85%|##########################2    | 307/362 [21:02<04:07,  4.51s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.153181766344026020914478182395 완료 (307/362) | status=success | patch=37265 | 이번 환자: 4초 | 예상 남은 시간: 3분 46초

Build training-ready dataset:  85%|##########################3    | 308/362 [21:05<03:49,  4.25s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.161633200801003804714818844696 완료 (308/362) | status=success | patch=27642 | 이번 환자: 3초 | 예상 남은 시간: 3분 41초

Build training-ready dataset:  85%|##########################4    | 309/362 [21:11<04:03,  4.59s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.161821150841552408667852639317 완료 (309/362) | status=success | patch=43679 | 이번 환자: 5초 | 예상 남은 시간: 3분 38초

Build training-ready dataset:  86%|##########################5    | 310/362 [21:17<04:31,  5.23s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.175318131822744218104175746898 완료 (310/362) | status=success | patch=57353 | 이번 환자: 6초 | 예상 남은 시간: 3분 34초

Build training-ready dataset:  86%|##########################6    | 311/362 [21:20<03:53,  4.57s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.203425588524695836343069893813 완료 (311/362) | status=success | patch=19341 | 이번 환자: 2초 | 예상 남은 시간: 3분 30초

Build training-ready dataset:  86%|##########################7    | 312/362 [21:24<03:32,  4.25s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.236698827306171960683086245994 완료 (312/362) | status=success | patch=23586 | 이번 환자: 3초 | 예상 남은 시간: 3분 25초

Build training-ready dataset:  86%|##########################8    | 313/362 [21:28<03:27,  4.24s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.246178337114401749164850220976 완료 (313/362) | status=success | patch=33764 | 이번 환자: 4초 | 예상 남은 시간: 3분 21초

Build training-ready dataset:  87%|##########################8    | 314/362 [21:33<03:36,  4.52s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.253317247142837717905329340520 완료 (314/362) | status=success | patch=41853 | 이번 환자: 5초 | 예상 남은 시간: 3분 17초

Build training-ready dataset:  87%|##########################9    | 315/362 [21:37<03:24,  4.36s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.283878926524838648426928238498 완료 (315/362) | status=success | patch=30449 | 이번 환자: 3초 | 예상 남은 시간: 3분 13초

Build training-ready dataset:  87%|###########################    | 316/362 [21:41<03:15,  4.24s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.286627485198831346082954437212 완료 (316/362) | status=success | patch=29680 | 이번 환자: 3초 | 예상 남은 시간: 3분 9초

Build training-ready dataset:  88%|###########################1   | 317/362 [21:46<03:13,  4.31s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.292049618819567427252971059233 완료 (317/362) | status=success | patch=32500 | 이번 환자: 4초 | 예상 남은 시간: 3분 5초

Build training-ready dataset:  88%|###########################2   | 318/362 [21:50<03:13,  4.40s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.296066944953051278419805374238 완료 (318/362) | status=success | patch=36818 | 이번 환자: 4초 | 예상 남은 시간: 3분 1초

Build training-ready dataset:  88%|###########################3   | 319/362 [21:53<02:54,  4.05s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.306520140119968755187868602181 완료 (319/362) | status=success | patch=26046 | 이번 환자: 3초 | 예상 남은 시간: 2분 57초

Build training-ready dataset:  88%|###########################4   | 320/362 [21:58<02:59,  4.28s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.317613170669207528926259976488 완료 (320/362) | status=success | patch=36352 | 이번 환자: 4초 | 예상 남은 시간: 2분 53초

Build training-ready dataset:  89%|###########################4   | 321/362 [22:02<02:52,  4.22s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.324649110927013926557500550446 완료 (321/362) | status=success | patch=28044 | 이번 환자: 4초 | 예상 남은 시간: 2분 48초

Build training-ready dataset:  89%|###########################5   | 322/362 [22:07<02:49,  4.24s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.336102335330125765000317290445 완료 (322/362) | status=success | patch=33850 | 이번 환자: 4초 | 예상 남은 시간: 2분 44초

Build training-ready dataset:  89%|###########################6   | 323/362 [22:12<02:56,  4.51s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.339484970190920330170416228517 완료 (323/362) | status=success | patch=41082 | 이번 환자: 5초 | 예상 남은 시간: 2분 40초

Build training-ready dataset:  90%|###########################7   | 324/362 [22:17<02:54,  4.60s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.373433682859788429397781158572 완료 (324/362) | status=success | patch=38877 | 이번 환자: 4초 | 예상 남은 시간: 2분 36초

Build training-ready dataset:  90%|###########################8   | 325/362 [22:21<02:52,  4.66s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.608029415915051219877530734559 완료 (325/362) | status=success | patch=36750 | 이번 환자: 4초 | 예상 남은 시간: 2분 32초

Build training-ready dataset:  90%|###########################9   | 326/362 [22:25<02:31,  4.20s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.622243923620914676263059698181 완료 (326/362) | status=success | patch=19340 | 이번 환자: 3초 | 예상 남은 시간: 2분 28초

Build training-ready dataset:  90%|############################   | 327/362 [22:30<02:41,  4.62s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.671278273674156798801285503514 완료 (327/362) | status=success | patch=46783 | 이번 환자: 5초 | 예상 남은 시간: 2분 24초

Build training-ready dataset:  91%|############################   | 328/362 [22:33<02:21,  4.16s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.701514276942509393419164159551 완료 (328/362) | status=success | patch=21116 | 이번 환자: 3초 | 예상 남은 시간: 2분 20초

Build training-ready dataset:  91%|############################1  | 329/362 [22:38<02:20,  4.26s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.766881513533845439335142582269 완료 (329/362) | status=success | patch=34718 | 이번 환자: 4초 | 예상 남은 시간: 2분 16초

Build training-ready dataset:  91%|############################2  | 330/362 [22:41<02:10,  4.09s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.814122498113547115932318256859 완료 (330/362) | status=success | patch=28904 | 이번 환자: 3초 | 예상 남은 시간: 2분 12초

Build training-ready dataset:  91%|############################3  | 331/362 [22:47<02:19,  4.51s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.888615810685807330497715730842 완료 (331/362) | status=success | patch=44598 | 이번 환자: 5초 | 예상 남은 시간: 2분 8초

Build training-ready dataset:  92%|############################4  | 332/362 [22:51<02:13,  4.47s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.897161587681142256575045076919 완료 (332/362) | status=success | patch=35024 | 이번 환자: 4초 | 예상 남은 시간: 2분 3초

Build training-ready dataset:  92%|############################5  | 333/362 [22:55<02:02,  4.22s/it]

[READY] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.939216568327879462530496768794 완료 (333/362) | status=success | patch=23064 | 이번 환자: 3초 | 예상 남은 시간: 1분 59초

Build training-ready dataset:  92%|############################6  | 334/362 [23:01<02:16,  4.88s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.109882169963817627559804568094 완료 (334/362) | status=success | patch=53010 | 이번 환자: 6초 | 예상 남은 시간: 1분 55초

Build training-ready dataset:  93%|############################6  | 335/362 [23:05<01:59,  4.43s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.121805476976020513950614465787 완료 (335/362) | status=success | patch=22028 | 이번 환자: 3초 | 예상 남은 시간: 1분 51초

Build training-ready dataset:  93%|############################7  | 336/362 [23:08<01:48,  4.17s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.124656777236468248920498636247 완료 (336/362) | status=success | patch=22324 | 이번 환자: 3초 | 예상 남은 시간: 1분 47초

Build training-ready dataset:  93%|############################8  | 337/362 [23:14<01:55,  4.63s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.129650136453746261130135157590 완료 (337/362) | status=success | patch=44335 | 이번 환자: 5초 | 예상 남은 시간: 1분 43초

Build training-ready dataset:  93%|############################9  | 338/362 [23:20<01:57,  4.90s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.138674679709964033277400089532 완료 (338/362) | status=success | patch=45094 | 이번 환자: 5초 | 예상 남은 시간: 1분 39초

Build training-ready dataset:  94%|#############################  | 339/362 [23:24<01:47,  4.69s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.139577698050713461261415990027 완료 (339/362) | status=success | patch=29668 | 이번 환자: 4초 | 예상 남은 시간: 1분 35초

Build training-ready dataset:  94%|#############################1 | 340/362 [23:29<01:47,  4.90s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.145510611155363050427743946446 완료 (340/362) | status=success | patch=42613 | 이번 환자: 5초 | 예상 남은 시간: 1분 31초

Build training-ready dataset:  94%|#############################2 | 341/362 [23:34<01:40,  4.77s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.148935306123327835217659769212 완료 (341/362) | status=success | patch=34614 | 이번 환자: 4초 | 예상 남은 시간: 1분 27초

Build training-ready dataset:  94%|#############################2 | 342/362 [23:37<01:28,  4.42s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.179683407589764683292800449011 완료 (342/362) | status=success | patch=26787 | 이번 환자: 3초 | 예상 남은 시간: 1분 22초

Build training-ready dataset:  95%|#############################3 | 343/362 [23:41<01:23,  4.37s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.193721075067404532739943086458 완료 (343/362) | status=success | patch=33793 | 이번 환자: 4초 | 예상 남은 시간: 1분 18초

Build training-ready dataset:  95%|#############################4 | 344/362 [23:45<01:16,  4.26s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.229960820686439513664996214638 완료 (344/362) | status=success | patch=29686 | 이번 환자: 3초 | 예상 남은 시간: 1분 14초

Build training-ready dataset:  95%|#############################5 | 345/362 [23:50<01:13,  4.32s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.237915456403882324748189195892 완료 (345/362) | status=success | patch=37591 | 이번 환자: 4초 | 예상 남은 시간: 1분 10초

Build training-ready dataset:  96%|#############################6 | 346/362 [23:53<01:05,  4.07s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.254929810944557499537650429296 완료 (346/362) | status=success | patch=24504 | 이번 환자: 3초 | 예상 남은 시간: 1분 6초

Build training-ready dataset:  96%|#############################7 | 347/362 [24:00<01:11,  4.78s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.259453428008507791234730686014 완료 (347/362) | status=success | patch=58165 | 이번 환자: 6초 | 예상 남은 시간: 1분 2초

Build training-ready dataset:  96%|#############################8 | 348/362 [24:04<01:02,  4.49s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.265570697208310960298668720669 완료 (348/362) | status=success | patch=29815 | 이번 환자: 3초 | 예상 남은 시간: 58초

Build training-ready dataset:  96%|#############################8 | 349/362 [24:06<00:50,  3.89s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.286061375572911414226912429210 완료 (349/362) | status=success | patch=13775 | 이번 환자: 2초 | 예상 남은 시간: 53초

Build training-ready dataset:  97%|#############################9 | 350/362 [24:10<00:45,  3.76s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.291156498203266896953765649282 완료 (350/362) | status=success | patch=24620 | 이번 환자: 3초 | 예상 남은 시간: 49초

Build training-ready dataset:  97%|############################## | 351/362 [24:14<00:44,  4.02s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.292576688635952269497781991202 완료 (351/362) | status=success | patch=35460 | 이번 환자: 4초 | 예상 남은 시간: 45초

Build training-ready dataset:  97%|##############################1| 352/362 [24:19<00:42,  4.30s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.300392272203629213913702120739 완료 (352/362) | status=success | patch=36577 | 이번 환자: 4초 | 예상 남은 시간: 41초

Build training-ready dataset:  98%|##############################2| 353/362 [24:24<00:40,  4.46s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.300693623747082239407271583452 완료 (353/362) | status=success | patch=35368 | 이번 환자: 4초 | 예상 남은 시간: 37초

Build training-ready dataset:  98%|##############################3| 354/362 [24:28<00:34,  4.30s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.306140003699110313373771452136 완료 (354/362) | status=success | patch=29732 | 이번 환자: 3초 | 예상 남은 시간: 33초

Build training-ready dataset:  98%|##############################4| 355/362 [24:33<00:30,  4.41s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.330043769832606379655473292782 완료 (355/362) | status=success | patch=32766 | 이번 환자: 4초 | 예상 남은 시간: 29초

Build training-ready dataset:  98%|##############################4| 356/362 [24:38<00:27,  4.57s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.330643702676971528301859647742 완료 (356/362) | status=success | patch=39787 | 이번 환자: 4초 | 예상 남은 시간: 24초

Build training-ready dataset:  99%|##############################5| 357/362 [24:43<00:24,  4.95s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.334166493392278943610545989413 완료 (357/362) | status=success | patch=45359 | 이번 환자: 5초 | 예상 남은 시간: 20초

Build training-ready dataset:  99%|##############################6| 358/362 [24:47<00:17,  4.44s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.340012777775661021262977442176 완료 (358/362) | status=success | patch=20997 | 이번 환자: 3초 | 예상 남은 시간: 16초

Build training-ready dataset:  99%|##############################7| 359/362 [24:50<00:12,  4.10s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.436403998650924660479049012235 완료 (359/362) | status=success | patch=19824 | 이번 환자: 3초 | 예상 남은 시간: 12초

Build training-ready dataset:  99%|##############################8| 360/362 [24:55<00:08,  4.28s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.472487466001405705666001578363 완료 (360/362) | status=success | patch=35369 | 이번 환자: 4초 | 예상 남은 시간: 8초

Build training-ready dataset: 100%|##############################9| 361/362 [24:59<00:04,  4.26s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.855232435861303786204450738044 완료 (361/362) | status=success | patch=29693 | 이번 환자: 4초 | 예상 남은 시간: 4초

Build training-ready dataset: 100%|###############################| 362/362 [25:01<00:00,  4.15s/it]

[READY] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.927394449308471452920270961822 완료 (362/362) | status=success | patch=16200 | 이번 환자: 2초 | 예상 남은 시간: 0초

========== BUILD TRAINING READY FINISHED ==========
OUT_ROOT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest
success / skipped rows: 362
errors: 0

Summarize final patch indexes: 100%|##############################| 362/362 [03:10<00:00,  1.90it/s]

========== SPLIT COUNT ==========
split
train    290
test      36
val       36
Name: count, dtype: int64

========== SPLIT POSITION COUNTS ==========

    split       position_bin  patch_count
0    test      lower_central        77743
1    test   lower_peripheral       205502
2    test     middle_central       158316
3    test  middle_peripheral       348545
4    test      upper_central        95669
5    test   upper_peripheral       206600
6   train      lower_central       673587
7   train   lower_peripheral      1752912
8   train     middle_central      1383309
9   train  middle_peripheral      3036464
10  train      upper_central       792448
11  train   upper_peripheral      1710769
12    val      lower_central        87302
13    val   lower_peripheral       229942
14    val     middle_central       180194
15    val  middle_peripheral       402883
16    val      upper_central       107547
17    val   upper_peripheral       229375

========== FINAL OUTPUT ==========
OUT_ROOT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest
volumes_npy: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\volumes_npy
patch_index_by_patient: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\patch_index_by_patient
manifests: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\manifests
configs: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\configs
logs: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\logs

========== FILES ==========
patient_manifest: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\manifests\patient_manifest.csv
patch_position_counts: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\manifests\patch_position_counts.csv
patch_count_by_patient: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\manifests\patch_count_by_patient.csv
patient_position_counts: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\manifests\patient_position_counts.csv
train_val_test_split: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\manifests\train_val_test_split.csv
split_position_counts: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\manifests\split_position_counts.csv

========== Position bin counts ==========

        position_bin  patch_count
0      lower_central       838632
1   lower_peripheral      2188356
2     middle_central      1721819
3  middle_peripheral      3787892
4      upper_central       995664
5   upper_peripheral      2146744

========== Patch count by patient summary ==========

count      362.000000
mean     32262.726519
std       9847.895441
min       7594.000000
25%      25986.750000
50%      32488.000000
75%      38226.250000
max      66124.000000
Name: patch_count, dtype: float64

========== Error count ==========
0