In [3]:
# ============================================================
# Build PaDiM training-ready slim dataset
# ------------------------------------------------------------
# 목적:
#   - 기존 Normal_LUNA16_training_ready_v1을 기반으로
#   - PaDiM / 위치별 정상 기준 학습에 필요한 파일만 새 폴더로 정리
#
# 최종 유지:
#   - ct_hu.npy
#   - pure_lung.npy
#   - meta.json
#   - 좌표 중심 patch CSV
#   - patient_manifest.csv
#   - train / val / test split CSV
#
# 최종 제거:
#   - organ_exclusion.npy
#   - patch CSV 안 반복 경로 컬럼
#   - patch CSV 안 기존 HU feature 컬럼
#   - hist_bin 컬럼
#   - 원본 NIfTI 경로 컬럼
#
# 주의:
#   - 원본 training_ready_v1은 건드리지 않음
#   - 새 padim 학습용 폴더를 따로 만듦
# ============================================================

from pathlib import Path
import os
import json
import shutil
import time
import gc
from collections import Counter

import numpy as np
import pandas as pd
from tqdm import tqdm
from pandas.errors import EmptyDataError


# ============================================================
# 1. CONFIG
# ============================================================

CONFIG = {
    # 기존 전체 training-ready 폴더
    "source_training_ready_root": r"E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest",

    # 새 PaDiM 학습용 slim 폴더
    "padim_training_ready_root": r"E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest",

    # 파일 복사 방식
    # "copy"     : 실제 파일 복사. 안전하지만 용량이 새로 듦.
    # "hardlink" : 같은 드라이브에서 실제 데이터 중복 없이 링크 생성. 빠르고 용량 절약.
    #              단, 원본과 새 파일이 같은 실제 데이터를 가리킴.
    "copy_mode": "hardlink",

    # 기존 결과가 있으면 skip
    "skip_existing": True,

    # 기존 결과 덮어쓰기
    "overwrite_existing": False,

    # CT / mask 파일명
    "ct_filename": "ct_hu.npy",
    "pure_filename": "pure_lung.npy",
    "meta_filename": "meta.json",

    # organ_exclusion은 PaDiM 학습용 slim에서는 저장하지 않음
    "save_organ_exclusion": False,

    # patch index에서 남길 컬럼
    # HU feature / hist_bin / 반복 경로 컬럼은 제외
    "keep_patch_columns": [
        "patient_id",
        "safe_id",
        "label",

        "local_z",
        "y0",
        "x0",
        "y1",
        "x1",

        "patch_size",
        "patch_stride",

        "position_bin",
        "z_level",
        "z_ratio",
        "central_peripheral",
        "central_distance_ratio_mean",
        "left_right_metadata",

        "pure_lung_pixels",
        "organ_pixels",
        "pure_lung_patch_ratio",
        "organ_patch_ratio",
        "slice_pure_lung_ratio",
    ],
}


SRC_ROOT = Path(CONFIG["source_training_ready_root"])
OUT_ROOT = Path(CONFIG["padim_training_ready_root"])

SRC_VOLUME_ROOT = SRC_ROOT / "volumes_npy"
SRC_PATCH_INDEX_ROOT = SRC_ROOT / "patch_index_by_patient"
SRC_MANIFEST_DIR = SRC_ROOT / "manifests"
SRC_CONFIG_DIR = SRC_ROOT / "configs"

OUT_VOLUME_ROOT = OUT_ROOT / "volumes_npy"
OUT_PATCH_INDEX_ROOT = OUT_ROOT / "patch_index_by_patient"
OUT_MANIFEST_DIR = OUT_ROOT / "manifests"
OUT_CONFIG_DIR = OUT_ROOT / "configs"
OUT_LOG_DIR = OUT_ROOT / "logs"

for d in [
    OUT_ROOT,
    OUT_VOLUME_ROOT,
    OUT_PATCH_INDEX_ROOT,
    OUT_MANIFEST_DIR,
    OUT_CONFIG_DIR,
    OUT_LOG_DIR,
]:
    d.mkdir(parents=True, exist_ok=True)

with open(OUT_CONFIG_DIR / "padim_training_ready_config.json", "w", encoding="utf-8") as f:
    json.dump(CONFIG, f, indent=2, ensure_ascii=False)

print("========== PADIM CONFIG ==========")
print("SRC_ROOT:", SRC_ROOT)
print("OUT_ROOT:", OUT_ROOT)
print("copy_mode:", CONFIG["copy_mode"])


# ============================================================
# 2. helper functions
# ============================================================

def format_seconds(seconds: float) -> str:
    seconds = int(seconds)

    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60

    if h > 0:
        return f"{h}시간 {m}분 {s}초"

    if m > 0:
        return f"{m}분 {s}초"

    return f"{s}초"


def save_json(obj, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)


def read_json_safe(path: Path):
    if not path.exists():
        return {}

    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def read_csv_safe(path: Path, usecols=None):
    try:
        return pd.read_csv(path, usecols=usecols)
    except EmptyDataError:
        if usecols is None:
            return pd.DataFrame()
        return pd.DataFrame(columns=list(usecols))
    except ValueError:
        # usecols 중 없는 컬럼이 있을 때 fallback
        try:
            return pd.read_csv(path)
        except EmptyDataError:
            return pd.DataFrame()


def count_csv_rows_safe(path: Path):
    if not path.exists():
        return 0

    try:
        return int(len(pd.read_csv(path, usecols=["patient_id"])))
    except Exception:
        try:
            return int(len(pd.read_csv(path)))
        except Exception:
            return 0


def copy_or_hardlink_file(src: Path, dst: Path, mode: str):
    """
    src 파일을 dst로 복사하거나 hardlink 생성.
    dst가 이미 있으면 그대로 둠.
    """

    src = Path(src)
    dst = Path(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)

    if not src.exists():
        raise FileNotFoundError(f"source file 없음: {src}")

    if dst.exists():
        return "exists"

    mode = str(mode).lower()

    if mode == "hardlink":
        try:
            os.link(str(src), str(dst))
            return "hardlink"
        except Exception:
            shutil.copy2(str(src), str(dst))
            return "copy_fallback"

    if mode == "copy":
        shutil.copy2(str(src), str(dst))
        return "copy"

    raise ValueError(f"지원하지 않는 copy_mode: {mode}")


def make_empty_slim_patch_df():
    return pd.DataFrame(columns=CONFIG["keep_patch_columns"])


def make_slim_patch_csv(source_patch_csv: Path, out_patch_csv: Path, patient_id: str, safe_id: str, label: str):
    """
    기존 patch CSV에서 PaDiM 학습에 필요한 컬럼만 남김.
    HU feature / hist_bin / 반복 경로 컬럼은 제거.
    """

    keep_cols = list(CONFIG["keep_patch_columns"])

    if not source_patch_csv.exists():
        slim_df = make_empty_slim_patch_df()
        slim_df.to_csv(out_patch_csv, index=False, encoding="utf-8-sig")
        return 0

    try:
        header = pd.read_csv(source_patch_csv, nrows=0).columns.tolist()
    except EmptyDataError:
        slim_df = make_empty_slim_patch_df()
        slim_df.to_csv(out_patch_csv, index=False, encoding="utf-8-sig")
        return 0

    available_keep_cols = [c for c in keep_cols if c in header]

    try:
        patch_df = pd.read_csv(source_patch_csv, usecols=available_keep_cols)
    except EmptyDataError:
        patch_df = pd.DataFrame(columns=available_keep_cols)

    # 필수 관리 컬럼 보강
    if "patient_id" not in patch_df.columns:
        patch_df["patient_id"] = patient_id

    if "safe_id" not in patch_df.columns:
        patch_df["safe_id"] = safe_id

    if "label" not in patch_df.columns:
        patch_df["label"] = label

    # keep_cols 순서 유지
    for c in keep_cols:
        if c not in patch_df.columns:
            patch_df[c] = ""

    patch_df = patch_df[keep_cols]

    patch_df.to_csv(
        out_patch_csv,
        index=False,
        encoding="utf-8-sig",
    )

    return int(len(patch_df))


def folder_size_gb(path: Path):
    total = 0
    for p in Path(path).rglob("*"):
        if p.is_file():
            total += p.stat().st_size
    return total / (1024 ** 3)


# ============================================================
# 3. input checks
# ============================================================

source_manifest_path = SRC_MANIFEST_DIR / "patient_manifest.csv"

if not source_manifest_path.exists():
    raise FileNotFoundError(f"patient_manifest.csv 없음: {source_manifest_path}")

source_manifest = pd.read_csv(source_manifest_path)

required_manifest_cols = [
    "patient_id",
    "safe_id",
    "patch_count",
    "ct_hu_npy",
    "pure_lung_npy",
    "meta_json",
    "patch_csv",
]

for c in required_manifest_cols:
    if c not in source_manifest.columns:
        raise RuntimeError(f"source patient_manifest.csv에 필요한 컬럼 없음: {c}")

print("========== SOURCE CHECK ==========")
print("source patients:", len(source_manifest))
print("source manifest:", source_manifest_path)


# ============================================================
# 4. build one patient
# ============================================================

def build_one_patient(row):
    patient_id = str(row["patient_id"])
    safe_id = str(row["safe_id"])
    label = str(row["label"]) if "label" in row and pd.notna(row["label"]) else "normal"

    out_patient_volume_dir = OUT_VOLUME_ROOT / safe_id
    out_patient_volume_dir.mkdir(parents=True, exist_ok=True)

    out_ct_npy = out_patient_volume_dir / CONFIG["ct_filename"]
    out_pure_npy = out_patient_volume_dir / CONFIG["pure_filename"]
    out_meta_json = out_patient_volume_dir / CONFIG["meta_filename"]
    out_done_marker = out_patient_volume_dir / ".done"

    out_patch_csv = OUT_PATCH_INDEX_ROOT / f"{safe_id}.csv"

    source_ct_npy = Path(str(row["ct_hu_npy"]))
    source_pure_npy = Path(str(row["pure_lung_npy"]))
    source_meta_json = Path(str(row["meta_json"]))
    source_patch_csv = Path(str(row["patch_csv"]))

    if bool(CONFIG["overwrite_existing"]):
        if out_patient_volume_dir.exists():
            shutil.rmtree(out_patient_volume_dir)
            out_patient_volume_dir.mkdir(parents=True, exist_ok=True)

        if out_patch_csv.exists():
            out_patch_csv.unlink()

    if (
        bool(CONFIG["skip_existing"])
        and out_done_marker.exists()
        and out_ct_npy.exists()
        and out_pure_npy.exists()
        and out_meta_json.exists()
        and out_patch_csv.exists()
    ):
        patch_count = count_csv_rows_safe(out_patch_csv)

        return {
            "patient_id": patient_id,
            "safe_id": safe_id,
            "status": "skipped_existing",
            "label": label,
            "patch_count": int(patch_count),
            "volume_dir": str(out_patient_volume_dir),
            "ct_hu_npy": str(out_ct_npy),
            "pure_lung_npy": str(out_pure_npy),
            "meta_json": str(out_meta_json),
            "patch_csv": str(out_patch_csv),
        }

    # --------------------------------------------------------
    # ct_hu.npy / pure_lung.npy만 유지
    # organ_exclusion.npy는 저장하지 않음
    # --------------------------------------------------------
    ct_copy_status = copy_or_hardlink_file(
        source_ct_npy,
        out_ct_npy,
        CONFIG["copy_mode"],
    )

    pure_copy_status = copy_or_hardlink_file(
        source_pure_npy,
        out_pure_npy,
        CONFIG["copy_mode"],
    )

    # --------------------------------------------------------
    # meta.json 정리
    # --------------------------------------------------------
    source_meta = read_json_safe(source_meta_json)

    padim_meta = dict(source_meta)
    padim_meta["patient_id"] = patient_id
    padim_meta["safe_id"] = safe_id
    padim_meta["label"] = label

    padim_meta["ct_hu_npy"] = str(out_ct_npy)
    padim_meta["pure_lung_npy"] = str(out_pure_npy)

    # PaDiM slim에서는 organ_exclusion.npy를 제거
    if "organ_exclusion_npy" in padim_meta:
        padim_meta.pop("organ_exclusion_npy")

    padim_meta["source_training_ready_root"] = str(SRC_ROOT)
    padim_meta["source_ct_hu_npy"] = str(source_ct_npy)
    padim_meta["source_pure_lung_npy"] = str(source_pure_npy)
    padim_meta["source_meta_json"] = str(source_meta_json)
    padim_meta["source_patch_csv"] = str(source_patch_csv)

    padim_meta["padim_training_ready_note"] = (
        "PaDiM 학습용 slim 데이터셋. "
        "ct_hu.npy와 pure_lung.npy만 유지. "
        "organ_exclusion.npy는 저장하지 않음. "
        "patch CSV는 좌표/위치/ratio 중심 컬럼만 유지."
    )

    padim_meta["copy_mode"] = CONFIG["copy_mode"]
    padim_meta["ct_copy_status"] = ct_copy_status
    padim_meta["pure_copy_status"] = pure_copy_status

    save_json(padim_meta, out_meta_json)

    # --------------------------------------------------------
    # slim patch CSV 생성
    # --------------------------------------------------------
    patch_count = make_slim_patch_csv(
        source_patch_csv=source_patch_csv,
        out_patch_csv=out_patch_csv,
        patient_id=patient_id,
        safe_id=safe_id,
        label=label,
    )

    out_done_marker.write_text("done", encoding="utf-8")

    return {
        "patient_id": patient_id,
        "safe_id": safe_id,
        "status": "success",
        "label": label,
        "patch_count": int(patch_count),

        "volume_dir": str(out_patient_volume_dir),
        "ct_hu_npy": str(out_ct_npy),
        "pure_lung_npy": str(out_pure_npy),
        "meta_json": str(out_meta_json),
        "patch_csv": str(out_patch_csv),

        "source_ct_hu_npy": str(source_ct_npy),
        "source_pure_lung_npy": str(source_pure_npy),
        "source_meta_json": str(source_meta_json),
        "source_patch_csv": str(source_patch_csv),

        "ct_copy_status": ct_copy_status,
        "pure_copy_status": pure_copy_status,
    }


# ============================================================
# 5. run build
# ============================================================

summary_rows = []
error_rows = []

global_start = time.perf_counter()
total_cases = len(source_manifest)

print("\n========== BUILD PADIM TRAINING READY START ==========")

for case_idx, (_, row) in enumerate(
    tqdm(
        source_manifest.iterrows(),
        total=total_cases,
        desc="Build PaDiM slim dataset",
        ncols=100,
        ascii=True,
    ),
    start=1,
):
    start = time.perf_counter()

    try:
        out_row = build_one_patient(row)

        elapsed = time.perf_counter() - start
        total_elapsed = time.perf_counter() - global_start
        avg = total_elapsed / case_idx
        remain = total_cases - case_idx
        eta = avg * remain

        out_row.update({
            "case_index": int(case_idx),
            "total_cases": int(total_cases),
            "elapsed_seconds": round(elapsed, 2),
            "elapsed_readable": format_seconds(elapsed),
            "total_elapsed_seconds": round(total_elapsed, 2),
            "total_elapsed_readable": format_seconds(total_elapsed),
            "estimated_remaining_seconds": round(eta, 2),
            "estimated_remaining_readable": format_seconds(eta),
        })

        summary_rows.append(out_row)

        pd.DataFrame(summary_rows).to_csv(
            OUT_LOG_DIR / "build_padim_training_ready_summary.csv",
            index=False,
            encoding="utf-8-sig",
        )

        print(
            f"[PADIM] {out_row['patient_id']} 완료 "
            f"({case_idx}/{total_cases}) | "
            f"status={out_row['status']} | "
            f"patch={out_row['patch_count']} | "
            f"이번 환자: {format_seconds(elapsed)} | "
            f"예상 남은 시간: {format_seconds(eta)}"
        )

    except Exception as e:
        elapsed = time.perf_counter() - start

        err = {
            "patient_id": str(row.get("patient_id", "")),
            "safe_id": str(row.get("safe_id", "")),
            "error": str(e),
            "elapsed_seconds": round(elapsed, 2),
            "elapsed_readable": format_seconds(elapsed),
        }

        error_rows.append(err)

        pd.DataFrame(error_rows).to_csv(
            OUT_LOG_DIR / "build_padim_training_ready_errors.csv",
            index=False,
            encoding="utf-8-sig",
        )

        print("[ERROR]", err["patient_id"], str(e))

    gc.collect()


summary_df = pd.DataFrame(summary_rows)
error_df = pd.DataFrame(error_rows)

summary_df.to_csv(
    OUT_LOG_DIR / "build_padim_training_ready_summary.csv",
    index=False,
    encoding="utf-8-sig",
)

if len(error_df) > 0:
    error_df.to_csv(
        OUT_LOG_DIR / "build_padim_training_ready_errors.csv",
        index=False,
        encoding="utf-8-sig",
    )

print("\n========== BUILD PADIM TRAINING READY FINISHED ==========")
print("OUT_ROOT:", OUT_ROOT)
print("success / skipped rows:", len(summary_df))
print("errors:", len(error_df))


# ============================================================
# 6. create patient manifest
# ============================================================

if len(summary_df) == 0:
    raise RuntimeError("성공한 환자가 없음. error csv 확인 필요.")

patient_manifest = summary_df.copy()

front_cols = [
    "patient_id",
    "safe_id",
    "status",
    "label",
    "patch_count",
    "volume_dir",
    "ct_hu_npy",
    "pure_lung_npy",
    "meta_json",
    "patch_csv",
]

front_cols = [c for c in front_cols if c in patient_manifest.columns]
other_cols = [c for c in patient_manifest.columns if c not in front_cols]
patient_manifest = patient_manifest[front_cols + other_cols]

patient_manifest.to_csv(
    OUT_MANIFEST_DIR / "patient_manifest.csv",
    index=False,
    encoding="utf-8-sig",
)


# ============================================================
# 7. copy / rebuild split files
# ============================================================

source_split_path = SRC_MANIFEST_DIR / "train_val_test_split.csv"

if source_split_path.exists():
    source_split_df = pd.read_csv(source_split_path)

    split_cols = ["patient_id", "split"]

    if "patient_id" not in source_split_df.columns or "split" not in source_split_df.columns:
        raise RuntimeError("source train_val_test_split.csv에 patient_id 또는 split 컬럼 없음")

    split_df = source_split_df[split_cols].merge(
        patient_manifest[
            [
                "patient_id",
                "safe_id",
                "patch_count",
                "patch_csv",
                "volume_dir",
                "ct_hu_npy",
                "pure_lung_npy",
            ]
        ],
        on="patient_id",
        how="inner",
    )

    split_df = split_df[split_df["patch_count"].fillna(0).astype(int) > 0].copy()

    split_df.to_csv(
        OUT_MANIFEST_DIR / "train_val_test_split.csv",
        index=False,
        encoding="utf-8-sig",
    )

    for split_name in ["train", "val", "test"]:
        split_df[split_df["split"] == split_name].to_csv(
            OUT_MANIFEST_DIR / f"{split_name}_patients.csv",
            index=False,
            encoding="utf-8-sig",
        )

else:
    print("[WARN] source train_val_test_split.csv 없음. split 파일은 생성하지 않음.")
    split_df = pd.DataFrame()


# ============================================================
# 8. summarize final slim patch CSVs
# ============================================================

patient_position_rows = []
patch_count_rows = []

for _, row in tqdm(
    patient_manifest.iterrows(),
    total=len(patient_manifest),
    desc="Summarize PaDiM patch indexes",
    ncols=100,
    ascii=True,
):
    patient_id = str(row["patient_id"])
    safe_id = str(row["safe_id"])
    patch_csv = Path(str(row["patch_csv"]))

    if not patch_csv.exists():
        patch_count_rows.append({
            "patient_id": patient_id,
            "safe_id": safe_id,
            "patch_count": 0,
        })
        continue

    try:
        df = pd.read_csv(patch_csv, usecols=["patient_id", "position_bin"])
    except EmptyDataError:
        df = pd.DataFrame(columns=["patient_id", "position_bin"])
    except ValueError:
        df = pd.DataFrame(columns=["patient_id", "position_bin"])

    patch_count_rows.append({
        "patient_id": patient_id,
        "safe_id": safe_id,
        "patch_count": int(len(df)),
    })

    if len(df) == 0:
        continue

    counts = df["position_bin"].value_counts()

    for position_bin, count in counts.items():
        patient_position_rows.append({
            "patient_id": patient_id,
            "safe_id": safe_id,
            "position_bin": position_bin,
            "patch_count": int(count),
        })

patient_position_df = pd.DataFrame(patient_position_rows)
patch_count_df = pd.DataFrame(patch_count_rows)

if len(patient_position_df) > 0:
    patch_position_counts = (
        patient_position_df
        .groupby("position_bin", as_index=False)["patch_count"]
        .sum()
        .sort_values("position_bin")
    )
else:
    patch_position_counts = pd.DataFrame(columns=["position_bin", "patch_count"])

patient_position_df.to_csv(
    OUT_MANIFEST_DIR / "patient_position_counts.csv",
    index=False,
    encoding="utf-8-sig",
)

patch_position_counts.to_csv(
    OUT_MANIFEST_DIR / "patch_position_counts.csv",
    index=False,
    encoding="utf-8-sig",
)

patch_count_df.to_csv(
    OUT_MANIFEST_DIR / "patch_count_by_patient.csv",
    index=False,
    encoding="utf-8-sig",
)


# ============================================================
# 9. split position counts
# ============================================================

if len(split_df) > 0 and len(patient_position_df) > 0:
    split_map = dict(zip(split_df["patient_id"], split_df["split"]))

    split_position_rows = []

    for _, r in patient_position_df.iterrows():
        pid = r["patient_id"]

        if pid not in split_map:
            continue

        split_position_rows.append({
            "split": split_map[pid],
            "patient_id": pid,
            "safe_id": r["safe_id"],
            "position_bin": r["position_bin"],
            "patch_count": int(r["patch_count"]),
        })

    split_position_df = pd.DataFrame(split_position_rows)

    if len(split_position_df) > 0:
        split_position_summary = (
            split_position_df
            .groupby(["split", "position_bin"], as_index=False)["patch_count"]
            .sum()
            .sort_values(["split", "position_bin"])
        )
    else:
        split_position_summary = pd.DataFrame(columns=["split", "position_bin", "patch_count"])

    split_position_df.to_csv(
        OUT_MANIFEST_DIR / "split_patient_position_counts.csv",
        index=False,
        encoding="utf-8-sig",
    )

    split_position_summary.to_csv(
        OUT_MANIFEST_DIR / "split_position_counts.csv",
        index=False,
        encoding="utf-8-sig",
    )
else:
    split_position_summary = pd.DataFrame(columns=["split", "position_bin", "patch_count"])


# ============================================================
# 10. copy source configs / small summaries
# ============================================================

for src_name in [
    "training_ready_config.json",
    "preprocess_config.json",
    "patch_config.json",
]:
    src = SRC_CONFIG_DIR / src_name
    if src.exists():
        shutil.copy2(str(src), str(OUT_CONFIG_DIR / f"source_{src_name}"))

for src_name in [
    "source_patch_patient_summary.csv",
    "source_patch_position_counts.csv",
    "source_patch_count_by_patient.csv",
]:
    src = SRC_MANIFEST_DIR / src_name
    if src.exists():
        shutil.copy2(str(src), str(OUT_MANIFEST_DIR / src_name))


# ============================================================
# 11. final check
# ============================================================

print("\n========== FINAL PADIM OUTPUT ==========")
print("OUT_ROOT:", OUT_ROOT)
print("volumes_npy:", OUT_VOLUME_ROOT)
print("patch_index_by_patient:", OUT_PATCH_INDEX_ROOT)
print("manifests:", OUT_MANIFEST_DIR)
print("configs:", OUT_CONFIG_DIR)
print("logs:", OUT_LOG_DIR)

print("\n========== FILES ==========")
print("patient_manifest:", OUT_MANIFEST_DIR / "patient_manifest.csv")
print("train_val_test_split:", OUT_MANIFEST_DIR / "train_val_test_split.csv")
print("patch_position_counts:", OUT_MANIFEST_DIR / "patch_position_counts.csv")
print("patch_count_by_patient:", OUT_MANIFEST_DIR / "patch_count_by_patient.csv")
print("split_position_counts:", OUT_MANIFEST_DIR / "split_position_counts.csv")

print("\n========== Position bin counts ==========")
display(patch_position_counts)

print("\n========== Patch count by patient summary ==========")
if len(patch_count_df) > 0:
    display(patch_count_df["patch_count"].describe())
else:
    print("patch_count_df 비어 있음")

print("\n========== Split count ==========")
if len(split_df) > 0:
    display(split_df["split"].value_counts())
else:
    print("split_df 비어 있음")

print("\n========== Split position counts ==========")
display(split_position_summary)

print("\n========== Error count ==========")
print(len(error_df))

if len(error_df) > 0:
    print("error file:", OUT_LOG_DIR / "build_padim_training_ready_errors.csv")

print("\n========== Size check ==========")
print("OUT total:", f"{folder_size_gb(OUT_ROOT):.2f} GB")
print("OUT volumes_npy:", f"{folder_size_gb(OUT_VOLUME_ROOT):.2f} GB")
print("OUT patch_index_by_patient:", f"{folder_size_gb(OUT_PATCH_INDEX_ROOT):.2f} GB")

========== PADIM CONFIG ==========
SRC_ROOT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest
OUT_ROOT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest
copy_mode: hardlink
========== SOURCE CHECK ==========
source patients: 362
source manifest: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_training_ready_v2_tslungguard_nochest\manifests\patient_manifest.csv

========== BUILD PADIM TRAINING READY START ==========

Build PaDiM slim dataset:   0%|1                                    | 1/362 [00:00<03:18,  1.82it/s]

[PADIM] normal001 완료 (1/362) | status=success | patch=20948 | 이번 환자: 0초 | 예상 남은 시간: 2분 54초

Build PaDiM slim dataset:   1%|2                                    | 2/362 [00:01<03:20,  1.80it/s]

[PADIM] normal002 완료 (2/362) | status=success | patch=22012 | 이번 환자: 0초 | 예상 남은 시간: 3분 13초

Build PaDiM slim dataset:   1%|3                                    | 3/362 [00:01<03:50,  1.56it/s]

[PADIM] normal003 완료 (3/362) | status=success | patch=30825 | 이번 환자: 0초 | 예상 남은 시간: 3분 37초

Build PaDiM slim dataset:   1%|4                                    | 4/362 [00:02<03:52,  1.54it/s]

[PADIM] normal004 완료 (4/362) | status=success | patch=27119 | 이번 환자: 0초 | 예상 남은 시간: 3분 42초

Build PaDiM slim dataset:   1%|5                                    | 5/362 [00:03<04:10,  1.43it/s]

[PADIM] normal005 완료 (5/362) | status=success | patch=32653 | 이번 환자: 0초 | 예상 남은 시간: 3분 53초

Build PaDiM slim dataset:   2%|6                                    | 6/362 [00:04<04:49,  1.23it/s]

[PADIM] normal006 완료 (6/362) | status=success | patch=39241 | 이번 환자: 0초 | 예상 남은 시간: 4분 12초

Build PaDiM slim dataset:   2%|7                                    | 7/362 [00:04<04:26,  1.33it/s]

[PADIM] normal007 완료 (7/362) | status=success | patch=23343 | 이번 환자: 0초 | 예상 남은 시간: 4분 9초

Build PaDiM slim dataset:   2%|8                                    | 8/362 [00:05<04:31,  1.30it/s]

[PADIM] normal008 완료 (8/362) | status=success | patch=33329 | 이번 환자: 0초 | 예상 남은 시간: 4분 13초

Build PaDiM slim dataset:   2%|9                                    | 9/362 [00:06<04:15,  1.38it/s]

[PADIM] normal009 완료 (9/362) | status=success | patch=25858 | 이번 환자: 0초 | 예상 남은 시간: 4분 9초

Build PaDiM slim dataset:   3%|9                                   | 10/362 [00:07<04:21,  1.34it/s]

[PADIM] normal010 완료 (10/362) | status=success | patch=34867 | 이번 환자: 0초 | 예상 남은 시간: 4분 11초

Build PaDiM slim dataset:   3%|#                                   | 11/362 [00:08<04:35,  1.27it/s]

[PADIM] normal011 완료 (11/362) | status=success | patch=36485 | 이번 환자: 0초 | 예상 남은 시간: 4분 15초

Build PaDiM slim dataset:   3%|#1                                  | 12/362 [00:08<04:30,  1.29it/s]

[PADIM] normal012 완료 (12/362) | status=success | patch=30678 | 이번 환자: 0초 | 예상 남은 시간: 4분 15초

Build PaDiM slim dataset:   4%|#2                                  | 13/362 [00:09<04:07,  1.41it/s]

[PADIM] normal013 완료 (13/362) | status=success | patch=21424 | 이번 환자: 0초 | 예상 남은 시간: 4분 10초

Build PaDiM slim dataset:   4%|#3                                  | 14/362 [00:10<04:05,  1.42it/s]

[PADIM] normal014 완료 (14/362) | status=success | patch=28777 | 이번 환자: 0초 | 예상 남은 시간: 4분 9초

Build PaDiM slim dataset:   4%|#4                                  | 15/362 [00:10<03:47,  1.53it/s]

[PADIM] normal015 완료 (15/362) | status=success | patch=20598 | 이번 환자: 0초 | 예상 남은 시간: 4분 4초

Build PaDiM slim dataset:   4%|#5                                  | 16/362 [00:11<03:42,  1.56it/s]

[PADIM] normal016 완료 (16/362) | status=success | patch=24133 | 이번 환자: 0초 | 예상 남은 시간: 4분 1초

Build PaDiM slim dataset:   5%|#6                                  | 17/362 [00:11<03:48,  1.51it/s]

[PADIM] normal017 완료 (17/362) | status=success | patch=29881 | 이번 환자: 0초 | 예상 남은 시간: 4분 1초

Build PaDiM slim dataset:   5%|#7                                  | 18/362 [00:12<03:58,  1.44it/s]

[PADIM] normal018 완료 (18/362) | status=success | patch=33392 | 이번 환자: 0초 | 예상 남은 시간: 4분 1초

Build PaDiM slim dataset:   5%|#8                                  | 19/362 [00:13<04:02,  1.41it/s]

[PADIM] normal019 완료 (19/362) | status=success | patch=34172 | 이번 환자: 0초 | 예상 남은 시간: 4분 1초

Build PaDiM slim dataset:   6%|#9                                  | 20/362 [00:13<03:47,  1.51it/s]

[PADIM] normal020 완료 (20/362) | status=success | patch=24239 | 이번 환자: 0초 | 예상 남은 시간: 3분 58초

Build PaDiM slim dataset:   6%|##                                  | 21/362 [00:14<03:51,  1.47it/s]

[PADIM] normal021 완료 (21/362) | status=success | patch=31543 | 이번 환자: 0초 | 예상 남은 시간: 3분 58초

Build PaDiM slim dataset:   6%|##1                                 | 22/362 [00:15<03:41,  1.53it/s]

[PADIM] normal022 완료 (22/362) | status=success | patch=22147 | 이번 환자: 0초 | 예상 남은 시간: 3분 55초

Build PaDiM slim dataset:   6%|##2                                 | 23/362 [00:16<04:08,  1.36it/s]

[PADIM] normal023 완료 (23/362) | status=success | patch=41977 | 이번 환자: 0초 | 예상 남은 시간: 3분 58초

Build PaDiM slim dataset:   7%|##3                                 | 24/362 [00:17<04:22,  1.29it/s]

[PADIM] normal024 완료 (24/362) | status=success | patch=37894 | 이번 환자: 0초 | 예상 남은 시간: 4분 0초

Build PaDiM slim dataset:   7%|##4                                 | 25/362 [00:17<04:19,  1.30it/s]

[PADIM] normal025 완료 (25/362) | status=success | patch=32476 | 이번 환자: 0초 | 예상 남은 시간: 4분 0초

Build PaDiM slim dataset:   7%|##5                                 | 26/362 [00:18<04:20,  1.29it/s]

[PADIM] normal026 완료 (26/362) | status=success | patch=32734 | 이번 환자: 0초 | 예상 남은 시간: 4분 0초

Build PaDiM slim dataset:   7%|##6                                 | 27/362 [00:19<04:09,  1.34it/s]

[PADIM] normal027 완료 (27/362) | status=success | patch=26663 | 이번 환자: 0초 | 예상 남은 시간: 3분 59초

Build PaDiM slim dataset:   8%|##7                                 | 28/362 [00:19<03:48,  1.46it/s]

[PADIM] normal028 완료 (28/362) | status=success | patch=20975 | 이번 환자: 0초 | 예상 남은 시간: 3분 56초

Build PaDiM slim dataset:   8%|##8                                 | 29/362 [00:20<03:43,  1.49it/s]

[PADIM] normal029 완료 (29/362) | status=success | patch=26160 | 이번 환자: 0초 | 예상 남은 시간: 3분 54초

Build PaDiM slim dataset:   8%|##9                                 | 30/362 [00:21<03:52,  1.43it/s]

[PADIM] normal030 완료 (30/362) | status=success | patch=30925 | 이번 환자: 0초 | 예상 남은 시간: 3분 54초

Build PaDiM slim dataset:   9%|###                                 | 31/362 [00:22<03:55,  1.40it/s]

[PADIM] normal031 완료 (31/362) | status=success | patch=29995 | 이번 환자: 0초 | 예상 남은 시간: 3분 54초

Build PaDiM slim dataset:   9%|###1                                | 32/362 [00:22<03:43,  1.48it/s]

[PADIM] normal032 완료 (32/362) | status=success | patch=23004 | 이번 환자: 0초 | 예상 남은 시간: 3분 52초

Build PaDiM slim dataset:   9%|###2                                | 33/362 [00:23<04:02,  1.36it/s]

[PADIM] normal033 완료 (33/362) | status=success | patch=38358 | 이번 환자: 0초 | 예상 남은 시간: 3분 53초

Build PaDiM slim dataset:   9%|###3                                | 34/362 [00:24<03:48,  1.43it/s]

[PADIM] normal034 완료 (34/362) | status=success | patch=23824 | 이번 환자: 0초 | 예상 남은 시간: 3분 51초

Build PaDiM slim dataset:  10%|###4                                | 35/362 [00:24<04:00,  1.36it/s]

[PADIM] normal035 완료 (35/362) | status=success | patch=35652 | 이번 환자: 0초 | 예상 남은 시간: 3분 52초

Build PaDiM slim dataset:  10%|###5                                | 36/362 [00:25<04:09,  1.31it/s]

[PADIM] normal036 완료 (36/362) | status=success | patch=34569 | 이번 환자: 0초 | 예상 남은 시간: 3분 52초

Build PaDiM slim dataset:  10%|###6                                | 37/362 [00:26<04:00,  1.35it/s]

[PADIM] normal037 완료 (37/362) | status=success | patch=27602 | 이번 환자: 0초 | 예상 남은 시간: 3분 51초

Build PaDiM slim dataset:  10%|###7                                | 38/362 [00:27<04:42,  1.15it/s]

[PADIM] normal038 완료 (38/362) | status=success | patch=52080 | 이번 환자: 1초 | 예상 남은 시간: 3분 55초

Build PaDiM slim dataset:  11%|###8                                | 39/362 [00:28<04:16,  1.26it/s]

[PADIM] normal039 완료 (39/362) | status=success | patch=24117 | 이번 환자: 0초 | 예상 남은 시간: 3분 53초

Build PaDiM slim dataset:  11%|###9                                | 40/362 [00:28<04:13,  1.27it/s]

[PADIM] normal040 완료 (40/362) | status=success | patch=32221 | 이번 환자: 0초 | 예상 남은 시간: 3분 53초

Build PaDiM slim dataset:  11%|####                                | 41/362 [00:29<04:07,  1.30it/s]

[PADIM] normal041 완료 (41/362) | status=success | patch=30150 | 이번 환자: 0초 | 예상 남은 시간: 3분 52초

Build PaDiM slim dataset:  12%|####1                               | 42/362 [00:30<03:52,  1.38it/s]

[PADIM] normal042 완료 (42/362) | status=success | patch=24745 | 이번 환자: 0초 | 예상 남은 시간: 3분 50초

Build PaDiM slim dataset:  12%|####2                               | 43/362 [00:31<03:57,  1.34it/s]

[PADIM] normal043 완료 (43/362) | status=success | patch=31646 | 이번 환자: 0초 | 예상 남은 시간: 3분 50초

Build PaDiM slim dataset:  12%|####3                               | 44/362 [00:32<04:10,  1.27it/s]

[PADIM] normal044 완료 (44/362) | status=success | patch=38253 | 이번 환자: 0초 | 예상 남은 시간: 3분 51초

Build PaDiM slim dataset:  12%|####4                               | 45/362 [00:32<04:19,  1.22it/s]

[PADIM] normal045 완료 (45/362) | status=success | patch=39455 | 이번 환자: 0초 | 예상 남은 시간: 3분 51초

Build PaDiM slim dataset:  13%|####5                               | 46/362 [00:33<03:52,  1.36it/s]

[PADIM] normal046 완료 (46/362) | status=success | patch=19874 | 이번 환자: 0초 | 예상 남은 시간: 3분 49초

Build PaDiM slim dataset:  13%|####6                               | 47/362 [00:34<03:47,  1.39it/s]

[PADIM] normal047 완료 (47/362) | status=success | patch=27299 | 이번 환자: 0초 | 예상 남은 시간: 3분 48초

Build PaDiM slim dataset:  13%|####7                               | 48/362 [00:34<03:59,  1.31it/s]

[PADIM] normal048 완료 (48/362) | status=success | patch=36835 | 이번 환자: 0초 | 예상 남은 시간: 3분 48초

Build PaDiM slim dataset:  14%|####8                               | 49/362 [00:35<04:15,  1.23it/s]

[PADIM] normal049 완료 (49/362) | status=success | patch=40415 | 이번 환자: 0초 | 예상 남은 시간: 3분 49초

Build PaDiM slim dataset:  14%|####9                               | 50/362 [00:36<04:31,  1.15it/s]

[PADIM] normal050 완료 (50/362) | status=success | patch=43285 | 이번 환자: 0초 | 예상 남은 시간: 3분 50초

Build PaDiM slim dataset:  14%|#####                               | 51/362 [00:37<04:26,  1.17it/s]

[PADIM] normal051 완료 (51/362) | status=success | patch=34465 | 이번 환자: 0초 | 예상 남은 시간: 3분 50초

Build PaDiM slim dataset:  14%|#####1                              | 52/362 [00:38<04:15,  1.21it/s]

[PADIM] normal052 완료 (52/362) | status=success | patch=28079 | 이번 환자: 0초 | 예상 남은 시간: 3분 49초

Build PaDiM slim dataset:  15%|#####2                              | 53/362 [00:39<03:58,  1.30it/s]

[PADIM] normal053 완료 (53/362) | status=success | patch=26605 | 이번 환자: 0초 | 예상 남은 시간: 3분 48초

Build PaDiM slim dataset:  15%|#####3                              | 54/362 [00:40<04:07,  1.25it/s]

[PADIM] normal054 완료 (54/362) | status=success | patch=37483 | 이번 환자: 0초 | 예상 남은 시간: 3분 48초

Build PaDiM slim dataset:  15%|#####4                              | 55/362 [00:40<04:09,  1.23it/s]

[PADIM] normal055 완료 (55/362) | status=success | patch=34903 | 이번 환자: 0초 | 예상 남은 시간: 3분 47초

Build PaDiM slim dataset:  15%|#####5                              | 56/362 [00:41<04:07,  1.23it/s]

[PADIM] normal056 완료 (56/362) | status=success | patch=33034 | 이번 환자: 0초 | 예상 남은 시간: 3분 47초

Build PaDiM slim dataset:  16%|#####6                              | 57/362 [00:42<03:56,  1.29it/s]

[PADIM] normal057 완료 (57/362) | status=success | patch=27838 | 이번 환자: 0초 | 예상 남은 시간: 3분 46초

Build PaDiM slim dataset:  16%|#####7                              | 58/362 [00:42<03:40,  1.38it/s]

[PADIM] normal058 완료 (58/362) | status=success | patch=24600 | 이번 환자: 0초 | 예상 남은 시간: 3분 45초

Build PaDiM slim dataset:  16%|#####8                              | 59/362 [00:43<04:04,  1.24it/s]

[PADIM] normal059 완료 (59/362) | status=success | patch=44421 | 이번 환자: 0초 | 예상 남은 시간: 3분 45초

Build PaDiM slim dataset:  17%|#####9                              | 60/362 [00:44<04:20,  1.16it/s]

[PADIM] normal060 완료 (60/362) | status=success | patch=42949 | 이번 환자: 0초 | 예상 남은 시간: 3분 46초

Build PaDiM slim dataset:  17%|######                              | 61/362 [00:45<04:04,  1.23it/s]

[PADIM] normal061 완료 (61/362) | status=success | patch=28589 | 이번 환자: 0초 | 예상 남은 시간: 3분 45초

Build PaDiM slim dataset:  17%|######1                             | 62/362 [00:46<03:48,  1.32it/s]

[PADIM] normal062 완료 (62/362) | status=success | patch=26013 | 이번 환자: 0초 | 예상 남은 시간: 3분 43초

Build PaDiM slim dataset:  17%|######2                             | 63/362 [00:46<03:36,  1.38it/s]

[PADIM] normal063 완료 (63/362) | status=success | patch=26090 | 이번 환자: 0초 | 예상 남은 시간: 3분 42초

Build PaDiM slim dataset:  18%|######3                             | 64/362 [00:47<03:25,  1.45it/s]

[PADIM] normal064 완료 (64/362) | status=success | patch=23826 | 이번 환자: 0초 | 예상 남은 시간: 3분 41초

Build PaDiM slim dataset:  18%|######4                             | 65/362 [00:48<03:37,  1.36it/s]

[PADIM] normal065 완료 (65/362) | status=success | patch=36114 | 이번 환자: 0초 | 예상 남은 시간: 3분 40초

Build PaDiM slim dataset:  18%|######5                             | 66/362 [00:49<03:34,  1.38it/s]

[PADIM] normal066 완료 (66/362) | status=success | patch=28836 | 이번 환자: 0초 | 예상 남은 시간: 3분 39초

Build PaDiM slim dataset:  19%|######6                             | 67/362 [00:49<03:31,  1.39it/s]

[PADIM] normal067 완료 (67/362) | status=success | patch=27944 | 이번 환자: 0초 | 예상 남은 시간: 3분 39초

Build PaDiM slim dataset:  19%|######7                             | 68/362 [00:50<03:31,  1.39it/s]

[PADIM] normal068 완료 (68/362) | status=success | patch=30335 | 이번 환자: 0초 | 예상 남은 시간: 3분 38초

Build PaDiM slim dataset:  19%|######8                             | 69/362 [00:51<03:54,  1.25it/s]

[PADIM] normal069 완료 (69/362) | status=success | patch=44501 | 이번 환자: 0초 | 예상 남은 시간: 3분 38초

Build PaDiM slim dataset:  19%|######9                             | 70/362 [00:52<03:53,  1.25it/s]

[PADIM] normal070 완료 (70/362) | status=success | patch=34226 | 이번 환자: 0초 | 예상 남은 시간: 3분 38초

Build PaDiM slim dataset:  20%|#######                             | 71/362 [00:53<03:53,  1.25it/s]

[PADIM] normal071 완료 (71/362) | status=success | patch=34989 | 이번 환자: 0초 | 예상 남은 시간: 3분 37초

Build PaDiM slim dataset:  20%|#######1                            | 72/362 [00:53<03:41,  1.31it/s]

[PADIM] normal073 완료 (72/362) | status=success | patch=27611 | 이번 환자: 0초 | 예상 남은 시간: 3분 36초

Build PaDiM slim dataset:  20%|#######2                            | 73/362 [00:54<03:35,  1.34it/s]

[PADIM] normal074 완료 (73/362) | status=success | patch=27632 | 이번 환자: 0초 | 예상 남은 시간: 3분 35초

Build PaDiM slim dataset:  20%|#######3                            | 74/362 [00:55<03:42,  1.30it/s]

[PADIM] normal075 완료 (74/362) | status=success | patch=34442 | 이번 환자: 0초 | 예상 남은 시간: 3분 35초

Build PaDiM slim dataset:  21%|#######4                            | 75/362 [00:56<03:44,  1.28it/s]

[PADIM] normal076 완료 (75/362) | status=success | patch=34170 | 이번 환자: 0초 | 예상 남은 시간: 3분 34초

Build PaDiM slim dataset:  21%|#######5                            | 76/362 [00:57<04:08,  1.15it/s]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.105756658031515062000744821260 완료 (76/362) | status=success | patch=33299 | 이번 환자: 1초 | 예상 남은 시간: 3분 35초

Build PaDiM slim dataset:  21%|#######6                            | 77/362 [00:58<04:33,  1.04it/s]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.122763913896761494371822656720 완료 (77/362) | status=success | patch=37363 | 이번 환자: 1초 | 예상 남은 시간: 3분 35초

Build PaDiM slim dataset:  22%|#######7                            | 78/362 [00:59<05:09,  1.09s/it]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.126121460017257137098781143514 완료 (78/362) | status=success | patch=45521 | 이번 환자: 1초 | 예상 남은 시간: 3분 37초

Build PaDiM slim dataset:  22%|#######8                            | 79/362 [01:00<04:55,  1.05s/it]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.139713436241461669335487719526 완료 (79/362) | status=success | patch=28537 | 이번 환자: 0초 | 예상 남은 시간: 3분 37초

Build PaDiM slim dataset:  22%|#######9                            | 80/362 [01:01<04:50,  1.03s/it]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.144438612068946916340281098509 완료 (80/362) | status=success | patch=31543 | 이번 환자: 0초 | 예상 남은 시간: 3분 37초

Build PaDiM slim dataset:  22%|########                            | 81/362 [01:03<05:31,  1.18s/it]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.146429221666426688999739595820 완료 (81/362) | status=success | patch=51215 | 이번 환자: 1초 | 예상 남은 시간: 3분 39초

Build PaDiM slim dataset:  23%|########1                           | 82/362 [01:04<05:30,  1.18s/it]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.194465340552956447447896167830 완료 (82/362) | status=success | patch=38146 | 이번 환자: 1초 | 예상 남은 시간: 3분 39초

Build PaDiM slim dataset:  23%|########2                           | 83/362 [01:05<05:38,  1.21s/it]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.210837812047373739447725050963 완료 (83/362) | status=success | patch=43348 | 이번 환자: 1초 | 예상 남은 시간: 3분 40초

Build PaDiM slim dataset:  23%|########3                           | 84/362 [01:06<05:02,  1.09s/it]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.231645134739451754302647733304 완료 (84/362) | status=success | patch=25515 | 이번 환자: 0초 | 예상 남은 시간: 3분 39초

Build PaDiM slim dataset:  23%|########4                           | 85/362 [01:07<04:54,  1.06s/it]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.238522526736091851696274044574 완료 (85/362) | status=success | patch=33227 | 이번 환자: 0초 | 예상 남은 시간: 3분 39초

Build PaDiM slim dataset:  24%|########5                           | 86/362 [01:08<04:31,  1.02it/s]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.250438451287314206124484591986 완료 (86/362) | status=success | patch=22590 | 이번 환자: 0초 | 예상 남은 시간: 3분 39초

Build PaDiM slim dataset:  24%|########6                           | 87/362 [01:09<04:36,  1.00s/it]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.269689294231892620436462818860 완료 (87/362) | status=success | patch=34818 | 이번 환자: 1초 | 예상 남은 시간: 3분 39초

Build PaDiM slim dataset:  24%|########7                           | 88/362 [01:10<04:09,  1.10it/s]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.278660284797073139172446973682 완료 (88/362) | status=success | patch=20207 | 이번 환자: 0초 | 예상 남은 시간: 3분 37초

Build PaDiM slim dataset:  25%|########8                           | 89/362 [01:11<04:31,  1.01it/s]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.280972147860943609388015648430 완료 (89/362) | status=success | patch=39017 | 이번 환자: 1초 | 예상 남은 시간: 3분 38초

Build PaDiM slim dataset:  25%|########9                           | 90/362 [01:12<04:23,  1.03it/s]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.302134342469412607966016057827 완료 (90/362) | status=success | patch=26516 | 이번 환자: 0초 | 예상 남은 시간: 3분 37초

Build PaDiM slim dataset:  25%|#########                           | 91/362 [01:13<04:36,  1.02s/it]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.310626494937915759224334597176 완료 (91/362) | status=success | patch=38364 | 이번 환자: 1초 | 예상 남은 시간: 3분 38초

Build PaDiM slim dataset:  25%|#########1                          | 92/362 [01:14<04:12,  1.07it/s]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.311981398931043315779172047718 완료 (92/362) | status=success | patch=20835 | 이번 환자: 0초 | 예상 남은 시간: 3분 37초

Build PaDiM slim dataset:  26%|#########2                          | 93/362 [01:15<05:13,  1.17s/it]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.332453873575389860371315979768 완료 (93/362) | status=success | patch=58698 | 이번 환자: 1초 | 예상 남은 시간: 3분 38초

Build PaDiM slim dataset:  26%|#########3                          | 94/362 [01:16<04:29,  1.01s/it]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.397062004302272014259317520874 완료 (94/362) | status=success | patch=17441 | 이번 환자: 0초 | 예상 남은 시간: 3분 37초

Build PaDiM slim dataset:  26%|#########4                          | 95/362 [01:16<03:35,  1.24it/s]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.564534197011295112247542153557 완료 (95/362) | status=success | patch=8730 | 이번 환자: 0초 | 예상 남은 시간: 3분 35초

Build PaDiM slim dataset:  27%|#########5                          | 96/362 [01:17<03:32,  1.25it/s]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.657775098760536289051744981056 완료 (96/362) | status=success | patch=23554 | 이번 환자: 0초 | 예상 남은 시간: 3분 34초

Build PaDiM slim dataset:  27%|#########6                          | 97/362 [01:18<03:51,  1.15it/s]

[PADIM] subset0_1.3.6.1.4.1.14519.5.2.1.6279.6001.975254950136384517744116790879 완료 (97/362) | status=success | patch=32514 | 이번 환자: 0초 | 예상 남은 시간: 3분 34초

Build PaDiM slim dataset:  27%|#########7                          | 98/362 [01:20<04:57,  1.13s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.100684836163890911914061745866 완료 (98/362) | status=success | patch=58144 | 이번 환자: 1초 | 예상 남은 시간: 3분 36초

Build PaDiM slim dataset:  27%|#########8                          | 99/362 [01:20<04:06,  1.07it/s]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.111017101339429664883879536171 완료 (99/362) | status=success | patch=12237 | 이번 환자: 0초 | 예상 남은 시간: 3분 34초

Build PaDiM slim dataset:  28%|#########6                         | 100/362 [01:21<03:44,  1.17it/s]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.113697708991260454310623082679 완료 (100/362) | status=success | patch=19536 | 이번 환자: 0초 | 예상 남은 시간: 3분 33초

Build PaDiM slim dataset:  28%|#########7                         | 101/362 [01:22<04:08,  1.05it/s]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.139595277234735528205899724196 완료 (101/362) | status=success | patch=40347 | 이번 환자: 1초 | 예상 남은 시간: 3분 33초

Build PaDiM slim dataset:  28%|#########8                         | 102/362 [01:23<03:41,  1.18it/s]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.140527383975300992150799777603 완료 (102/362) | status=success | patch=16750 | 이번 환자: 0초 | 예상 남은 시간: 3분 31초

Build PaDiM slim dataset:  28%|#########9                         | 103/362 [01:24<03:45,  1.15it/s]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.144943344795414353192059796098 완료 (103/362) | status=success | patch=29652 | 이번 환자: 0초 | 예상 남은 시간: 3분 31초

Build PaDiM slim dataset:  29%|##########                         | 104/362 [01:25<04:03,  1.06it/s]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.146603910507557786636779705509 완료 (104/362) | status=success | patch=37255 | 이번 환자: 1초 | 예상 남은 시간: 3분 31초

Build PaDiM slim dataset:  29%|##########1                        | 105/362 [01:26<04:52,  1.14s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.152684536713461901635595118048 완료 (105/362) | status=success | patch=54976 | 이번 환자: 1초 | 예상 남은 시간: 3분 32초

Build PaDiM slim dataset:  29%|##########2                        | 106/362 [01:27<04:18,  1.01s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.161002239822118346732951898613 완료 (106/362) | status=success | patch=19194 | 이번 환자: 0초 | 예상 남은 시간: 3분 31초

Build PaDiM slim dataset:  30%|##########3                        | 107/362 [01:28<04:04,  1.04it/s]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.161073793312426102774780216551 완료 (107/362) | status=success | patch=25978 | 이번 환자: 0초 | 예상 남은 시간: 3분 30초

Build PaDiM slim dataset:  30%|##########4                        | 108/362 [01:29<04:31,  1.07s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.162207236104936931957809623059 완료 (108/362) | status=success | patch=44929 | 이번 환자: 1초 | 예상 남은 시간: 3분 30초

Build PaDiM slim dataset:  30%|##########5                        | 109/362 [01:31<04:50,  1.15s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.171919524048654494439256263785 완료 (109/362) | status=success | patch=42244 | 이번 환자: 1초 | 예상 남은 시간: 3분 31초

Build PaDiM slim dataset:  30%|##########6                        | 110/362 [01:32<04:47,  1.14s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.184019785706727365023450012318 완료 (110/362) | status=success | patch=36381 | 이번 환자: 1초 | 예상 남은 시간: 3분 31초

Build PaDiM slim dataset:  31%|##########7                        | 111/362 [01:33<05:01,  1.20s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.186021279664749879526003668137 완료 (111/362) | status=success | patch=44675 | 이번 환자: 1초 | 예상 남은 시간: 3분 31초

Build PaDiM slim dataset:  31%|##########8                        | 112/362 [01:34<04:57,  1.19s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.193408384740507320589857096592 완료 (112/362) | status=success | patch=36620 | 이번 환자: 1초 | 예상 남은 시간: 3분 31초

Build PaDiM slim dataset:  31%|##########9                        | 113/362 [01:35<04:37,  1.12s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.197987940182806628828566429132 완료 (113/362) | status=success | patch=29595 | 이번 환자: 0초 | 예상 남은 시간: 3분 30초

Build PaDiM slim dataset:  31%|###########                        | 114/362 [01:36<04:25,  1.07s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.200558451375970945040979397866 완료 (114/362) | status=success | patch=31636 | 이번 환자: 0초 | 예상 남은 시간: 3분 29초

Build PaDiM slim dataset:  32%|###########1                       | 115/362 [01:38<04:55,  1.20s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.216652640878960522552873394709 완료 (115/362) | status=success | patch=42122 | 이번 환자: 1초 | 예상 남은 시간: 3분 30초

Build PaDiM slim dataset:  32%|###########2                       | 116/362 [01:39<04:41,  1.15s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.222087811960706096424718056430 완료 (116/362) | status=success | patch=33302 | 이번 환자: 0초 | 예상 남은 시간: 3분 30초

Build PaDiM slim dataset:  32%|###########3                       | 117/362 [01:40<04:54,  1.20s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.231834776365874788440767645596 완료 (117/362) | status=success | patch=44522 | 이번 환자: 1초 | 예상 남은 시간: 3분 30초

Build PaDiM slim dataset:  33%|###########4                       | 118/362 [01:41<04:36,  1.13s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.259018373683540453277752706262 완료 (118/362) | status=success | patch=31635 | 이번 환자: 0초 | 예상 남은 시간: 3분 29초

Build PaDiM slim dataset:  33%|###########5                       | 119/362 [01:42<04:49,  1.19s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.286647622786041008124419915089 완료 (119/362) | status=success | patch=44845 | 이번 환자: 1초 | 예상 남은 시간: 3분 29초

Build PaDiM slim dataset:  33%|###########6                       | 120/362 [01:43<04:48,  1.19s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.300271604576987336866436407488 완료 (120/362) | status=success | patch=40075 | 이번 환자: 1초 | 예상 남은 시간: 3분 29초

Build PaDiM slim dataset:  33%|###########6                       | 121/362 [01:44<04:33,  1.13s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.308183340111270052562662456038 완료 (121/362) | status=success | patch=31709 | 이번 환자: 0초 | 예상 남은 시간: 3분 28초

Build PaDiM slim dataset:  34%|###########7                       | 122/362 [01:46<04:29,  1.12s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.331211682377519763144559212009 완료 (122/362) | status=success | patch=35523 | 이번 환자: 1초 | 예상 남은 시간: 3분 28초

Build PaDiM slim dataset:  34%|###########8                       | 123/362 [01:46<04:05,  1.03s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.335866409407244673864352309754 완료 (123/362) | status=success | patch=24458 | 이번 환자: 0초 | 예상 남은 시간: 3분 27초

Build PaDiM slim dataset:  34%|###########9                       | 124/362 [01:47<03:55,  1.01it/s]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.802595762867498341201607992711 완료 (124/362) | status=success | patch=28144 | 이번 환자: 0초 | 예상 남은 시간: 3분 26초

Build PaDiM slim dataset:  35%|############                       | 125/362 [01:48<03:57,  1.00s/it]

[PADIM] subset1_1.3.6.1.4.1.14519.5.2.1.6279.6001.888291896309937415860209787179 완료 (125/362) | status=success | patch=32427 | 이번 환자: 0초 | 예상 남은 시간: 3분 26초

Build PaDiM slim dataset:  35%|############1                      | 126/362 [01:49<03:51,  1.02it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.102133688497886810253331438797 완료 (126/362) | status=success | patch=29156 | 이번 환자: 0초 | 예상 남은 시간: 3분 25초

Build PaDiM slim dataset:  35%|############2                      | 127/362 [01:50<03:42,  1.06it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.113586291551175790743673929831 완료 (127/362) | status=success | patch=26172 | 이번 환자: 0초 | 예상 남은 시간: 3분 24초

Build PaDiM slim dataset:  35%|############3                      | 128/362 [01:52<04:25,  1.14s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.116492508532884962903000261147 완료 (128/362) | status=success | patch=53049 | 이번 환자: 1초 | 예상 남은 시간: 3분 24초

Build PaDiM slim dataset:  36%|############4                      | 129/362 [01:52<03:53,  1.00s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.117383608379722740629083782428 완료 (129/362) | status=success | patch=19926 | 이번 환자: 0초 | 예상 남은 시간: 3분 23초

Build PaDiM slim dataset:  36%|############5                      | 130/362 [01:54<04:17,  1.11s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.139444426690868429919252698606 완료 (130/362) | status=success | patch=44459 | 이번 환자: 1초 | 예상 남은 시간: 3분 23초

Build PaDiM slim dataset:  36%|############6                      | 131/362 [01:55<04:13,  1.10s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.156322145453198768801776721493 완료 (131/362) | status=success | patch=34459 | 이번 환자: 1초 | 예상 남은 시간: 3분 23초

Build PaDiM slim dataset:  36%|############7                      | 132/362 [01:56<04:13,  1.10s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.156579001330474859527530187095 완료 (132/362) | status=success | patch=36781 | 이번 환자: 1초 | 예상 남은 시간: 3분 22초

Build PaDiM slim dataset:  37%|############8                      | 133/362 [01:57<04:24,  1.16s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.159521777966998275980367008904 완료 (133/362) | status=success | patch=41675 | 이번 환자: 1초 | 예상 남은 시간: 3분 22초

Build PaDiM slim dataset:  37%|############9                      | 134/362 [01:58<03:56,  1.04s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.172845185165807139298420209778 완료 (134/362) | status=success | patch=23156 | 이번 환자: 0초 | 예상 남은 시간: 3분 21초

Build PaDiM slim dataset:  37%|#############                      | 135/362 [01:59<03:32,  1.07it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.176362912420491262783064585333 완료 (135/362) | status=success | patch=22046 | 이번 환자: 0초 | 예상 남은 시간: 3분 20초

Build PaDiM slim dataset:  38%|#############1                     | 136/362 [02:00<03:49,  1.02s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.191301539558980174217770205256 완료 (136/362) | status=success | patch=40194 | 이번 환자: 1초 | 예상 남은 시간: 3분 19초

Build PaDiM slim dataset:  38%|#############2                     | 137/362 [02:01<03:57,  1.06s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.213022585153512920098588556742 완료 (137/362) | status=success | patch=37799 | 이번 환자: 1초 | 예상 남은 시간: 3분 19초

Build PaDiM slim dataset:  38%|#############3                     | 138/362 [02:02<03:30,  1.06it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.216526102138308489357443843021 완료 (138/362) | status=success | patch=18653 | 이번 환자: 0초 | 예상 남은 시간: 3분 18초

Build PaDiM slim dataset:  38%|#############4                     | 139/362 [02:02<03:25,  1.09it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.220205300714852483483213840572 완료 (139/362) | status=success | patch=27045 | 이번 환자: 0초 | 예상 남은 시간: 3분 17초

Build PaDiM slim dataset:  39%|#############5                     | 140/362 [02:04<04:11,  1.13s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.221945191226273284587353530424 완료 (140/362) | status=success | patch=53582 | 이번 환자: 1초 | 예상 남은 시간: 3분 17초

Build PaDiM slim dataset:  39%|#############6                     | 141/362 [02:05<03:56,  1.07s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.223098610241551815995595311693 완료 (141/362) | status=success | patch=28111 | 이번 환자: 0초 | 예상 남은 시간: 3분 16초

Build PaDiM slim dataset:  39%|#############7                     | 142/362 [02:06<04:19,  1.18s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.230078008964732806419498631442 완료 (142/362) | status=success | patch=48442 | 이번 환자: 1초 | 예상 남은 시간: 3분 16초

Build PaDiM slim dataset:  40%|#############8                     | 143/362 [02:08<04:10,  1.14s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.253283426904813468115158375647 완료 (143/362) | status=success | patch=34257 | 이번 환자: 1초 | 예상 남은 시간: 3분 16초

Build PaDiM slim dataset:  40%|#############9                     | 144/362 [02:08<03:53,  1.07s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.265133389948279331857097127422 완료 (144/362) | status=success | patch=27843 | 이번 환자: 0초 | 예상 남은 시간: 3분 15초

Build PaDiM slim dataset:  40%|##############                     | 145/362 [02:09<03:33,  1.02it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.272259794130271010519952623746 완료 (145/362) | status=success | patch=22907 | 이번 환자: 0초 | 예상 남은 시간: 3분 14초

Build PaDiM slim dataset:  40%|##############1                    | 146/362 [02:10<03:32,  1.02it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.281967919138248195763602360723 완료 (146/362) | status=success | patch=30210 | 이번 환자: 0초 | 예상 남은 시간: 3분 13초

Build PaDiM slim dataset:  41%|##############2                    | 147/362 [02:11<03:38,  1.02s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.296863826932699509516219450076 완료 (147/362) | status=success | patch=32809 | 이번 환자: 1초 | 예상 남은 시간: 3분 12초

Build PaDiM slim dataset:  41%|##############3                    | 148/362 [02:12<03:38,  1.02s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.306788423710427765311352901943 완료 (148/362) | status=success | patch=32604 | 이번 환자: 0초 | 예상 남은 시간: 3분 12초

Build PaDiM slim dataset:  41%|##############4                    | 149/362 [02:14<04:11,  1.18s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.311236942972970815890902714604 완료 (149/362) | status=success | patch=51859 | 이번 환자: 1초 | 예상 남은 시간: 3분 12초

Build PaDiM slim dataset:  41%|##############5                    | 150/362 [02:15<03:53,  1.10s/it]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.325580698241281352835338693869 완료 (150/362) | status=success | patch=28349 | 이번 환자: 0초 | 예상 남은 시간: 3분 11초

Build PaDiM slim dataset:  42%|##############5                    | 151/362 [02:15<03:15,  1.08it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.470912100568074901744259213968 완료 (151/362) | status=success | patch=12549 | 이번 환자: 0초 | 예상 남은 시간: 3분 9초

Build PaDiM slim dataset:  42%|##############6                    | 152/362 [02:16<03:17,  1.06it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.504324996863016748259361352296 완료 (152/362) | status=success | patch=29706 | 이번 환자: 0초 | 예상 남은 시간: 3분 8초

Build PaDiM slim dataset:  42%|##############7                    | 153/362 [02:17<03:16,  1.06it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.669518152156802508672627785405 완료 (153/362) | status=success | patch=28155 | 이번 환자: 0초 | 예상 남은 시간: 3분 8초

Build PaDiM slim dataset:  43%|##############8                    | 154/362 [02:18<02:59,  1.16it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.707218743153927597786179232739 완료 (154/362) | status=success | patch=18863 | 이번 환자: 0초 | 예상 남은 시간: 3분 6초

Build PaDiM slim dataset:  43%|##############9                    | 155/362 [02:19<02:51,  1.21it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.743969234977916254223533321294 완료 (155/362) | status=success | patch=21761 | 이번 환자: 0초 | 예상 남은 시간: 3분 5초

Build PaDiM slim dataset:  43%|###############                    | 156/362 [02:20<03:15,  1.05it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.776429308535398795601496131524 완료 (156/362) | status=success | patch=39692 | 이번 환자: 1초 | 예상 남은 시간: 3분 5초

Build PaDiM slim dataset:  43%|###############1                   | 157/362 [02:20<02:36,  1.31it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.803808126682275425758092691689 완료 (157/362) | status=success | patch=7594 | 이번 환자: 0초 | 예상 남은 시간: 3분 3초

Build PaDiM slim dataset:  44%|###############2                   | 158/362 [02:21<03:03,  1.11it/s]

[PADIM] subset2_1.3.6.1.4.1.14519.5.2.1.6279.6001.885292267869246639232975687131 완료 (158/362) | status=success | patch=39459 | 이번 환자: 1초 | 예상 남은 시간: 3분 3초

Build PaDiM slim dataset:  44%|###############3                   | 159/362 [02:23<03:13,  1.05it/s]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.100620385482151095585000946543 완료 (159/362) | status=success | patch=34643 | 이번 환자: 1초 | 예상 남은 시간: 3분 2초

Build PaDiM slim dataset:  44%|###############4                   | 160/362 [02:24<03:20,  1.01it/s]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.125356649712550043958727288500 완료 (160/362) | status=success | patch=35438 | 이번 환자: 1초 | 예상 남은 시간: 3분 1초

Build PaDiM slim dataset:  44%|###############5                   | 161/362 [02:25<03:34,  1.07s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.145474881373882284343459153872 완료 (161/362) | status=success | patch=40924 | 이번 환자: 1초 | 예상 남은 시간: 3분 1초

Build PaDiM slim dataset:  45%|###############6                   | 162/362 [02:26<03:40,  1.10s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.160216916075817913953530562493 완료 (162/362) | status=success | patch=38817 | 이번 환자: 1초 | 예상 남은 시간: 3분 0초

Build PaDiM slim dataset:  45%|###############7                   | 163/362 [02:27<03:18,  1.00it/s]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.177985905159808659201278495182 완료 (163/362) | status=success | patch=21857 | 이번 환자: 0초 | 예상 남은 시간: 2분 59초

Build PaDiM slim dataset:  45%|###############8                   | 164/362 [02:28<03:36,  1.09s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.191617711875409989053242965150 완료 (164/362) | status=success | patch=42690 | 이번 환자: 1초 | 예상 남은 시간: 2분 59초

Build PaDiM slim dataset:  46%|###############9                   | 165/362 [02:29<03:33,  1.08s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.199069398344356765037879821616 완료 (165/362) | status=success | patch=34960 | 이번 환자: 0초 | 예상 남은 시간: 2분 58초

Build PaDiM slim dataset:  46%|################                   | 166/362 [02:30<03:32,  1.08s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.202476538079060560282495099956 완료 (166/362) | status=success | patch=34731 | 이번 환자: 1초 | 예상 남은 시간: 2분 57초

Build PaDiM slim dataset:  46%|################1                  | 167/362 [02:31<03:33,  1.09s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.203741923654363010377298352671 완료 (167/362) | status=success | patch=35411 | 이번 환자: 1초 | 예상 남은 시간: 2분 57초

Build PaDiM slim dataset:  46%|################2                  | 168/362 [02:32<03:24,  1.06s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.205852555362702089950453265567 완료 (168/362) | status=success | patch=29948 | 이번 환자: 0초 | 예상 남은 시간: 2분 56초

Build PaDiM slim dataset:  47%|################3                  | 169/362 [02:33<02:49,  1.14it/s]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.210426531621179400035178209430 완료 (169/362) | status=success | patch=12114 | 이번 환자: 0초 | 예상 남은 시간: 2분 55초

Build PaDiM slim dataset:  47%|################4                  | 170/362 [02:34<03:31,  1.10s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.215086589927307766627151367533 완료 (170/362) | status=success | patch=53387 | 이번 환자: 1초 | 예상 남은 시간: 2분 54초

Build PaDiM slim dataset:  47%|################5                  | 171/362 [02:35<03:21,  1.06s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.229664630348267553620068691756 완료 (171/362) | status=success | patch=30834 | 이번 환자: 0초 | 예상 남은 시간: 2분 54초

Build PaDiM slim dataset:  48%|################6                  | 172/362 [02:36<02:48,  1.13it/s]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.264090899378396711987322794314 완료 (172/362) | status=success | patch=12412 | 이번 환자: 0초 | 예상 남은 시간: 2분 52초

Build PaDiM slim dataset:  48%|################7                  | 173/362 [02:37<03:12,  1.02s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.268589491017129166376960414534 완료 (173/362) | status=success | patch=44144 | 이번 환자: 1초 | 예상 남은 시간: 2분 52초

Build PaDiM slim dataset:  48%|################8                  | 174/362 [02:38<02:44,  1.14it/s]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.268838889380981659524993261082 완료 (174/362) | status=success | patch=14893 | 이번 환자: 0초 | 예상 남은 시간: 2분 50초

Build PaDiM slim dataset:  48%|################9                  | 175/362 [02:39<02:57,  1.06it/s]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.314519596680450457855054746285 완료 (175/362) | status=success | patch=36077 | 이번 환자: 1초 | 예상 남은 시간: 2분 50초

Build PaDiM slim dataset:  49%|#################                  | 176/362 [02:40<02:58,  1.04it/s]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.319009811633846643966578282371 완료 (176/362) | status=success | patch=31615 | 이번 환자: 0초 | 예상 남은 시간: 2분 49초

Build PaDiM slim dataset:  49%|#################1                 | 177/362 [02:41<03:19,  1.08s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.334022941831199910030220864961 완료 (177/362) | status=success | patch=44028 | 이번 환자: 1초 | 예상 남은 시간: 2분 48초

Build PaDiM slim dataset:  49%|#################2                 | 178/362 [02:42<02:54,  1.05it/s]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.398955972049286139436103068984 완료 (178/362) | status=success | patch=17488 | 이번 환자: 0초 | 예상 남은 시간: 2분 47초

Build PaDiM slim dataset:  49%|#################3                 | 179/362 [02:43<03:00,  1.01it/s]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.619372068417051974713149104919 완료 (179/362) | status=success | patch=32920 | 이번 환자: 1초 | 예상 남은 시간: 2분 47초

Build PaDiM slim dataset:  50%|#################4                 | 180/362 [02:44<03:11,  1.05s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.710845873679853791427022019413 완료 (180/362) | status=success | patch=39585 | 이번 환자: 1초 | 예상 남은 시간: 2분 46초

Build PaDiM slim dataset:  50%|#################5                 | 181/362 [02:45<03:03,  1.02s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.965620538050807352935663552285 완료 (181/362) | status=success | patch=30430 | 이번 환자: 0초 | 예상 남은 시간: 2분 45초

Build PaDiM slim dataset:  50%|#################5                 | 182/362 [02:46<03:02,  1.02s/it]

[PADIM] subset3_1.3.6.1.4.1.14519.5.2.1.6279.6001.969607480572818589276327766720 완료 (182/362) | status=success | patch=33059 | 이번 환자: 0초 | 예상 남은 시간: 2분 44초

Build PaDiM slim dataset:  51%|#################6                 | 183/362 [02:47<02:52,  1.04it/s]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.100530488926682752765845212286 완료 (183/362) | status=success | patch=24815 | 이번 환자: 0초 | 예상 남은 시간: 2분 43초

Build PaDiM slim dataset:  51%|#################7                 | 184/362 [02:47<02:31,  1.17it/s]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.103115201714075993579787468219 완료 (184/362) | status=success | patch=15838 | 이번 환자: 0초 | 예상 남은 시간: 2분 42초

Build PaDiM slim dataset:  51%|#################8                 | 185/362 [02:48<02:10,  1.35it/s]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.104780906131535625872840889059 완료 (185/362) | status=success | patch=12412 | 이번 환자: 0초 | 예상 남은 시간: 2분 41초

Build PaDiM slim dataset:  51%|#################9                 | 186/362 [02:49<02:50,  1.03it/s]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.125067060506283419853742462394 완료 (186/362) | status=success | patch=49341 | 이번 환자: 1초 | 예상 남은 시간: 2분 40초

Build PaDiM slim dataset:  52%|##################                 | 187/362 [02:50<02:49,  1.03it/s]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.145283812746259413053188838096 완료 (187/362) | status=success | patch=30691 | 이번 환자: 0초 | 예상 남은 시간: 2분 39초

Build PaDiM slim dataset:  52%|##################1                | 188/362 [02:52<03:03,  1.06s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.156821379677057223126714881626 완료 (188/362) | status=success | patch=43121 | 이번 환자: 1초 | 예상 남은 시간: 2분 39초

Build PaDiM slim dataset:  52%|##################2                | 189/362 [02:53<02:51,  1.01it/s]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.163931625580639955914619627409 완료 (189/362) | status=success | patch=26164 | 이번 환자: 0초 | 예상 남은 시간: 2분 38초

Build PaDiM slim dataset:  52%|##################3                | 190/362 [02:53<02:45,  1.04it/s]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.200837896655745926888305239398 완료 (190/362) | status=success | patch=27341 | 이번 환자: 0초 | 예상 남은 시간: 2분 37초

Build PaDiM slim dataset:  53%|##################4                | 191/362 [02:55<02:54,  1.02s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.203179378754043776171267611064 완료 (191/362) | status=success | patch=36767 | 이번 환자: 1초 | 예상 남은 시간: 2분 36초

Build PaDiM slim dataset:  53%|##################5                | 192/362 [02:55<02:32,  1.12it/s]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.209269973797560820442292189762 완료 (192/362) | status=success | patch=16865 | 이번 환자: 0초 | 예상 남은 시간: 2분 35초

Build PaDiM slim dataset:  53%|##################6                | 193/362 [02:57<03:10,  1.13s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.211071908915618528829547301883 완료 (193/362) | status=success | patch=55697 | 이번 환자: 1초 | 예상 남은 시간: 2분 35초

Build PaDiM slim dataset:  54%|##################7                | 194/362 [02:58<03:13,  1.15s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.232011770495640253949434620907 완료 (194/362) | status=success | patch=40034 | 이번 환자: 1초 | 예상 남은 시간: 2분 34초

Build PaDiM slim dataset:  54%|##################8                | 195/362 [02:59<03:04,  1.10s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.232058316950007760548968840196 완료 (195/362) | status=success | patch=31047 | 이번 환자: 0초 | 예상 남은 시간: 2분 33초

Build PaDiM slim dataset:  54%|##################9                | 196/362 [03:00<03:09,  1.14s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.261678072503577216586082745513 완료 (196/362) | status=success | patch=40632 | 이번 환자: 1초 | 예상 남은 시간: 2분 33초

Build PaDiM slim dataset:  54%|###################                | 197/362 [03:01<03:11,  1.16s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.303865116731361029078599241306 완료 (197/362) | status=success | patch=38043 | 이번 환자: 1초 | 예상 남은 시간: 2분 32초

Build PaDiM slim dataset:  55%|###################1               | 198/362 [03:03<03:05,  1.13s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.304676828064484590312919543151 완료 (198/362) | status=success | patch=32914 | 이번 환자: 0초 | 예상 남은 시간: 2분 31초

Build PaDiM slim dataset:  55%|###################2               | 199/362 [03:03<02:51,  1.05s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.316393351033132458296975008261 완료 (199/362) | status=success | patch=23719 | 이번 환자: 0초 | 예상 남은 시간: 2분 30초

Build PaDiM slim dataset:  55%|###################3               | 200/362 [03:04<02:42,  1.00s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.320967206808467952819309001585 완료 (200/362) | status=success | patch=25653 | 이번 환자: 0초 | 예상 남은 시간: 2분 29초

Build PaDiM slim dataset:  56%|###################4               | 201/362 [03:06<02:51,  1.07s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.329326052298830421573852261436 완료 (201/362) | status=success | patch=38529 | 이번 환자: 1초 | 예상 남은 시간: 2분 28초

Build PaDiM slim dataset:  56%|###################5               | 202/362 [03:06<02:34,  1.04it/s]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.330425234131526435132846006585 완료 (202/362) | status=success | patch=22331 | 이번 환자: 0초 | 예상 남은 시간: 2분 27초

Build PaDiM slim dataset:  56%|###################6               | 203/362 [03:07<02:31,  1.05it/s]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.333319057944372470283038483725 완료 (203/362) | status=success | patch=27649 | 이번 환자: 0초 | 예상 남은 시간: 2분 26초

Build PaDiM slim dataset:  56%|###################7               | 204/362 [03:08<02:36,  1.01it/s]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.385151742584074711135621089321 완료 (204/362) | status=success | patch=35041 | 이번 환자: 1초 | 예상 남은 시간: 2분 26초

Build PaDiM slim dataset:  57%|###################8               | 205/362 [03:09<02:43,  1.04s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.390009458146468860187238398197 완료 (205/362) | status=success | patch=38736 | 이번 환자: 1초 | 예상 남은 시간: 2분 25초

Build PaDiM slim dataset:  57%|###################9               | 206/362 [03:11<03:24,  1.31s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.428038562098395445838061018440 완료 (206/362) | status=success | patch=66124 | 이번 환자: 1초 | 예상 남은 시간: 2분 25초

Build PaDiM slim dataset:  57%|####################               | 207/362 [03:13<03:27,  1.34s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.449254134266555649028108149727 완료 (207/362) | status=success | patch=46764 | 이번 환자: 1초 | 예상 남은 시간: 2분 24초

Build PaDiM slim dataset:  57%|####################1              | 208/362 [03:14<03:07,  1.22s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.811825890493256320617655474043 완료 (208/362) | status=success | patch=28587 | 이번 환자: 0초 | 예상 남은 시간: 2분 23초

Build PaDiM slim dataset:  58%|####################2              | 209/362 [03:15<02:53,  1.14s/it]

[PADIM] subset4_1.3.6.1.4.1.14519.5.2.1.6279.6001.885168397833922082085837240429 완료 (209/362) | status=success | patch=29284 | 이번 환자: 0초 | 예상 남은 시간: 2분 22초

Build PaDiM slim dataset:  58%|####################3              | 210/362 [03:15<02:36,  1.03s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.100332161840553388986847034053 완료 (210/362) | status=success | patch=21302 | 이번 환자: 0초 | 예상 남은 시간: 2분 21초

Build PaDiM slim dataset:  58%|####################4              | 211/362 [03:16<02:23,  1.05it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.101228986346984399347858840086 완료 (211/362) | status=success | patch=20160 | 이번 환자: 0초 | 예상 남은 시간: 2분 20초

Build PaDiM slim dataset:  59%|####################4              | 212/362 [03:17<02:32,  1.02s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.106419850406056634877579573537 완료 (212/362) | status=success | patch=37128 | 이번 환자: 1초 | 예상 남은 시간: 2분 19초

Build PaDiM slim dataset:  59%|####################5              | 213/362 [03:19<02:56,  1.19s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.111780708132595903430640048766 완료 (213/362) | status=success | patch=50353 | 이번 환자: 1초 | 예상 남은 시간: 2분 19초

Build PaDiM slim dataset:  59%|####################6              | 214/362 [03:20<02:54,  1.18s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.120196332569034738680965284519 완료 (214/362) | status=success | patch=38685 | 이번 환자: 1초 | 예상 남은 시간: 2분 18초

Build PaDiM slim dataset:  59%|####################7              | 215/362 [03:21<02:48,  1.15s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.133132722052053001903031735878 완료 (215/362) | status=success | patch=34569 | 이번 환자: 0초 | 예상 남은 시간: 2분 17초

Build PaDiM slim dataset:  60%|####################8              | 216/362 [03:22<02:50,  1.17s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.134638281277099121660656324702 완료 (216/362) | status=success | patch=37754 | 이번 환자: 1초 | 예상 남은 시간: 2분 17초

Build PaDiM slim dataset:  60%|####################9              | 217/362 [03:23<02:23,  1.01it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.138894439026794145866157853158 완료 (217/362) | status=success | patch=15415 | 이번 환자: 0초 | 예상 남은 시간: 2분 15초

Build PaDiM slim dataset:  60%|#####################              | 218/362 [03:24<02:24,  1.01s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.143410010885830403003179808334 완료 (218/362) | status=success | patch=31991 | 이번 환자: 0초 | 예상 남은 시간: 2분 15초

Build PaDiM slim dataset:  60%|#####################1             | 219/362 [03:25<02:12,  1.08it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.143782059748737055784173697516 완료 (219/362) | status=success | patch=20661 | 이번 환자: 0초 | 예상 남은 시간: 2분 13초

Build PaDiM slim dataset:  61%|#####################2             | 220/362 [03:26<02:19,  1.02it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.152706273988004688708784163325 완료 (220/362) | status=success | patch=35161 | 이번 환자: 1초 | 예상 남은 시간: 2분 13초

Build PaDiM slim dataset:  61%|#####################3             | 221/362 [03:28<02:47,  1.19s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.174935793360491516757154875981 완료 (221/362) | status=success | patch=55384 | 이번 환자: 1초 | 예상 남은 시간: 2분 12초

Build PaDiM slim dataset:  61%|#####################4             | 222/362 [03:29<02:44,  1.18s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.183056151780567460322586876100 완료 (222/362) | status=success | patch=35352 | 이번 환자: 1초 | 예상 남은 시간: 2분 11초

Build PaDiM slim dataset:  62%|#####################5             | 223/362 [03:29<02:26,  1.06s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.188484197846284733942365679565 완료 (223/362) | status=success | patch=23625 | 이번 환자: 0초 | 예상 남은 시간: 2분 10초

Build PaDiM slim dataset:  62%|#####################6             | 224/362 [03:30<02:21,  1.03s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.190144948425835566841437565646 완료 (224/362) | status=success | patch=29789 | 이번 환자: 0초 | 예상 남은 시간: 2분 9초

Build PaDiM slim dataset:  62%|#####################7             | 225/362 [03:31<02:16,  1.00it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.201890795870532056891161597218 완료 (225/362) | status=success | patch=28560 | 이번 환자: 0초 | 예상 남은 시간: 2분 8초

Build PaDiM slim dataset:  62%|#####################8             | 226/362 [03:32<02:11,  1.03it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.205615524269596458818376243313 완료 (226/362) | status=success | patch=27835 | 이번 환자: 0초 | 예상 남은 시간: 2분 7초

Build PaDiM slim dataset:  63%|#####################9             | 227/362 [03:33<02:21,  1.05s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.219281726101239572270900838145 완료 (227/362) | status=success | patch=37526 | 이번 환자: 1초 | 예상 남은 시간: 2분 7초

Build PaDiM slim dataset:  63%|######################             | 228/362 [03:35<02:29,  1.11s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.229171189693734694696158152904 완료 (228/362) | status=success | patch=40879 | 이번 환자: 1초 | 예상 남은 시간: 2분 6초

Build PaDiM slim dataset:  63%|######################1            | 229/362 [03:35<02:02,  1.08it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.234400932423244218697302970157 완료 (229/362) | status=success | patch=11965 | 이번 환자: 0초 | 예상 남은 시간: 2분 5초

Build PaDiM slim dataset:  64%|######################2            | 230/362 [03:36<01:45,  1.26it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.238042459915048190592571019348 완료 (230/362) | status=success | patch=12703 | 이번 환자: 0초 | 예상 남은 시간: 2분 4초

Build PaDiM slim dataset:  64%|######################3            | 231/362 [03:37<01:47,  1.22it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.245349763807614756148761326488 완료 (231/362) | status=success | patch=28033 | 이번 환자: 0초 | 예상 남은 시간: 2분 3초

Build PaDiM slim dataset:  64%|######################4            | 232/362 [03:38<01:59,  1.09it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.246589849815292078281051154201 완료 (232/362) | status=success | patch=36017 | 이번 환자: 1초 | 예상 남은 시간: 2분 2초

Build PaDiM slim dataset:  64%|######################5            | 233/362 [03:39<02:05,  1.03it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.285926554490515269336267972830 완료 (233/362) | status=success | patch=35084 | 이번 환자: 1초 | 예상 남은 시간: 2분 1초

Build PaDiM slim dataset:  65%|######################6            | 234/362 [03:40<02:08,  1.01s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.309955814083231537823157605135 완료 (234/362) | status=success | patch=35503 | 이번 환자: 1초 | 예상 남은 시간: 2분 0초

Build PaDiM slim dataset:  65%|######################7            | 235/362 [03:41<02:21,  1.11s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.328695385904874796172316226975 완료 (235/362) | status=success | patch=44357 | 이번 환자: 1초 | 예상 남은 시간: 1분 59초

Build PaDiM slim dataset:  65%|######################8            | 236/362 [03:43<02:26,  1.17s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.334184846571549530235084187602 완료 (236/362) | status=success | patch=42488 | 이번 환자: 1초 | 예상 남은 시간: 1분 59초

Build PaDiM slim dataset:  65%|######################9            | 237/362 [03:43<01:57,  1.07it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.397202838387416555106806022938 완료 (237/362) | status=success | patch=10307 | 이번 환자: 0초 | 예상 남은 시간: 1분 57초

Build PaDiM slim dataset:  66%|#######################            | 238/362 [03:44<02:00,  1.03it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.553241901808946577644850294647 완료 (238/362) | status=success | patch=33363 | 이번 환자: 1초 | 예상 남은 시간: 1분 56초

Build PaDiM slim dataset:  66%|#######################1           | 239/362 [03:45<02:04,  1.02s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.596908385953413160131451426904 완료 (239/362) | status=success | patch=35699 | 이번 환자: 1초 | 예상 남은 시간: 1분 56초

Build PaDiM slim dataset:  66%|#######################2           | 240/362 [03:47<02:19,  1.14s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.745109871503276594185453478952 완료 (240/362) | status=success | patch=47187 | 이번 환자: 1초 | 예상 남은 시간: 1분 55초

Build PaDiM slim dataset:  67%|#######################3           | 241/362 [03:47<01:59,  1.01it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.842980983137518332429408284002 완료 (241/362) | status=success | patch=17183 | 이번 환자: 0초 | 예상 남은 시간: 1분 54초

Build PaDiM slim dataset:  67%|#######################3           | 242/362 [03:48<02:01,  1.01s/it]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.910757789941076242457816491305 완료 (242/362) | status=success | patch=33758 | 이번 환자: 1초 | 예상 남은 시간: 1분 53초

Build PaDiM slim dataset:  67%|#######################4           | 243/362 [03:49<01:57,  1.02it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.980362852713685276785310240144 완료 (243/362) | status=success | patch=27824 | 이번 환자: 0초 | 예상 남은 시간: 1분 52초

Build PaDiM slim dataset:  67%|#######################5           | 244/362 [03:50<01:53,  1.04it/s]

[PADIM] subset5_1.3.6.1.4.1.14519.5.2.1.6279.6001.986011151772797848993829243183 완료 (244/362) | status=success | patch=28800 | 이번 환자: 0초 | 예상 남은 시간: 1분 51초

Build PaDiM slim dataset:  68%|#######################6           | 245/362 [03:51<01:45,  1.11it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.120842785645314664964010792308 완료 (245/362) | status=success | patch=21696 | 이번 환자: 0초 | 예상 남은 시간: 1분 50초

Build PaDiM slim dataset:  68%|#######################7           | 246/362 [03:52<01:55,  1.01it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.136830368929967292376608088362 완료 (246/362) | status=success | patch=40984 | 이번 환자: 1초 | 예상 남은 시간: 1분 49초

Build PaDiM slim dataset:  68%|#######################8           | 247/362 [03:53<01:54,  1.00it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.164790817284381538042494285101 완료 (247/362) | status=success | patch=32327 | 이번 환자: 0초 | 예상 남은 시간: 1분 48초

Build PaDiM slim dataset:  69%|#######################9           | 248/362 [03:54<02:00,  1.06s/it]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.171682845383273105440297561095 완료 (248/362) | status=success | patch=38932 | 이번 환자: 1초 | 예상 남은 시간: 1분 47초

Build PaDiM slim dataset:  69%|########################           | 249/362 [03:55<01:56,  1.03s/it]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.177888806135892723698313903329 완료 (249/362) | status=success | patch=29127 | 이번 환자: 0초 | 예상 남은 시간: 1분 46초

Build PaDiM slim dataset:  69%|########################1          | 250/362 [03:57<02:10,  1.17s/it]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.182798854785392200340436516930 완료 (250/362) | status=success | patch=48824 | 이번 환자: 1초 | 예상 남은 시간: 1분 46초

Build PaDiM slim dataset:  69%|########################2          | 251/362 [03:58<02:14,  1.22s/it]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.190937805243443708408459490152 완료 (251/362) | status=success | patch=44570 | 이번 환자: 1초 | 예상 남은 시간: 1분 45초

Build PaDiM slim dataset:  70%|########################3          | 252/362 [03:59<01:58,  1.08s/it]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.226564372605239604660221582288 완료 (252/362) | status=success | patch=22017 | 이번 환자: 0초 | 예상 남은 시간: 1분 44초

Build PaDiM slim dataset:  70%|########################4          | 253/362 [04:00<01:50,  1.01s/it]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.235217371152464582553341729176 완료 (253/362) | status=success | patch=26071 | 이번 환자: 0초 | 예상 남은 시간: 1분 43초

Build PaDiM slim dataset:  70%|########################5          | 254/362 [04:01<01:57,  1.09s/it]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.240630002689062442926543993263 완료 (254/362) | status=success | patch=42054 | 이번 환자: 1초 | 예상 남은 시간: 1분 42초

Build PaDiM slim dataset:  70%|########################6          | 255/362 [04:02<01:58,  1.11s/it]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.254138388912084634057282064266 완료 (255/362) | status=success | patch=35869 | 이번 환자: 1초 | 예상 남은 시간: 1분 41초

Build PaDiM slim dataset:  71%|########################7          | 256/362 [04:03<01:58,  1.12s/it]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.255409701134762680010928250229 완료 (256/362) | status=success | patch=37864 | 이번 환자: 1초 | 예상 남은 시간: 1분 40초

Build PaDiM slim dataset:  71%|########################8          | 257/362 [04:04<01:53,  1.08s/it]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.266009527139315622265711325223 완료 (257/362) | status=success | patch=30958 | 이번 환자: 0초 | 예상 남은 시간: 1분 39초

Build PaDiM slim dataset:  71%|########################9          | 258/362 [04:05<01:47,  1.03s/it]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.275849601663847251574860892603 완료 (258/362) | status=success | patch=30628 | 이번 환자: 0초 | 예상 남은 시간: 1분 39초

Build PaDiM slim dataset:  72%|#########################          | 259/362 [04:06<01:30,  1.14it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.290410217650314119074833254861 완료 (259/362) | status=success | patch=13640 | 이번 환자: 0초 | 예상 남은 시간: 1분 37초

Build PaDiM slim dataset:  72%|#########################1         | 260/362 [04:06<01:27,  1.17it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.297251044869095073091780740645 완료 (260/362) | status=success | patch=26734 | 이번 환자: 0초 | 예상 남은 시간: 1분 36초

Build PaDiM slim dataset:  72%|#########################2         | 261/362 [04:08<01:38,  1.03it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.306558074682524259000586270818 완료 (261/362) | status=success | patch=40397 | 이번 환자: 1초 | 예상 남은 시간: 1분 36초

Build PaDiM slim dataset:  72%|#########################3         | 262/362 [04:08<01:27,  1.15it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.307921770358136677021532761235 완료 (262/362) | status=success | patch=18992 | 이번 환자: 0초 | 예상 남은 시간: 1분 34초

Build PaDiM slim dataset:  73%|#########################4         | 263/362 [04:09<01:30,  1.09it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.308153138776443962077214577161 완료 (263/362) | status=success | patch=33862 | 이번 환자: 0초 | 예상 남은 시간: 1분 34초

Build PaDiM slim dataset:  73%|#########################5         | 264/362 [04:10<01:35,  1.03it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.313756547848086902190878548835 완료 (264/362) | status=success | patch=34846 | 이번 환자: 1초 | 예상 남은 시간: 1분 33초

Build PaDiM slim dataset:  73%|#########################6         | 265/362 [04:11<01:28,  1.10it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.341557859428950960906150406596 완료 (265/362) | status=success | patch=22623 | 이번 환자: 0초 | 예상 남은 시간: 1분 32초

Build PaDiM slim dataset:  73%|#########################7         | 266/362 [04:12<01:32,  1.04it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.414288023902112119945238126594 완료 (266/362) | status=success | patch=32720 | 이번 환자: 1초 | 예상 남은 시간: 1분 31초

Build PaDiM slim dataset:  74%|#########################8         | 267/362 [04:13<01:29,  1.06it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.463588161905537526756964393219 완료 (267/362) | status=success | patch=26815 | 이번 환자: 0초 | 예상 남은 시간: 1분 30초

Build PaDiM slim dataset:  74%|#########################9         | 268/362 [04:14<01:22,  1.14it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.465032801496479029639448332481 완료 (268/362) | status=success | patch=22574 | 이번 환자: 0초 | 예상 남은 시간: 1분 29초

Build PaDiM slim dataset:  74%|##########################         | 269/362 [04:15<01:17,  1.20it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.475325201787910087416720919680 완료 (269/362) | status=success | patch=22835 | 이번 환자: 0초 | 예상 남은 시간: 1분 28초

Build PaDiM slim dataset:  75%|##########################1        | 270/362 [04:16<01:19,  1.16it/s]

[PADIM] subset6_1.3.6.1.4.1.14519.5.2.1.6279.6001.561423049201987049884663740668 완료 (270/362) | status=success | patch=27597 | 이번 환자: 0초 | 예상 남은 시간: 1분 27초

Build PaDiM slim dataset:  75%|##########################2        | 271/362 [04:16<01:16,  1.18it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.116097642684124305074876564522 완료 (271/362) | status=success | patch=24390 | 이번 환자: 0초 | 예상 남은 시간: 1분 26초

Build PaDiM slim dataset:  75%|##########################2        | 272/362 [04:18<01:30,  1.01s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.116703382344406837243058680403 완료 (272/362) | status=success | patch=48006 | 이번 환자: 1초 | 예상 남은 시간: 1분 25초

Build PaDiM slim dataset:  75%|##########################3        | 273/362 [04:19<01:38,  1.11s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.131150737314367975651717513386 완료 (273/362) | status=success | patch=44154 | 이번 환자: 1초 | 예상 남은 시간: 1분 24초

Build PaDiM slim dataset:  76%|##########################4        | 274/362 [04:20<01:38,  1.12s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.139889514693390832525232698200 완료 (274/362) | status=success | patch=35545 | 이번 환자: 1초 | 예상 남은 시간: 1분 23초

Build PaDiM slim dataset:  76%|##########################5        | 275/362 [04:22<01:42,  1.17s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.143813757344903170810482790787 완료 (275/362) | status=success | patch=42905 | 이번 환자: 1초 | 예상 남은 시간: 1분 22초

Build PaDiM slim dataset:  76%|##########################6        | 276/362 [04:23<01:47,  1.25s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.151669338315069779994664893123 완료 (276/362) | status=success | patch=47497 | 이번 환자: 1초 | 예상 남은 시간: 1분 22초

Build PaDiM slim dataset:  77%|##########################7        | 277/362 [04:24<01:34,  1.12s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.159665703190517688573100822213 완료 (277/362) | status=success | patch=25480 | 이번 환자: 0초 | 예상 남은 시간: 1분 21초

Build PaDiM slim dataset:  77%|##########################8        | 278/362 [04:24<01:19,  1.06it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.163217526257871051722166468085 완료 (278/362) | status=success | patch=15678 | 이번 환자: 0초 | 예상 남은 시간: 1분 20초

Build PaDiM slim dataset:  77%|##########################9        | 279/362 [04:26<01:30,  1.08s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.167500254299688235071950909530 완료 (279/362) | status=success | patch=49844 | 이번 환자: 1초 | 예상 남은 시간: 1분 19초

Build PaDiM slim dataset:  77%|###########################        | 280/362 [04:27<01:23,  1.01s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.170825539570536865106681134236 완료 (280/362) | status=success | patch=25834 | 이번 환자: 0초 | 예상 남은 시간: 1분 18초

Build PaDiM slim dataset:  78%|###########################1       | 281/362 [04:27<01:09,  1.16it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.187803155574314810830688534991 완료 (281/362) | status=success | patch=13324 | 이번 환자: 0초 | 예상 남은 시간: 1분 17초

Build PaDiM slim dataset:  78%|###########################2       | 282/362 [04:28<01:01,  1.31it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.223650122819238796121876338881 완료 (282/362) | status=success | patch=14950 | 이번 환자: 0초 | 예상 남은 시간: 1분 16초

Build PaDiM slim dataset:  78%|###########################3       | 283/362 [04:28<00:59,  1.32it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.245546033414728092794968890929 완료 (283/362) | status=success | patch=21294 | 이번 환자: 0초 | 예상 남은 시간: 1분 15초

Build PaDiM slim dataset:  78%|###########################4       | 284/362 [04:29<00:57,  1.36it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.248360766706804179966476685510 완료 (284/362) | status=success | patch=19149 | 이번 환자: 0초 | 예상 남은 시간: 1분 14초

Build PaDiM slim dataset:  79%|###########################5       | 285/362 [04:30<00:59,  1.30it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.248425363469507808613979846863 완료 (285/362) | status=success | patch=27502 | 이번 환자: 0초 | 예상 남은 시간: 1분 13초

Build PaDiM slim dataset:  79%|###########################6       | 286/362 [04:31<01:03,  1.21it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.252709517998555732486024866345 완료 (286/362) | status=success | patch=30229 | 이번 환자: 0초 | 예상 남은 시간: 1분 12초

Build PaDiM slim dataset:  79%|###########################7       | 287/362 [04:32<01:09,  1.09it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.256542095129414948017808425649 완료 (287/362) | status=success | patch=37079 | 이번 환자: 1초 | 예상 남은 시간: 1분 11초

Build PaDiM slim dataset:  80%|###########################8       | 288/362 [04:33<01:12,  1.02it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.266581250778073944645044950856 완료 (288/362) | status=success | patch=36201 | 이번 환자: 1초 | 예상 남은 시간: 1분 10초

Build PaDiM slim dataset:  80%|###########################9       | 289/362 [04:35<01:19,  1.09s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.270788655216695628640355888562 완료 (289/362) | status=success | patch=44561 | 이번 환자: 1초 | 예상 남은 시간: 1분 9초

Build PaDiM slim dataset:  80%|############################       | 290/362 [04:36<01:22,  1.14s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.276351267409869539593937734609 완료 (290/362) | status=success | patch=41887 | 이번 환자: 1초 | 예상 남은 시간: 1분 8초

Build PaDiM slim dataset:  80%|############################1      | 291/362 [04:37<01:23,  1.18s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.279953669991076107785464313394 완료 (291/362) | status=success | patch=39602 | 이번 환자: 1초 | 예상 남은 시간: 1분 7초

Build PaDiM slim dataset:  81%|############################2      | 292/362 [04:38<01:17,  1.10s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.303066851236267189733420290986 완료 (292/362) | status=success | patch=28543 | 이번 환자: 0초 | 예상 남은 시간: 1분 6초

Build PaDiM slim dataset:  81%|############################3      | 293/362 [04:39<01:10,  1.03s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.306112617218006614029386065035 완료 (293/362) | status=success | patch=24589 | 이번 환자: 0초 | 예상 남은 시간: 1분 5초

Build PaDiM slim dataset:  81%|############################4      | 294/362 [04:40<01:07,  1.01it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.307946352302138765071461362398 완료 (294/362) | status=success | patch=27660 | 이번 환자: 0초 | 예상 남은 시간: 1분 4초

Build PaDiM slim dataset:  81%|############################5      | 295/362 [04:41<01:03,  1.05it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.314836406260772370397541392345 완료 (295/362) | status=success | patch=24904 | 이번 환자: 0초 | 예상 남은 시간: 1분 3초

Build PaDiM slim dataset:  82%|############################6      | 296/362 [04:42<01:06,  1.01s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.315918264676377418120578391325 완료 (296/362) | status=success | patch=36856 | 이번 환자: 1초 | 예상 남은 시간: 1분 2초

Build PaDiM slim dataset:  82%|############################7      | 297/362 [04:43<01:09,  1.08s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.336198008634390022174744544656 완료 (297/362) | status=success | patch=38548 | 이번 환자: 1초 | 예상 남은 시간: 1분 2초

Build PaDiM slim dataset:  82%|############################8      | 298/362 [04:44<01:16,  1.19s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.339039410276356623209709113755 완료 (298/362) | status=success | patch=47978 | 이번 환자: 1초 | 예상 남은 시간: 1분 1초

Build PaDiM slim dataset:  83%|############################9      | 299/362 [04:45<01:11,  1.14s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.447468612991222399440694673357 완료 (299/362) | status=success | patch=32201 | 이번 환자: 0초 | 예상 남은 시간: 1분 0초

Build PaDiM slim dataset:  83%|#############################      | 300/362 [04:47<01:15,  1.22s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.664409965623578819357819577077 완료 (300/362) | status=success | patch=44669 | 이번 환자: 1초 | 예상 남은 시간: 59초

Build PaDiM slim dataset:  83%|#############################1     | 301/362 [04:47<01:00,  1.02it/s]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.664989286137882319237192185951 완료 (301/362) | status=success | patch=10482 | 이번 환자: 0초 | 예상 남은 시간: 58초

Build PaDiM slim dataset:  83%|#############################1     | 302/362 [04:48<01:02,  1.05s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.686193079844756926365065559979 완료 (302/362) | status=success | patch=36667 | 이번 환자: 1초 | 예상 남은 시간: 57초

Build PaDiM slim dataset:  84%|#############################2     | 303/362 [04:50<01:03,  1.07s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.749871569713868632259874663577 완료 (303/362) | status=success | patch=32774 | 이번 환자: 1초 | 예상 남은 시간: 56초

Build PaDiM slim dataset:  84%|#############################3     | 304/362 [04:51<01:00,  1.04s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.897279226481700053115245043064 완료 (304/362) | status=success | patch=28666 | 이번 환자: 0초 | 예상 남은 시간: 55초

Build PaDiM slim dataset:  84%|#############################4     | 305/362 [04:52<00:59,  1.05s/it]

[PADIM] subset7_1.3.6.1.4.1.14519.5.2.1.6279.6001.957384617596077920906744920611 완료 (305/362) | status=success | patch=34384 | 이번 환자: 1초 | 예상 남은 시간: 54초

Build PaDiM slim dataset:  85%|#############################5     | 306/362 [04:53<01:01,  1.10s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.108193664222196923321844991231 완료 (306/362) | status=success | patch=38770 | 이번 환자: 1초 | 예상 남은 시간: 53초

Build PaDiM slim dataset:  85%|#############################6     | 307/362 [04:54<01:02,  1.14s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.153181766344026020914478182395 완료 (307/362) | status=success | patch=37265 | 이번 환자: 1초 | 예상 남은 시간: 52초

Build PaDiM slim dataset:  85%|#############################7     | 308/362 [04:55<00:59,  1.09s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.161633200801003804714818844696 완료 (308/362) | status=success | patch=27642 | 이번 환자: 0초 | 예상 남은 시간: 51초

Build PaDiM slim dataset:  85%|#############################8     | 309/362 [04:56<01:01,  1.17s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.161821150841552408667852639317 완료 (309/362) | status=success | patch=43679 | 이번 환자: 1초 | 예상 남은 시간: 50초

Build PaDiM slim dataset:  86%|#############################9     | 310/362 [04:58<01:10,  1.35s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.175318131822744218104175746898 완료 (310/362) | status=success | patch=57353 | 이번 환자: 1초 | 예상 남은 시간: 50초

Build PaDiM slim dataset:  86%|##############################     | 311/362 [04:59<00:59,  1.16s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.203425588524695836343069893813 완료 (311/362) | status=success | patch=19341 | 이번 환자: 0초 | 예상 남은 시간: 49초

Build PaDiM slim dataset:  86%|##############################1    | 312/362 [05:00<00:53,  1.07s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.236698827306171960683086245994 완료 (312/362) | status=success | patch=23586 | 이번 환자: 0초 | 예상 남은 시간: 48초

Build PaDiM slim dataset:  86%|##############################2    | 313/362 [05:01<00:52,  1.08s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.246178337114401749164850220976 완료 (313/362) | status=success | patch=33764 | 이번 환자: 1초 | 예상 남은 시간: 47초

Build PaDiM slim dataset:  87%|##############################3    | 314/362 [05:02<00:54,  1.14s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.253317247142837717905329340520 완료 (314/362) | status=success | patch=41853 | 이번 환자: 1초 | 예상 남은 시간: 46초

Build PaDiM slim dataset:  87%|##############################4    | 315/362 [05:03<00:52,  1.11s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.283878926524838648426928238498 완료 (315/362) | status=success | patch=30449 | 이번 환자: 0초 | 예상 남은 시간: 45초

Build PaDiM slim dataset:  87%|##############################5    | 316/362 [05:04<00:49,  1.07s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.286627485198831346082954437212 완료 (316/362) | status=success | patch=29680 | 이번 환자: 0초 | 예상 남은 시간: 44초

Build PaDiM slim dataset:  88%|##############################6    | 317/362 [05:05<00:47,  1.06s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.292049618819567427252971059233 완료 (317/362) | status=success | patch=32500 | 이번 환자: 0초 | 예상 남은 시간: 43초

Build PaDiM slim dataset:  88%|##############################7    | 318/362 [05:06<00:47,  1.08s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.296066944953051278419805374238 완료 (318/362) | status=success | patch=36818 | 이번 환자: 1초 | 예상 남은 시간: 42초

Build PaDiM slim dataset:  88%|##############################8    | 319/362 [05:07<00:43,  1.01s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.306520140119968755187868602181 완료 (319/362) | status=success | patch=26046 | 이번 환자: 0초 | 예상 남은 시간: 41초

Build PaDiM slim dataset:  88%|##############################9    | 320/362 [05:08<00:44,  1.05s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.317613170669207528926259976488 완료 (320/362) | status=success | patch=36352 | 이번 환자: 1초 | 예상 남은 시간: 40초

Build PaDiM slim dataset:  89%|###############################    | 321/362 [05:09<00:41,  1.01s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.324649110927013926557500550446 완료 (321/362) | status=success | patch=28044 | 이번 환자: 0초 | 예상 남은 시간: 39초

Build PaDiM slim dataset:  89%|###############################1   | 322/362 [05:10<00:41,  1.03s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.336102335330125765000317290445 완료 (322/362) | status=success | patch=33850 | 이번 환자: 1초 | 예상 남은 시간: 38초

Build PaDiM slim dataset:  89%|###############################2   | 323/362 [05:12<00:43,  1.11s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.339484970190920330170416228517 완료 (323/362) | status=success | patch=41082 | 이번 환자: 1초 | 예상 남은 시간: 37초

Build PaDiM slim dataset:  90%|###############################3   | 324/362 [05:13<00:43,  1.14s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.373433682859788429397781158572 완료 (324/362) | status=success | patch=38877 | 이번 환자: 1초 | 예상 남은 시간: 36초

Build PaDiM slim dataset:  90%|###############################4   | 325/362 [05:14<00:43,  1.17s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.608029415915051219877530734559 완료 (325/362) | status=success | patch=36750 | 이번 환자: 1초 | 예상 남은 시간: 35초

Build PaDiM slim dataset:  90%|###############################5   | 326/362 [05:15<00:37,  1.04s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.622243923620914676263059698181 완료 (326/362) | status=success | patch=19340 | 이번 환자: 0초 | 예상 남은 시간: 34초

Build PaDiM slim dataset:  90%|###############################6   | 327/362 [05:16<00:40,  1.16s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.671278273674156798801285503514 완료 (327/362) | status=success | patch=46783 | 이번 환자: 1초 | 예상 남은 시간: 33초

Build PaDiM slim dataset:  91%|###############################7   | 328/362 [05:17<00:35,  1.03s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.701514276942509393419164159551 완료 (328/362) | status=success | patch=21116 | 이번 환자: 0초 | 예상 남은 시간: 32초

Build PaDiM slim dataset:  91%|###############################8   | 329/362 [05:18<00:34,  1.05s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.766881513533845439335142582269 완료 (329/362) | status=success | patch=34718 | 이번 환자: 1초 | 예상 남은 시간: 31초

Build PaDiM slim dataset:  91%|###############################9   | 330/362 [05:19<00:32,  1.02s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.814122498113547115932318256859 완료 (330/362) | status=success | patch=28904 | 이번 환자: 0초 | 예상 남은 시간: 30초

Build PaDiM slim dataset:  91%|################################   | 331/362 [05:20<00:34,  1.12s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.888615810685807330497715730842 완료 (331/362) | status=success | patch=44598 | 이번 환자: 1초 | 예상 남은 시간: 30초

Build PaDiM slim dataset:  92%|################################   | 332/362 [05:21<00:33,  1.11s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.897161587681142256575045076919 완료 (332/362) | status=success | patch=35024 | 이번 환자: 0초 | 예상 남은 시간: 29초

Build PaDiM slim dataset:  92%|################################1  | 333/362 [05:22<00:29,  1.02s/it]

[PADIM] subset8_1.3.6.1.4.1.14519.5.2.1.6279.6001.939216568327879462530496768794 완료 (333/362) | status=success | patch=23064 | 이번 환자: 0초 | 예상 남은 시간: 28초

Build PaDiM slim dataset:  92%|################################2  | 334/362 [05:24<00:33,  1.19s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.109882169963817627559804568094 완료 (334/362) | status=success | patch=53010 | 이번 환자: 1초 | 예상 남은 시간: 27초

Build PaDiM slim dataset:  93%|################################3  | 335/362 [05:25<00:28,  1.06s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.121805476976020513950614465787 완료 (335/362) | status=success | patch=22028 | 이번 환자: 0초 | 예상 남은 시간: 26초

Build PaDiM slim dataset:  93%|################################4  | 336/362 [05:25<00:25,  1.02it/s]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.124656777236468248920498636247 완료 (336/362) | status=success | patch=22324 | 이번 환자: 0초 | 예상 남은 시간: 25초

Build PaDiM slim dataset:  93%|################################5  | 337/362 [05:27<00:27,  1.10s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.129650136453746261130135157590 완료 (337/362) | status=success | patch=44335 | 이번 환자: 1초 | 예상 남은 시간: 24초

Build PaDiM slim dataset:  93%|################################6  | 338/362 [05:28<00:28,  1.18s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.138674679709964033277400089532 완료 (338/362) | status=success | patch=45094 | 이번 환자: 1초 | 예상 남은 시간: 23초

Build PaDiM slim dataset:  94%|################################7  | 339/362 [05:29<00:25,  1.12s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.139577698050713461261415990027 완료 (339/362) | status=success | patch=29668 | 이번 환자: 0초 | 예상 남은 시간: 22초

Build PaDiM slim dataset:  94%|################################8  | 340/362 [05:30<00:25,  1.17s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.145510611155363050427743946446 완료 (340/362) | status=success | patch=42613 | 이번 환자: 1초 | 예상 남은 시간: 21초

Build PaDiM slim dataset:  94%|################################9  | 341/362 [05:31<00:23,  1.14s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.148935306123327835217659769212 완료 (341/362) | status=success | patch=34614 | 이번 환자: 1초 | 예상 남은 시간: 20초

Build PaDiM slim dataset:  94%|#################################  | 342/362 [05:32<00:21,  1.08s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.179683407589764683292800449011 완료 (342/362) | status=success | patch=26787 | 이번 환자: 0초 | 예상 남은 시간: 19초

Build PaDiM slim dataset:  95%|#################################1 | 343/362 [05:34<00:20,  1.09s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.193721075067404532739943086458 완료 (343/362) | status=success | patch=33793 | 이번 환자: 1초 | 예상 남은 시간: 18초

Build PaDiM slim dataset:  95%|#################################2 | 344/362 [05:35<00:18,  1.05s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.229960820686439513664996214638 완료 (344/362) | status=success | patch=29686 | 이번 환자: 0초 | 예상 남은 시간: 17초

Build PaDiM slim dataset:  95%|#################################3 | 345/362 [05:36<00:18,  1.09s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.237915456403882324748189195892 완료 (345/362) | status=success | patch=37591 | 이번 환자: 1초 | 예상 남은 시간: 16초

Build PaDiM slim dataset:  96%|#################################4 | 346/362 [05:37<00:16,  1.01s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.254929810944557499537650429296 완료 (346/362) | status=success | patch=24504 | 이번 환자: 0초 | 예상 남은 시간: 15초

Build PaDiM slim dataset:  96%|#################################5 | 347/362 [05:38<00:18,  1.21s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.259453428008507791234730686014 완료 (347/362) | status=success | patch=58165 | 이번 환자: 1초 | 예상 남은 시간: 14초

Build PaDiM slim dataset:  96%|#################################6 | 348/362 [05:39<00:15,  1.12s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.265570697208310960298668720669 완료 (348/362) | status=success | patch=29815 | 이번 환자: 0초 | 예상 남은 시간: 13초

Build PaDiM slim dataset:  96%|#################################7 | 349/362 [05:40<00:12,  1.07it/s]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.286061375572911414226912429210 완료 (349/362) | status=success | patch=13775 | 이번 환자: 0초 | 예상 남은 시간: 12초

Build PaDiM slim dataset:  97%|#################################8 | 350/362 [05:40<00:10,  1.12it/s]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.291156498203266896953765649282 완료 (350/362) | status=success | patch=24620 | 이번 환자: 0초 | 예상 남은 시간: 11초

Build PaDiM slim dataset:  97%|#################################9 | 351/362 [05:42<00:11,  1.07s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.292576688635952269497781991202 완료 (351/362) | status=success | patch=35460 | 이번 환자: 1초 | 예상 남은 시간: 10초

Build PaDiM slim dataset:  97%|################################## | 352/362 [05:43<00:10,  1.08s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.300392272203629213913702120739 완료 (352/362) | status=success | patch=36577 | 이번 환자: 1초 | 예상 남은 시간: 9초

Build PaDiM slim dataset:  98%|##################################1| 353/362 [05:44<00:09,  1.08s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.300693623747082239407271583452 완료 (353/362) | status=success | patch=35368 | 이번 환자: 1초 | 예상 남은 시간: 8초

Build PaDiM slim dataset:  98%|##################################2| 354/362 [05:45<00:08,  1.03s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.306140003699110313373771452136 완료 (354/362) | status=success | patch=29732 | 이번 환자: 0초 | 예상 남은 시간: 7초

Build PaDiM slim dataset:  98%|##################################3| 355/362 [05:46<00:07,  1.03s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.330043769832606379655473292782 완료 (355/362) | status=success | patch=32766 | 이번 환자: 0초 | 예상 남은 시간: 6초

Build PaDiM slim dataset:  98%|##################################4| 356/362 [05:47<00:06,  1.08s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.330643702676971528301859647742 완료 (356/362) | status=success | patch=39787 | 이번 환자: 1초 | 예상 남은 시간: 5초

Build PaDiM slim dataset:  99%|##################################5| 357/362 [05:49<00:05,  1.17s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.334166493392278943610545989413 완료 (357/362) | status=success | patch=45359 | 이번 환자: 1초 | 예상 남은 시간: 4초

Build PaDiM slim dataset:  99%|##################################6| 358/362 [05:49<00:04,  1.03s/it]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.340012777775661021262977442176 완료 (358/362) | status=success | patch=20997 | 이번 환자: 0초 | 예상 남은 시간: 3초

Build PaDiM slim dataset:  99%|##################################7| 359/362 [05:50<00:02,  1.07it/s]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.436403998650924660479049012235 완료 (359/362) | status=success | patch=19824 | 이번 환자: 0초 | 예상 남은 시간: 2초

Build PaDiM slim dataset:  99%|##################################8| 360/362 [05:51<00:01,  1.01it/s]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.472487466001405705666001578363 완료 (360/362) | status=success | patch=35369 | 이번 환자: 1초 | 예상 남은 시간: 1초

Build PaDiM slim dataset: 100%|##################################9| 361/362 [05:52<00:00,  1.02it/s]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.855232435861303786204450738044 완료 (361/362) | status=success | patch=29693 | 이번 환자: 0초 | 예상 남은 시간: 0초

Build PaDiM slim dataset: 100%|###################################| 362/362 [05:53<00:00,  1.03it/s]

[PADIM] subset9_1.3.6.1.4.1.14519.5.2.1.6279.6001.927394449308471452920270961822 완료 (362/362) | status=success | patch=16200 | 이번 환자: 0초 | 예상 남은 시간: 0초

========== BUILD PADIM TRAINING READY FINISHED ==========
OUT_ROOT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest
success / skipped rows: 362
errors: 0

Summarize PaDiM patch indexes: 100%|##############################| 362/362 [00:37<00:00,  9.71it/s]

========== FINAL PADIM OUTPUT ==========
OUT_ROOT: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest
volumes_npy: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest\volumes_npy
patch_index_by_patient: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest\patch_index_by_patient
manifests: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest\manifests
configs: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest\configs
logs: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest\logs

========== FILES ==========
patient_manifest: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest\manifests\patient_manifest.csv
train_val_test_split: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest\manifests\train_val_test_split.csv
patch_position_counts: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest\manifests\patch_position_counts.csv
patch_count_by_patient: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest\manifests\patch_count_by_patient.csv
split_position_counts: E:\jyp\ct_data_2d_preprocessed\Normal_LUNA16_padim_training_ready_v2_tslungguard_nochest\manifests\split_position_counts.csv

========== Position bin counts ==========

        position_bin  patch_count
0      lower_central       838632
1   lower_peripheral      2188356
2     middle_central      1721819
3  middle_peripheral      3787892
4      upper_central       995664
5   upper_peripheral      2146744

========== Patch count by patient summary ==========

count      362.000000
mean     32262.726519
std       9847.895441
min       7594.000000
25%      25986.750000
50%      32488.000000
75%      38226.250000
max      66124.000000
Name: patch_count, dtype: float64

========== Split count ==========

split
train    290
test      36
val       36
Name: count, dtype: int64

========== Split position counts ==========

    split       position_bin  patch_count
0    test      lower_central        77743
1    test   lower_peripheral       205502
2    test     middle_central       158316
3    test  middle_peripheral       348545
4    test      upper_central        95669
5    test   upper_peripheral       206600
6   train      lower_central       673587
7   train   lower_peripheral      1752912
8   train     middle_central      1383309
9   train  middle_peripheral      3036464
10  train      upper_central       792448
11  train   upper_peripheral      1710769
12    val      lower_central        87302
13    val   lower_peripheral       229942
14    val     middle_central       180194
15    val  middle_peripheral       402883
16    val      upper_central       107547
17    val   upper_peripheral       229375

========== Error count ==========
0

========== Size check ==========
OUT total: 71.02 GB
OUT volumes_npy: 67.92 GB
OUT patch_index_by_patient: 3.09 GB